/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BaseResponseListUserActivityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponseListUserActivityResponse{}

// BaseResponseListUserActivityResponse struct for BaseResponseListUserActivityResponse
type BaseResponseListUserActivityResponse struct {
	// Response status on whether the request succeeded
	Status *bool `json:"status,omitempty"`
	Data []UserActivityResponse `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
	Errors []ErrorModel `json:"errors,omitempty"`
	// Metadata
	Meta *MetaModel `json:"meta,omitempty"`
}

// NewBaseResponseListUserActivityResponse instantiates a new BaseResponseListUserActivityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponseListUserActivityResponse() *BaseResponseListUserActivityResponse {
	this := BaseResponseListUserActivityResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// NewBaseResponseListUserActivityResponseWithDefaults instantiates a new BaseResponseListUserActivityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponseListUserActivityResponseWithDefaults() *BaseResponseListUserActivityResponse {
	this := BaseResponseListUserActivityResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BaseResponseListUserActivityResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseListUserActivityResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BaseResponseListUserActivityResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *BaseResponseListUserActivityResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListUserActivityResponse) GetData() []UserActivityResponse {
	if o == nil {
		var ret []UserActivityResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListUserActivityResponse) GetDataOk() ([]UserActivityResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BaseResponseListUserActivityResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []UserActivityResponse and assigns it to the Data field.
func (o *BaseResponseListUserActivityResponse) SetData(v []UserActivityResponse) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListUserActivityResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListUserActivityResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *BaseResponseListUserActivityResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *BaseResponseListUserActivityResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *BaseResponseListUserActivityResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *BaseResponseListUserActivityResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetErrors returns the Errors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListUserActivityResponse) GetErrors() []ErrorModel {
	if o == nil {
		var ret []ErrorModel
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListUserActivityResponse) GetErrorsOk() ([]ErrorModel, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BaseResponseListUserActivityResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorModel and assigns it to the Errors field.
func (o *BaseResponseListUserActivityResponse) SetErrors(v []ErrorModel) {
	o.Errors = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BaseResponseListUserActivityResponse) GetMeta() MetaModel {
	if o == nil || IsNil(o.Meta) {
		var ret MetaModel
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseListUserActivityResponse) GetMetaOk() (*MetaModel, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BaseResponseListUserActivityResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaModel and assigns it to the Meta field.
func (o *BaseResponseListUserActivityResponse) SetMeta(v MetaModel) {
	o.Meta = &v
}

func (o BaseResponseListUserActivityResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponseListUserActivityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBaseResponseListUserActivityResponse struct {
	value *BaseResponseListUserActivityResponse
	isSet bool
}

func (v NullableBaseResponseListUserActivityResponse) Get() *BaseResponseListUserActivityResponse {
	return v.value
}

func (v *NullableBaseResponseListUserActivityResponse) Set(val *BaseResponseListUserActivityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponseListUserActivityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponseListUserActivityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponseListUserActivityResponse(val *BaseResponseListUserActivityResponse) *NullableBaseResponseListUserActivityResponse {
	return &NullableBaseResponseListUserActivityResponse{value: val, isSet: true}
}

func (v NullableBaseResponseListUserActivityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponseListUserActivityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


