/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ELFSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ELFSection{}

// ELFSection struct for ELFSection
type ELFSection struct {
	Name string `json:"name"`
	Type string `json:"type"`
	VirtualAddress int32 `json:"virtual_address"`
	VirtualSize int32 `json:"virtual_size"`
	RawSize int32 `json:"raw_size"`
	FileOffset int32 `json:"file_offset"`
	Flags string `json:"flags"`
	FlagsRaw int32 `json:"flags_raw"`
	Entropy float32 `json:"entropy"`
	Alignment int32 `json:"alignment"`
}

type _ELFSection ELFSection

// NewELFSection instantiates a new ELFSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewELFSection(name string, type_ string, virtualAddress int32, virtualSize int32, rawSize int32, fileOffset int32, flags string, flagsRaw int32, entropy float32, alignment int32) *ELFSection {
	this := ELFSection{}
	this.Name = name
	this.Type = type_
	this.VirtualAddress = virtualAddress
	this.VirtualSize = virtualSize
	this.RawSize = rawSize
	this.FileOffset = fileOffset
	this.Flags = flags
	this.FlagsRaw = flagsRaw
	this.Entropy = entropy
	this.Alignment = alignment
	return &this
}

// NewELFSectionWithDefaults instantiates a new ELFSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewELFSectionWithDefaults() *ELFSection {
	this := ELFSection{}
	return &this
}

// GetName returns the Name field value
func (o *ELFSection) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ELFSection) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ELFSection) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ELFSection) SetType(v string) {
	o.Type = v
}

// GetVirtualAddress returns the VirtualAddress field value
func (o *ELFSection) GetVirtualAddress() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VirtualAddress
}

// GetVirtualAddressOk returns a tuple with the VirtualAddress field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetVirtualAddressOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualAddress, true
}

// SetVirtualAddress sets field value
func (o *ELFSection) SetVirtualAddress(v int32) {
	o.VirtualAddress = v
}

// GetVirtualSize returns the VirtualSize field value
func (o *ELFSection) GetVirtualSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VirtualSize
}

// GetVirtualSizeOk returns a tuple with the VirtualSize field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetVirtualSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirtualSize, true
}

// SetVirtualSize sets field value
func (o *ELFSection) SetVirtualSize(v int32) {
	o.VirtualSize = v
}

// GetRawSize returns the RawSize field value
func (o *ELFSection) GetRawSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RawSize
}

// GetRawSizeOk returns a tuple with the RawSize field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetRawSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawSize, true
}

// SetRawSize sets field value
func (o *ELFSection) SetRawSize(v int32) {
	o.RawSize = v
}

// GetFileOffset returns the FileOffset field value
func (o *ELFSection) GetFileOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FileOffset
}

// GetFileOffsetOk returns a tuple with the FileOffset field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetFileOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileOffset, true
}

// SetFileOffset sets field value
func (o *ELFSection) SetFileOffset(v int32) {
	o.FileOffset = v
}

// GetFlags returns the Flags field value
func (o *ELFSection) GetFlags() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetFlagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Flags, true
}

// SetFlags sets field value
func (o *ELFSection) SetFlags(v string) {
	o.Flags = v
}

// GetFlagsRaw returns the FlagsRaw field value
func (o *ELFSection) GetFlagsRaw() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FlagsRaw
}

// GetFlagsRawOk returns a tuple with the FlagsRaw field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetFlagsRawOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagsRaw, true
}

// SetFlagsRaw sets field value
func (o *ELFSection) SetFlagsRaw(v int32) {
	o.FlagsRaw = v
}

// GetEntropy returns the Entropy field value
func (o *ELFSection) GetEntropy() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Entropy
}

// GetEntropyOk returns a tuple with the Entropy field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetEntropyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entropy, true
}

// SetEntropy sets field value
func (o *ELFSection) SetEntropy(v float32) {
	o.Entropy = v
}

// GetAlignment returns the Alignment field value
func (o *ELFSection) GetAlignment() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Alignment
}

// GetAlignmentOk returns a tuple with the Alignment field value
// and a boolean to check if the value has been set.
func (o *ELFSection) GetAlignmentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alignment, true
}

// SetAlignment sets field value
func (o *ELFSection) SetAlignment(v int32) {
	o.Alignment = v
}

func (o ELFSection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ELFSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["virtual_address"] = o.VirtualAddress
	toSerialize["virtual_size"] = o.VirtualSize
	toSerialize["raw_size"] = o.RawSize
	toSerialize["file_offset"] = o.FileOffset
	toSerialize["flags"] = o.Flags
	toSerialize["flags_raw"] = o.FlagsRaw
	toSerialize["entropy"] = o.Entropy
	toSerialize["alignment"] = o.Alignment
	return toSerialize, nil
}

func (o *ELFSection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"virtual_address",
		"virtual_size",
		"raw_size",
		"file_offset",
		"flags",
		"flags_raw",
		"entropy",
		"alignment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varELFSection := _ELFSection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varELFSection)

	if err != nil {
		return err
	}

	*o = ELFSection(varELFSection)

	return err
}

type NullableELFSection struct {
	value *ELFSection
	isSet bool
}

func (v NullableELFSection) Get() *ELFSection {
	return v.value
}

func (v *NullableELFSection) Set(val *ELFSection) {
	v.value = val
	v.isSet = true
}

func (v NullableELFSection) IsSet() bool {
	return v.isSet
}

func (v *NullableELFSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableELFSection(val *ELFSection) *NullableELFSection {
	return &NullableELFSection{value: val, isSet: true}
}

func (v NullableELFSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableELFSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


