/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CalleesCallerFunctionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalleesCallerFunctionsResponse{}

// CalleesCallerFunctionsResponse struct for CalleesCallerFunctionsResponse
type CalleesCallerFunctionsResponse struct {
	// Base address of the binary
	BaseAddress int32 `json:"base_address"`
	// List of functions called by the target function
	Callees []CalleeFunctionInfo `json:"callees"`
	// List of functions that call the target function
	Callers []CallerFunctionInfo `json:"callers"`
}

type _CalleesCallerFunctionsResponse CalleesCallerFunctionsResponse

// NewCalleesCallerFunctionsResponse instantiates a new CalleesCallerFunctionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalleesCallerFunctionsResponse(baseAddress int32, callees []CalleeFunctionInfo, callers []CallerFunctionInfo) *CalleesCallerFunctionsResponse {
	this := CalleesCallerFunctionsResponse{}
	this.BaseAddress = baseAddress
	this.Callees = callees
	this.Callers = callers
	return &this
}

// NewCalleesCallerFunctionsResponseWithDefaults instantiates a new CalleesCallerFunctionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalleesCallerFunctionsResponseWithDefaults() *CalleesCallerFunctionsResponse {
	this := CalleesCallerFunctionsResponse{}
	return &this
}

// GetBaseAddress returns the BaseAddress field value
func (o *CalleesCallerFunctionsResponse) GetBaseAddress() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BaseAddress
}

// GetBaseAddressOk returns a tuple with the BaseAddress field value
// and a boolean to check if the value has been set.
func (o *CalleesCallerFunctionsResponse) GetBaseAddressOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseAddress, true
}

// SetBaseAddress sets field value
func (o *CalleesCallerFunctionsResponse) SetBaseAddress(v int32) {
	o.BaseAddress = v
}

// GetCallees returns the Callees field value
func (o *CalleesCallerFunctionsResponse) GetCallees() []CalleeFunctionInfo {
	if o == nil {
		var ret []CalleeFunctionInfo
		return ret
	}

	return o.Callees
}

// GetCalleesOk returns a tuple with the Callees field value
// and a boolean to check if the value has been set.
func (o *CalleesCallerFunctionsResponse) GetCalleesOk() ([]CalleeFunctionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Callees, true
}

// SetCallees sets field value
func (o *CalleesCallerFunctionsResponse) SetCallees(v []CalleeFunctionInfo) {
	o.Callees = v
}

// GetCallers returns the Callers field value
func (o *CalleesCallerFunctionsResponse) GetCallers() []CallerFunctionInfo {
	if o == nil {
		var ret []CallerFunctionInfo
		return ret
	}

	return o.Callers
}

// GetCallersOk returns a tuple with the Callers field value
// and a boolean to check if the value has been set.
func (o *CalleesCallerFunctionsResponse) GetCallersOk() ([]CallerFunctionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Callers, true
}

// SetCallers sets field value
func (o *CalleesCallerFunctionsResponse) SetCallers(v []CallerFunctionInfo) {
	o.Callers = v
}

func (o CalleesCallerFunctionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalleesCallerFunctionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base_address"] = o.BaseAddress
	toSerialize["callees"] = o.Callees
	toSerialize["callers"] = o.Callers
	return toSerialize, nil
}

func (o *CalleesCallerFunctionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_address",
		"callees",
		"callers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalleesCallerFunctionsResponse := _CalleesCallerFunctionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalleesCallerFunctionsResponse)

	if err != nil {
		return err
	}

	*o = CalleesCallerFunctionsResponse(varCalleesCallerFunctionsResponse)

	return err
}

type NullableCalleesCallerFunctionsResponse struct {
	value *CalleesCallerFunctionsResponse
	isSet bool
}

func (v NullableCalleesCallerFunctionsResponse) Get() *CalleesCallerFunctionsResponse {
	return v.value
}

func (v *NullableCalleesCallerFunctionsResponse) Set(val *CalleesCallerFunctionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCalleesCallerFunctionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCalleesCallerFunctionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalleesCallerFunctionsResponse(val *CalleesCallerFunctionsResponse) *NullableCalleesCallerFunctionsResponse {
	return &NullableCalleesCallerFunctionsResponse{value: val, isSet: true}
}

func (v NullableCalleesCallerFunctionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalleesCallerFunctionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


