/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProcessDumpsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessDumpsData{}

// ProcessDumpsData struct for ProcessDumpsData
type ProcessDumpsData struct {
	Count int32 `json:"count"`
	Dumps []ProcessDump `json:"dumps"`
}

type _ProcessDumpsData ProcessDumpsData

// NewProcessDumpsData instantiates a new ProcessDumpsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessDumpsData(count int32, dumps []ProcessDump) *ProcessDumpsData {
	this := ProcessDumpsData{}
	this.Count = count
	this.Dumps = dumps
	return &this
}

// NewProcessDumpsDataWithDefaults instantiates a new ProcessDumpsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessDumpsDataWithDefaults() *ProcessDumpsData {
	this := ProcessDumpsData{}
	return &this
}

// GetCount returns the Count field value
func (o *ProcessDumpsData) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ProcessDumpsData) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ProcessDumpsData) SetCount(v int32) {
	o.Count = v
}

// GetDumps returns the Dumps field value
func (o *ProcessDumpsData) GetDumps() []ProcessDump {
	if o == nil {
		var ret []ProcessDump
		return ret
	}

	return o.Dumps
}

// GetDumpsOk returns a tuple with the Dumps field value
// and a boolean to check if the value has been set.
func (o *ProcessDumpsData) GetDumpsOk() ([]ProcessDump, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dumps, true
}

// SetDumps sets field value
func (o *ProcessDumpsData) SetDumps(v []ProcessDump) {
	o.Dumps = v
}

func (o ProcessDumpsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessDumpsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["dumps"] = o.Dumps
	return toSerialize, nil
}

func (o *ProcessDumpsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"dumps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessDumpsData := _ProcessDumpsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcessDumpsData)

	if err != nil {
		return err
	}

	*o = ProcessDumpsData(varProcessDumpsData)

	return err
}

type NullableProcessDumpsData struct {
	value *ProcessDumpsData
	isSet bool
}

func (v NullableProcessDumpsData) Get() *ProcessDumpsData {
	return v.value
}

func (v *NullableProcessDumpsData) Set(val *ProcessDumpsData) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessDumpsData) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessDumpsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessDumpsData(val *ProcessDumpsData) *NullableProcessDumpsData {
	return &NullableProcessDumpsData{value: val, isSet: true}
}

func (v NullableProcessDumpsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessDumpsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


