/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Permissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Permissions{}

// Permissions struct for Permissions
type Permissions struct {
	CanExportSymbols bool `json:"can_export_symbols"`
	CanGeneratePdfReports bool `json:"can_generate_pdf_reports"`
	CanUseAiMalwareAnalysis bool `json:"can_use_ai_malware_analysis"`
	CanUseMalwareSandbox bool `json:"can_use_malware_sandbox"`
	CanUsePrivateAnalyses bool `json:"can_use_private_analyses"`
}

type _Permissions Permissions

// NewPermissions instantiates a new Permissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissions(canExportSymbols bool, canGeneratePdfReports bool, canUseAiMalwareAnalysis bool, canUseMalwareSandbox bool, canUsePrivateAnalyses bool) *Permissions {
	this := Permissions{}
	this.CanExportSymbols = canExportSymbols
	this.CanGeneratePdfReports = canGeneratePdfReports
	this.CanUseAiMalwareAnalysis = canUseAiMalwareAnalysis
	this.CanUseMalwareSandbox = canUseMalwareSandbox
	this.CanUsePrivateAnalyses = canUsePrivateAnalyses
	return &this
}

// NewPermissionsWithDefaults instantiates a new Permissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsWithDefaults() *Permissions {
	this := Permissions{}
	return &this
}

// GetCanExportSymbols returns the CanExportSymbols field value
func (o *Permissions) GetCanExportSymbols() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanExportSymbols
}

// GetCanExportSymbolsOk returns a tuple with the CanExportSymbols field value
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanExportSymbolsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanExportSymbols, true
}

// SetCanExportSymbols sets field value
func (o *Permissions) SetCanExportSymbols(v bool) {
	o.CanExportSymbols = v
}

// GetCanGeneratePdfReports returns the CanGeneratePdfReports field value
func (o *Permissions) GetCanGeneratePdfReports() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanGeneratePdfReports
}

// GetCanGeneratePdfReportsOk returns a tuple with the CanGeneratePdfReports field value
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanGeneratePdfReportsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanGeneratePdfReports, true
}

// SetCanGeneratePdfReports sets field value
func (o *Permissions) SetCanGeneratePdfReports(v bool) {
	o.CanGeneratePdfReports = v
}

// GetCanUseAiMalwareAnalysis returns the CanUseAiMalwareAnalysis field value
func (o *Permissions) GetCanUseAiMalwareAnalysis() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanUseAiMalwareAnalysis
}

// GetCanUseAiMalwareAnalysisOk returns a tuple with the CanUseAiMalwareAnalysis field value
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanUseAiMalwareAnalysisOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanUseAiMalwareAnalysis, true
}

// SetCanUseAiMalwareAnalysis sets field value
func (o *Permissions) SetCanUseAiMalwareAnalysis(v bool) {
	o.CanUseAiMalwareAnalysis = v
}

// GetCanUseMalwareSandbox returns the CanUseMalwareSandbox field value
func (o *Permissions) GetCanUseMalwareSandbox() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanUseMalwareSandbox
}

// GetCanUseMalwareSandboxOk returns a tuple with the CanUseMalwareSandbox field value
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanUseMalwareSandboxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanUseMalwareSandbox, true
}

// SetCanUseMalwareSandbox sets field value
func (o *Permissions) SetCanUseMalwareSandbox(v bool) {
	o.CanUseMalwareSandbox = v
}

// GetCanUsePrivateAnalyses returns the CanUsePrivateAnalyses field value
func (o *Permissions) GetCanUsePrivateAnalyses() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanUsePrivateAnalyses
}

// GetCanUsePrivateAnalysesOk returns a tuple with the CanUsePrivateAnalyses field value
// and a boolean to check if the value has been set.
func (o *Permissions) GetCanUsePrivateAnalysesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanUsePrivateAnalyses, true
}

// SetCanUsePrivateAnalyses sets field value
func (o *Permissions) SetCanUsePrivateAnalyses(v bool) {
	o.CanUsePrivateAnalyses = v
}

func (o Permissions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Permissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["can_export_symbols"] = o.CanExportSymbols
	toSerialize["can_generate_pdf_reports"] = o.CanGeneratePdfReports
	toSerialize["can_use_ai_malware_analysis"] = o.CanUseAiMalwareAnalysis
	toSerialize["can_use_malware_sandbox"] = o.CanUseMalwareSandbox
	toSerialize["can_use_private_analyses"] = o.CanUsePrivateAnalyses
	return toSerialize, nil
}

func (o *Permissions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"can_export_symbols",
		"can_generate_pdf_reports",
		"can_use_ai_malware_analysis",
		"can_use_malware_sandbox",
		"can_use_private_analyses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissions := _Permissions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissions)

	if err != nil {
		return err
	}

	*o = Permissions(varPermissions)

	return err
}

type NullablePermissions struct {
	value *Permissions
	isSet bool
}

func (v NullablePermissions) Get() *Permissions {
	return v.value
}

func (v *NullablePermissions) Set(val *Permissions) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissions(val *Permissions) *NullablePermissions {
	return &NullablePermissions{value: val, isSet: true}
}

func (v NullablePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


