/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// ModelName Custom enum for the model name
type ModelName string

// List of ModelName
const (
	MODELNAME_BINNET_0_7_X86_64_WINDOWS ModelName = "binnet-0.7-x86-64-windows"
	MODELNAME_BINNET_0_7_X86_64_LINUX ModelName = "binnet-0.7-x86-64-linux"
	MODELNAME_BINNET_0_7_X86_32_WINDOWS ModelName = "binnet-0.7-x86-32-windows"
	MODELNAME_BINNET_0_7_X86_32_LINUX ModelName = "binnet-0.7-x86-32-linux"
	MODELNAME_BINNET_0_7_ARM_64_WINDOWS ModelName = "binnet-0.7-arm-64-windows"
	MODELNAME_BINNET_0_7_ARM_64_LINUX ModelName = "binnet-0.7-arm-64-linux"
	MODELNAME_BINNET_0_7_X86_64_ANDROID ModelName = "binnet-0.7-x86-64-android"
	MODELNAME_BINNET_0_7_X86_32_ANDROID ModelName = "binnet-0.7-x86-32-android"
	MODELNAME_BINNET_0_7_ARM_64_ANDROID ModelName = "binnet-0.7-arm-64-android"
)

// All allowed values of ModelName enum
var AllowedModelNameEnumValues = []ModelName{
	"binnet-0.7-x86-64-windows",
	"binnet-0.7-x86-64-linux",
	"binnet-0.7-x86-32-windows",
	"binnet-0.7-x86-32-linux",
	"binnet-0.7-arm-64-windows",
	"binnet-0.7-arm-64-linux",
	"binnet-0.7-x86-64-android",
	"binnet-0.7-x86-32-android",
	"binnet-0.7-arm-64-android",
}

func (v *ModelName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelName(value)
	for _, existing := range AllowedModelNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelName", value)
}

// NewModelNameFromValue returns a pointer to a valid ModelName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewModelNameFromValue(v string) (*ModelName, error) {
	ev := ModelName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ModelName: valid values are %v", v, AllowedModelNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ModelName) IsValid() bool {
	for _, existing := range AllowedModelNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ModelName value
func (v ModelName) Ptr() *ModelName {
	return &v
}

type NullableModelName struct {
	value *ModelName
	isSet bool
}

func (v NullableModelName) Get() *ModelName {
	return v.value
}

func (v *NullableModelName) Set(val *ModelName) {
	v.value = val
	v.isSet = true
}

func (v NullableModelName) IsSet() bool {
	return v.isSet
}

func (v *NullableModelName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelName(val *ModelName) *NullableModelName {
	return &NullableModelName{value: val, isSet: true}
}

func (v NullableModelName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

