/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAnalysisStringsStatusOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnalysisStringsStatusOutputBody{}

// GetAnalysisStringsStatusOutputBody struct for GetAnalysisStringsStatusOutputBody
type GetAnalysisStringsStatusOutputBody struct {
	// String-extraction task status
	Status string `json:"status"`
}

type _GetAnalysisStringsStatusOutputBody GetAnalysisStringsStatusOutputBody

// NewGetAnalysisStringsStatusOutputBody instantiates a new GetAnalysisStringsStatusOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalysisStringsStatusOutputBody(status string) *GetAnalysisStringsStatusOutputBody {
	this := GetAnalysisStringsStatusOutputBody{}
	this.Status = status
	return &this
}

// NewGetAnalysisStringsStatusOutputBodyWithDefaults instantiates a new GetAnalysisStringsStatusOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalysisStringsStatusOutputBodyWithDefaults() *GetAnalysisStringsStatusOutputBody {
	this := GetAnalysisStringsStatusOutputBody{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetAnalysisStringsStatusOutputBody) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetAnalysisStringsStatusOutputBody) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetAnalysisStringsStatusOutputBody) SetStatus(v string) {
	o.Status = v
}

func (o GetAnalysisStringsStatusOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnalysisStringsStatusOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GetAnalysisStringsStatusOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAnalysisStringsStatusOutputBody := _GetAnalysisStringsStatusOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAnalysisStringsStatusOutputBody)

	if err != nil {
		return err
	}

	*o = GetAnalysisStringsStatusOutputBody(varGetAnalysisStringsStatusOutputBody)

	return err
}

type NullableGetAnalysisStringsStatusOutputBody struct {
	value *GetAnalysisStringsStatusOutputBody
	isSet bool
}

func (v NullableGetAnalysisStringsStatusOutputBody) Get() *GetAnalysisStringsStatusOutputBody {
	return v.value
}

func (v *NullableGetAnalysisStringsStatusOutputBody) Set(val *GetAnalysisStringsStatusOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalysisStringsStatusOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalysisStringsStatusOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalysisStringsStatusOutputBody(val *GetAnalysisStringsStatusOutputBody) *NullableGetAnalysisStringsStatusOutputBody {
	return &NullableGetAnalysisStringsStatusOutputBody{value: val, isSet: true}
}

func (v NullableGetAnalysisStringsStatusOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalysisStringsStatusOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


