/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagItem{}

// TagItem struct for TagItem
type TagItem struct {
	Name string `json:"name"`
	Origin string `json:"origin"`
	CollectionId NullableInt32 `json:"collection_id,omitempty"`
}

type _TagItem TagItem

// NewTagItem instantiates a new TagItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagItem(name string, origin string) *TagItem {
	this := TagItem{}
	this.Name = name
	this.Origin = origin
	return &this
}

// NewTagItemWithDefaults instantiates a new TagItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagItemWithDefaults() *TagItem {
	this := TagItem{}
	return &this
}

// GetName returns the Name field value
func (o *TagItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagItem) SetName(v string) {
	o.Name = v
}

// GetOrigin returns the Origin field value
func (o *TagItem) GetOrigin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *TagItem) GetOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *TagItem) SetOrigin(v string) {
	o.Origin = v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TagItem) GetCollectionId() int32 {
	if o == nil || IsNil(o.CollectionId.Get()) {
		var ret int32
		return ret
	}
	return *o.CollectionId.Get()
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TagItem) GetCollectionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionId.Get(), o.CollectionId.IsSet()
}

// HasCollectionId returns a boolean if a field has been set.
func (o *TagItem) HasCollectionId() bool {
	if o != nil && o.CollectionId.IsSet() {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given NullableInt32 and assigns it to the CollectionId field.
func (o *TagItem) SetCollectionId(v int32) {
	o.CollectionId.Set(&v)
}
// SetCollectionIdNil sets the value for CollectionId to be an explicit nil
func (o *TagItem) SetCollectionIdNil() {
	o.CollectionId.Set(nil)
}

// UnsetCollectionId ensures that no value is present for CollectionId, not even an explicit nil
func (o *TagItem) UnsetCollectionId() {
	o.CollectionId.Unset()
}

func (o TagItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["origin"] = o.Origin
	if o.CollectionId.IsSet() {
		toSerialize["collection_id"] = o.CollectionId.Get()
	}
	return toSerialize, nil
}

func (o *TagItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"origin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagItem := _TagItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagItem)

	if err != nil {
		return err
	}

	*o = TagItem(varTagItem)

	return err
}

type NullableTagItem struct {
	value *TagItem
	isSet bool
}

func (v NullableTagItem) Get() *TagItem {
	return v.value
}

func (v *NullableTagItem) Set(val *TagItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTagItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTagItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagItem(val *TagItem) *NullableTagItem {
	return &NullableTagItem{value: val, isSet: true}
}

func (v NullableTagItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


