/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the EventSTEPSTARTED type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventSTEPSTARTED{}

// EventSTEPSTARTED struct for EventSTEPSTARTED
type EventSTEPSTARTED struct {
	Data SseEventStepStartedData `json:"data"`
	// The event name.
	Event string `json:"event"`
	// The event ID.
	Id *int32 `json:"id,omitempty"`
	// The retry time in milliseconds.
	Retry *int32 `json:"retry,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EventSTEPSTARTED EventSTEPSTARTED

// NewEventSTEPSTARTED instantiates a new EventSTEPSTARTED object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventSTEPSTARTED(data SseEventStepStartedData, event string) *EventSTEPSTARTED {
	this := EventSTEPSTARTED{}
	this.Data = data
	this.Event = event
	return &this
}

// NewEventSTEPSTARTEDWithDefaults instantiates a new EventSTEPSTARTED object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventSTEPSTARTEDWithDefaults() *EventSTEPSTARTED {
	this := EventSTEPSTARTED{}
	return &this
}

// GetData returns the Data field value
func (o *EventSTEPSTARTED) GetData() SseEventStepStartedData {
	if o == nil {
		var ret SseEventStepStartedData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EventSTEPSTARTED) GetDataOk() (*SseEventStepStartedData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *EventSTEPSTARTED) SetData(v SseEventStepStartedData) {
	o.Data = v
}

// GetEvent returns the Event field value
func (o *EventSTEPSTARTED) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *EventSTEPSTARTED) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *EventSTEPSTARTED) SetEvent(v string) {
	o.Event = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EventSTEPSTARTED) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSTEPSTARTED) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EventSTEPSTARTED) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EventSTEPSTARTED) SetId(v int32) {
	o.Id = &v
}

// GetRetry returns the Retry field value if set, zero value otherwise.
func (o *EventSTEPSTARTED) GetRetry() int32 {
	if o == nil || IsNil(o.Retry) {
		var ret int32
		return ret
	}
	return *o.Retry
}

// GetRetryOk returns a tuple with the Retry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventSTEPSTARTED) GetRetryOk() (*int32, bool) {
	if o == nil || IsNil(o.Retry) {
		return nil, false
	}
	return o.Retry, true
}

// HasRetry returns a boolean if a field has been set.
func (o *EventSTEPSTARTED) HasRetry() bool {
	if o != nil && !IsNil(o.Retry) {
		return true
	}

	return false
}

// SetRetry gets a reference to the given int32 and assigns it to the Retry field.
func (o *EventSTEPSTARTED) SetRetry(v int32) {
	o.Retry = &v
}

func (o EventSTEPSTARTED) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventSTEPSTARTED) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["event"] = o.Event
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Retry) {
		toSerialize["retry"] = o.Retry
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventSTEPSTARTED) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventSTEPSTARTED := _EventSTEPSTARTED{}

	err = json.Unmarshal(data, &varEventSTEPSTARTED)

	if err != nil {
		return err
	}

	*o = EventSTEPSTARTED(varEventSTEPSTARTED)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "event")
		delete(additionalProperties, "id")
		delete(additionalProperties, "retry")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventSTEPSTARTED struct {
	value *EventSTEPSTARTED
	isSet bool
}

func (v NullableEventSTEPSTARTED) Get() *EventSTEPSTARTED {
	return v.value
}

func (v *NullableEventSTEPSTARTED) Set(val *EventSTEPSTARTED) {
	v.value = val
	v.isSet = true
}

func (v NullableEventSTEPSTARTED) IsSet() bool {
	return v.isSet
}

func (v *NullableEventSTEPSTARTED) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventSTEPSTARTED(val *EventSTEPSTARTED) *NullableEventSTEPSTARTED {
	return &NullableEventSTEPSTARTED{value: val, isSet: true}
}

func (v NullableEventSTEPSTARTED) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventSTEPSTARTED) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


