/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// AiDecompilationRating the model 'AiDecompilationRating'
type AiDecompilationRating string

// List of AiDecompilationRating
const (
	AIDECOMPILATIONRATING_POSITIVE AiDecompilationRating = "POSITIVE"
	AIDECOMPILATIONRATING_NEGATIVE AiDecompilationRating = "NEGATIVE"
	AIDECOMPILATIONRATING_NEUTRAL AiDecompilationRating = "NEUTRAL"
)

// All allowed values of AiDecompilationRating enum
var AllowedAiDecompilationRatingEnumValues = []AiDecompilationRating{
	"POSITIVE",
	"NEGATIVE",
	"NEUTRAL",
}

func (v *AiDecompilationRating) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AiDecompilationRating(value)
	for _, existing := range AllowedAiDecompilationRatingEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AiDecompilationRating", value)
}

// NewAiDecompilationRatingFromValue returns a pointer to a valid AiDecompilationRating
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAiDecompilationRatingFromValue(v string) (*AiDecompilationRating, error) {
	ev := AiDecompilationRating(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AiDecompilationRating: valid values are %v", v, AllowedAiDecompilationRatingEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AiDecompilationRating) IsValid() bool {
	for _, existing := range AllowedAiDecompilationRatingEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AiDecompilationRating value
func (v AiDecompilationRating) Ptr() *AiDecompilationRating {
	return &v
}

type NullableAiDecompilationRating struct {
	value *AiDecompilationRating
	isSet bool
}

func (v NullableAiDecompilationRating) Get() *AiDecompilationRating {
	return v.value
}

func (v *NullableAiDecompilationRating) Set(val *AiDecompilationRating) {
	v.value = val
	v.isSet = true
}

func (v NullableAiDecompilationRating) IsSet() bool {
	return v.isSet
}

func (v *NullableAiDecompilationRating) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiDecompilationRating(val *AiDecompilationRating) *NullableAiDecompilationRating {
	return &NullableAiDecompilationRating{value: val, isSet: true}
}

func (v NullableAiDecompilationRating) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiDecompilationRating) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

