/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CollectionCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionCreateRequest{}

// CollectionCreateRequest struct for CollectionCreateRequest
type CollectionCreateRequest struct {
	CollectionName string `json:"collection_name"`
	Description string `json:"description"`
	CollectionScope *CollectionScope `json:"collection_scope,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Binaries []int32 `json:"binaries,omitempty"`
	ModelId int32 `json:"model_id"`
}

type _CollectionCreateRequest CollectionCreateRequest

// NewCollectionCreateRequest instantiates a new CollectionCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionCreateRequest(collectionName string, description string, modelId int32) *CollectionCreateRequest {
	this := CollectionCreateRequest{}
	this.CollectionName = collectionName
	this.Description = description
	var collectionScope CollectionScope = COLLECTIONSCOPE_PRIVATE
	this.CollectionScope = &collectionScope
	this.ModelId = modelId
	return &this
}

// NewCollectionCreateRequestWithDefaults instantiates a new CollectionCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionCreateRequestWithDefaults() *CollectionCreateRequest {
	this := CollectionCreateRequest{}
	var collectionScope CollectionScope = COLLECTIONSCOPE_PRIVATE
	this.CollectionScope = &collectionScope
	return &this
}

// GetCollectionName returns the CollectionName field value
func (o *CollectionCreateRequest) GetCollectionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionName
}

// GetCollectionNameOk returns a tuple with the CollectionName field value
// and a boolean to check if the value has been set.
func (o *CollectionCreateRequest) GetCollectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionName, true
}

// SetCollectionName sets field value
func (o *CollectionCreateRequest) SetCollectionName(v string) {
	o.CollectionName = v
}

// GetDescription returns the Description field value
func (o *CollectionCreateRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CollectionCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CollectionCreateRequest) SetDescription(v string) {
	o.Description = v
}

// GetCollectionScope returns the CollectionScope field value if set, zero value otherwise.
func (o *CollectionCreateRequest) GetCollectionScope() CollectionScope {
	if o == nil || IsNil(o.CollectionScope) {
		var ret CollectionScope
		return ret
	}
	return *o.CollectionScope
}

// GetCollectionScopeOk returns a tuple with the CollectionScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionCreateRequest) GetCollectionScopeOk() (*CollectionScope, bool) {
	if o == nil || IsNil(o.CollectionScope) {
		return nil, false
	}
	return o.CollectionScope, true
}

// HasCollectionScope returns a boolean if a field has been set.
func (o *CollectionCreateRequest) HasCollectionScope() bool {
	if o != nil && !IsNil(o.CollectionScope) {
		return true
	}

	return false
}

// SetCollectionScope gets a reference to the given CollectionScope and assigns it to the CollectionScope field.
func (o *CollectionCreateRequest) SetCollectionScope(v CollectionScope) {
	o.CollectionScope = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CollectionCreateRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CollectionCreateRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CollectionCreateRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CollectionCreateRequest) SetTags(v []string) {
	o.Tags = v
}

// GetBinaries returns the Binaries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CollectionCreateRequest) GetBinaries() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.Binaries
}

// GetBinariesOk returns a tuple with the Binaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CollectionCreateRequest) GetBinariesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Binaries) {
		return nil, false
	}
	return o.Binaries, true
}

// HasBinaries returns a boolean if a field has been set.
func (o *CollectionCreateRequest) HasBinaries() bool {
	if o != nil && !IsNil(o.Binaries) {
		return true
	}

	return false
}

// SetBinaries gets a reference to the given []int32 and assigns it to the Binaries field.
func (o *CollectionCreateRequest) SetBinaries(v []int32) {
	o.Binaries = v
}

// GetModelId returns the ModelId field value
func (o *CollectionCreateRequest) GetModelId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *CollectionCreateRequest) GetModelIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *CollectionCreateRequest) SetModelId(v int32) {
	o.ModelId = v
}

func (o CollectionCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection_name"] = o.CollectionName
	toSerialize["description"] = o.Description
	if !IsNil(o.CollectionScope) {
		toSerialize["collection_scope"] = o.CollectionScope
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Binaries != nil {
		toSerialize["binaries"] = o.Binaries
	}
	toSerialize["model_id"] = o.ModelId
	return toSerialize, nil
}

func (o *CollectionCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"collection_name",
		"description",
		"model_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCollectionCreateRequest := _CollectionCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCollectionCreateRequest)

	if err != nil {
		return err
	}

	*o = CollectionCreateRequest(varCollectionCreateRequest)

	return err
}

type NullableCollectionCreateRequest struct {
	value *CollectionCreateRequest
	isSet bool
}

func (v NullableCollectionCreateRequest) Get() *CollectionCreateRequest {
	return v.value
}

func (v *NullableCollectionCreateRequest) Set(val *CollectionCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionCreateRequest(val *CollectionCreateRequest) *NullableCollectionCreateRequest {
	return &NullableCollectionCreateRequest{value: val, isSet: true}
}

func (v NullableCollectionCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


