/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCollectionInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCollectionInputBody{}

// CreateCollectionInputBody struct for CreateCollectionInputBody
type CreateCollectionInputBody struct {
	// Optional binary IDs to link to the collection.
	Binaries []int64 `json:"binaries,omitempty"`
	// Collection name.
	CollectionName string `json:"collection_name"`
	// Visibility scope.
	CollectionScope string `json:"collection_scope"`
	// Collection description.
	Description string `json:"description"`
	// Model ID the collection is associated with.
	ModelId int64 `json:"model_id"`
	// Optional tags to attach to the collection.
	Tags []string `json:"tags,omitempty"`
}

type _CreateCollectionInputBody CreateCollectionInputBody

// NewCreateCollectionInputBody instantiates a new CreateCollectionInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCollectionInputBody(collectionName string, collectionScope string, description string, modelId int64) *CreateCollectionInputBody {
	this := CreateCollectionInputBody{}
	this.CollectionName = collectionName
	this.CollectionScope = collectionScope
	this.Description = description
	this.ModelId = modelId
	return &this
}

// NewCreateCollectionInputBodyWithDefaults instantiates a new CreateCollectionInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCollectionInputBodyWithDefaults() *CreateCollectionInputBody {
	this := CreateCollectionInputBody{}
	var collectionScope string = "PRIVATE"
	this.CollectionScope = collectionScope
	return &this
}

// GetBinaries returns the Binaries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCollectionInputBody) GetBinaries() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.Binaries
}

// GetBinariesOk returns a tuple with the Binaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCollectionInputBody) GetBinariesOk() ([]int64, bool) {
	if o == nil || IsNil(o.Binaries) {
		return nil, false
	}
	return o.Binaries, true
}

// HasBinaries returns a boolean if a field has been set.
func (o *CreateCollectionInputBody) HasBinaries() bool {
	if o != nil && !IsNil(o.Binaries) {
		return true
	}

	return false
}

// SetBinaries gets a reference to the given []int64 and assigns it to the Binaries field.
func (o *CreateCollectionInputBody) SetBinaries(v []int64) {
	o.Binaries = v
}

// GetCollectionName returns the CollectionName field value
func (o *CreateCollectionInputBody) GetCollectionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionName
}

// GetCollectionNameOk returns a tuple with the CollectionName field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionInputBody) GetCollectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionName, true
}

// SetCollectionName sets field value
func (o *CreateCollectionInputBody) SetCollectionName(v string) {
	o.CollectionName = v
}

// GetCollectionScope returns the CollectionScope field value
func (o *CreateCollectionInputBody) GetCollectionScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectionScope
}

// GetCollectionScopeOk returns a tuple with the CollectionScope field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionInputBody) GetCollectionScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectionScope, true
}

// SetCollectionScope sets field value
func (o *CreateCollectionInputBody) SetCollectionScope(v string) {
	o.CollectionScope = v
}

// GetDescription returns the Description field value
func (o *CreateCollectionInputBody) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionInputBody) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateCollectionInputBody) SetDescription(v string) {
	o.Description = v
}

// GetModelId returns the ModelId field value
func (o *CreateCollectionInputBody) GetModelId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ModelId
}

// GetModelIdOk returns a tuple with the ModelId field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionInputBody) GetModelIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ModelId, true
}

// SetModelId sets field value
func (o *CreateCollectionInputBody) SetModelId(v int64) {
	o.ModelId = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCollectionInputBody) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCollectionInputBody) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateCollectionInputBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateCollectionInputBody) SetTags(v []string) {
	o.Tags = v
}

func (o CreateCollectionInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCollectionInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Binaries != nil {
		toSerialize["binaries"] = o.Binaries
	}
	toSerialize["collection_name"] = o.CollectionName
	toSerialize["collection_scope"] = o.CollectionScope
	toSerialize["description"] = o.Description
	toSerialize["model_id"] = o.ModelId
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *CreateCollectionInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"collection_name",
		"collection_scope",
		"description",
		"model_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCollectionInputBody := _CreateCollectionInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCollectionInputBody)

	if err != nil {
		return err
	}

	*o = CreateCollectionInputBody(varCreateCollectionInputBody)

	return err
}

type NullableCreateCollectionInputBody struct {
	value *CreateCollectionInputBody
	isSet bool
}

func (v NullableCreateCollectionInputBody) Get() *CreateCollectionInputBody {
	return v.value
}

func (v *NullableCreateCollectionInputBody) Set(val *CreateCollectionInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCollectionInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCollectionInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCollectionInputBody(val *CreateCollectionInputBody) *NullableCreateCollectionInputBody {
	return &NullableCreateCollectionInputBody{value: val, isSet: true}
}

func (v NullableCreateCollectionInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCollectionInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


