/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the XrefFromResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &XrefFromResponse{}

// XrefFromResponse struct for XrefFromResponse
type XrefFromResponse struct {
	Value NullableString `json:"value"`
	IsScalar NullableBool `json:"is_scalar,omitempty"`
	IsCall NullableBool `json:"is_call,omitempty"`
	IsData NullableBool `json:"is_data,omitempty"`
	IsString NullableBool `json:"is_string,omitempty"`
	RawData NullableString `json:"raw_data,omitempty"`
	Segment NullableSegmentInfo `json:"segment,omitempty"`
	OrigStrEncoding NullableString `json:"orig_str_encoding,omitempty"`
	XrefTo NullableString `json:"xref_to"`
	AdditionalProperties map[string]interface{}
}

type _XrefFromResponse XrefFromResponse

// NewXrefFromResponse instantiates a new XrefFromResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewXrefFromResponse(value NullableString, xrefTo NullableString) *XrefFromResponse {
	this := XrefFromResponse{}
	this.Value = value
	this.XrefTo = xrefTo
	return &this
}

// NewXrefFromResponseWithDefaults instantiates a new XrefFromResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewXrefFromResponseWithDefaults() *XrefFromResponse {
	this := XrefFromResponse{}
	return &this
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for string will be returned
func (o *XrefFromResponse) GetValue() string {
	if o == nil || o.Value.Get() == nil {
		var ret string
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *XrefFromResponse) SetValue(v string) {
	o.Value.Set(&v)
}

// GetIsScalar returns the IsScalar field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetIsScalar() bool {
	if o == nil || IsNil(o.IsScalar.Get()) {
		var ret bool
		return ret
	}
	return *o.IsScalar.Get()
}

// GetIsScalarOk returns a tuple with the IsScalar field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetIsScalarOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsScalar.Get(), o.IsScalar.IsSet()
}

// HasIsScalar returns a boolean if a field has been set.
func (o *XrefFromResponse) HasIsScalar() bool {
	if o != nil && o.IsScalar.IsSet() {
		return true
	}

	return false
}

// SetIsScalar gets a reference to the given NullableBool and assigns it to the IsScalar field.
func (o *XrefFromResponse) SetIsScalar(v bool) {
	o.IsScalar.Set(&v)
}
// SetIsScalarNil sets the value for IsScalar to be an explicit nil
func (o *XrefFromResponse) SetIsScalarNil() {
	o.IsScalar.Set(nil)
}

// UnsetIsScalar ensures that no value is present for IsScalar, not even an explicit nil
func (o *XrefFromResponse) UnsetIsScalar() {
	o.IsScalar.Unset()
}

// GetIsCall returns the IsCall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetIsCall() bool {
	if o == nil || IsNil(o.IsCall.Get()) {
		var ret bool
		return ret
	}
	return *o.IsCall.Get()
}

// GetIsCallOk returns a tuple with the IsCall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetIsCallOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsCall.Get(), o.IsCall.IsSet()
}

// HasIsCall returns a boolean if a field has been set.
func (o *XrefFromResponse) HasIsCall() bool {
	if o != nil && o.IsCall.IsSet() {
		return true
	}

	return false
}

// SetIsCall gets a reference to the given NullableBool and assigns it to the IsCall field.
func (o *XrefFromResponse) SetIsCall(v bool) {
	o.IsCall.Set(&v)
}
// SetIsCallNil sets the value for IsCall to be an explicit nil
func (o *XrefFromResponse) SetIsCallNil() {
	o.IsCall.Set(nil)
}

// UnsetIsCall ensures that no value is present for IsCall, not even an explicit nil
func (o *XrefFromResponse) UnsetIsCall() {
	o.IsCall.Unset()
}

// GetIsData returns the IsData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetIsData() bool {
	if o == nil || IsNil(o.IsData.Get()) {
		var ret bool
		return ret
	}
	return *o.IsData.Get()
}

// GetIsDataOk returns a tuple with the IsData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetIsDataOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsData.Get(), o.IsData.IsSet()
}

// HasIsData returns a boolean if a field has been set.
func (o *XrefFromResponse) HasIsData() bool {
	if o != nil && o.IsData.IsSet() {
		return true
	}

	return false
}

// SetIsData gets a reference to the given NullableBool and assigns it to the IsData field.
func (o *XrefFromResponse) SetIsData(v bool) {
	o.IsData.Set(&v)
}
// SetIsDataNil sets the value for IsData to be an explicit nil
func (o *XrefFromResponse) SetIsDataNil() {
	o.IsData.Set(nil)
}

// UnsetIsData ensures that no value is present for IsData, not even an explicit nil
func (o *XrefFromResponse) UnsetIsData() {
	o.IsData.Unset()
}

// GetIsString returns the IsString field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetIsString() bool {
	if o == nil || IsNil(o.IsString.Get()) {
		var ret bool
		return ret
	}
	return *o.IsString.Get()
}

// GetIsStringOk returns a tuple with the IsString field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetIsStringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsString.Get(), o.IsString.IsSet()
}

// HasIsString returns a boolean if a field has been set.
func (o *XrefFromResponse) HasIsString() bool {
	if o != nil && o.IsString.IsSet() {
		return true
	}

	return false
}

// SetIsString gets a reference to the given NullableBool and assigns it to the IsString field.
func (o *XrefFromResponse) SetIsString(v bool) {
	o.IsString.Set(&v)
}
// SetIsStringNil sets the value for IsString to be an explicit nil
func (o *XrefFromResponse) SetIsStringNil() {
	o.IsString.Set(nil)
}

// UnsetIsString ensures that no value is present for IsString, not even an explicit nil
func (o *XrefFromResponse) UnsetIsString() {
	o.IsString.Unset()
}

// GetRawData returns the RawData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetRawData() string {
	if o == nil || IsNil(o.RawData.Get()) {
		var ret string
		return ret
	}
	return *o.RawData.Get()
}

// GetRawDataOk returns a tuple with the RawData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetRawDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RawData.Get(), o.RawData.IsSet()
}

// HasRawData returns a boolean if a field has been set.
func (o *XrefFromResponse) HasRawData() bool {
	if o != nil && o.RawData.IsSet() {
		return true
	}

	return false
}

// SetRawData gets a reference to the given NullableString and assigns it to the RawData field.
func (o *XrefFromResponse) SetRawData(v string) {
	o.RawData.Set(&v)
}
// SetRawDataNil sets the value for RawData to be an explicit nil
func (o *XrefFromResponse) SetRawDataNil() {
	o.RawData.Set(nil)
}

// UnsetRawData ensures that no value is present for RawData, not even an explicit nil
func (o *XrefFromResponse) UnsetRawData() {
	o.RawData.Unset()
}

// GetSegment returns the Segment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetSegment() SegmentInfo {
	if o == nil || IsNil(o.Segment.Get()) {
		var ret SegmentInfo
		return ret
	}
	return *o.Segment.Get()
}

// GetSegmentOk returns a tuple with the Segment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetSegmentOk() (*SegmentInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Segment.Get(), o.Segment.IsSet()
}

// HasSegment returns a boolean if a field has been set.
func (o *XrefFromResponse) HasSegment() bool {
	if o != nil && o.Segment.IsSet() {
		return true
	}

	return false
}

// SetSegment gets a reference to the given NullableSegmentInfo and assigns it to the Segment field.
func (o *XrefFromResponse) SetSegment(v SegmentInfo) {
	o.Segment.Set(&v)
}
// SetSegmentNil sets the value for Segment to be an explicit nil
func (o *XrefFromResponse) SetSegmentNil() {
	o.Segment.Set(nil)
}

// UnsetSegment ensures that no value is present for Segment, not even an explicit nil
func (o *XrefFromResponse) UnsetSegment() {
	o.Segment.Unset()
}

// GetOrigStrEncoding returns the OrigStrEncoding field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *XrefFromResponse) GetOrigStrEncoding() string {
	if o == nil || IsNil(o.OrigStrEncoding.Get()) {
		var ret string
		return ret
	}
	return *o.OrigStrEncoding.Get()
}

// GetOrigStrEncodingOk returns a tuple with the OrigStrEncoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetOrigStrEncodingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrigStrEncoding.Get(), o.OrigStrEncoding.IsSet()
}

// HasOrigStrEncoding returns a boolean if a field has been set.
func (o *XrefFromResponse) HasOrigStrEncoding() bool {
	if o != nil && o.OrigStrEncoding.IsSet() {
		return true
	}

	return false
}

// SetOrigStrEncoding gets a reference to the given NullableString and assigns it to the OrigStrEncoding field.
func (o *XrefFromResponse) SetOrigStrEncoding(v string) {
	o.OrigStrEncoding.Set(&v)
}
// SetOrigStrEncodingNil sets the value for OrigStrEncoding to be an explicit nil
func (o *XrefFromResponse) SetOrigStrEncodingNil() {
	o.OrigStrEncoding.Set(nil)
}

// UnsetOrigStrEncoding ensures that no value is present for OrigStrEncoding, not even an explicit nil
func (o *XrefFromResponse) UnsetOrigStrEncoding() {
	o.OrigStrEncoding.Unset()
}

// GetXrefTo returns the XrefTo field value
// If the value is explicit nil, the zero value for string will be returned
func (o *XrefFromResponse) GetXrefTo() string {
	if o == nil || o.XrefTo.Get() == nil {
		var ret string
		return ret
	}

	return *o.XrefTo.Get()
}

// GetXrefToOk returns a tuple with the XrefTo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *XrefFromResponse) GetXrefToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.XrefTo.Get(), o.XrefTo.IsSet()
}

// SetXrefTo sets field value
func (o *XrefFromResponse) SetXrefTo(v string) {
	o.XrefTo.Set(&v)
}

func (o XrefFromResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o XrefFromResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value.Get()
	if o.IsScalar.IsSet() {
		toSerialize["is_scalar"] = o.IsScalar.Get()
	}
	if o.IsCall.IsSet() {
		toSerialize["is_call"] = o.IsCall.Get()
	}
	if o.IsData.IsSet() {
		toSerialize["is_data"] = o.IsData.Get()
	}
	if o.IsString.IsSet() {
		toSerialize["is_string"] = o.IsString.Get()
	}
	if o.RawData.IsSet() {
		toSerialize["raw_data"] = o.RawData.Get()
	}
	if o.Segment.IsSet() {
		toSerialize["segment"] = o.Segment.Get()
	}
	if o.OrigStrEncoding.IsSet() {
		toSerialize["orig_str_encoding"] = o.OrigStrEncoding.Get()
	}
	toSerialize["xref_to"] = o.XrefTo.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *XrefFromResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"xref_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varXrefFromResponse := _XrefFromResponse{}

	err = json.Unmarshal(data, &varXrefFromResponse)

	if err != nil {
		return err
	}

	*o = XrefFromResponse(varXrefFromResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "is_scalar")
		delete(additionalProperties, "is_call")
		delete(additionalProperties, "is_data")
		delete(additionalProperties, "is_string")
		delete(additionalProperties, "raw_data")
		delete(additionalProperties, "segment")
		delete(additionalProperties, "orig_str_encoding")
		delete(additionalProperties, "xref_to")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableXrefFromResponse struct {
	value *XrefFromResponse
	isSet bool
}

func (v NullableXrefFromResponse) Get() *XrefFromResponse {
	return v.value
}

func (v *NullableXrefFromResponse) Set(val *XrefFromResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableXrefFromResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableXrefFromResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableXrefFromResponse(val *XrefFromResponse) *NullableXrefFromResponse {
	return &NullableXrefFromResponse{value: val, isSet: true}
}

func (v NullableXrefFromResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableXrefFromResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


