/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FunctionSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionSearchResponse{}

// FunctionSearchResponse struct for FunctionSearchResponse
type FunctionSearchResponse struct {
	// The results of the search
	Results []FunctionSearchResult `json:"results"`
}

type _FunctionSearchResponse FunctionSearchResponse

// NewFunctionSearchResponse instantiates a new FunctionSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionSearchResponse(results []FunctionSearchResult) *FunctionSearchResponse {
	this := FunctionSearchResponse{}
	this.Results = results
	return &this
}

// NewFunctionSearchResponseWithDefaults instantiates a new FunctionSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionSearchResponseWithDefaults() *FunctionSearchResponse {
	this := FunctionSearchResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *FunctionSearchResponse) GetResults() []FunctionSearchResult {
	if o == nil {
		var ret []FunctionSearchResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *FunctionSearchResponse) GetResultsOk() ([]FunctionSearchResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *FunctionSearchResponse) SetResults(v []FunctionSearchResult) {
	o.Results = v
}

func (o FunctionSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *FunctionSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionSearchResponse := _FunctionSearchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFunctionSearchResponse)

	if err != nil {
		return err
	}

	*o = FunctionSearchResponse(varFunctionSearchResponse)

	return err
}

type NullableFunctionSearchResponse struct {
	value *FunctionSearchResponse
	isSet bool
}

func (v NullableFunctionSearchResponse) Get() *FunctionSearchResponse {
	return v.value
}

func (v *NullableFunctionSearchResponse) Set(val *FunctionSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionSearchResponse(val *FunctionSearchResponse) *NullableFunctionSearchResponse {
	return &NullableFunctionSearchResponse{value: val, isSet: true}
}

func (v NullableFunctionSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


