/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the StageEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StageEvent{}

// StageEvent struct for StageEvent
type StageEvent struct {
	Stage AnalysisStage `json:"stage"`
	Status AnalysisStageStatus `json:"status"`
	Timestamp string `json:"timestamp"`
	AdditionalProperties map[string]interface{}
}

type _StageEvent StageEvent

// NewStageEvent instantiates a new StageEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStageEvent(stage AnalysisStage, status AnalysisStageStatus, timestamp string) *StageEvent {
	this := StageEvent{}
	this.Stage = stage
	this.Status = status
	this.Timestamp = timestamp
	return &this
}

// NewStageEventWithDefaults instantiates a new StageEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStageEventWithDefaults() *StageEvent {
	this := StageEvent{}
	return &this
}

// GetStage returns the Stage field value
func (o *StageEvent) GetStage() AnalysisStage {
	if o == nil {
		var ret AnalysisStage
		return ret
	}

	return o.Stage
}

// GetStageOk returns a tuple with the Stage field value
// and a boolean to check if the value has been set.
func (o *StageEvent) GetStageOk() (*AnalysisStage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stage, true
}

// SetStage sets field value
func (o *StageEvent) SetStage(v AnalysisStage) {
	o.Stage = v
}

// GetStatus returns the Status field value
func (o *StageEvent) GetStatus() AnalysisStageStatus {
	if o == nil {
		var ret AnalysisStageStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StageEvent) GetStatusOk() (*AnalysisStageStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StageEvent) SetStatus(v AnalysisStageStatus) {
	o.Status = v
}

// GetTimestamp returns the Timestamp field value
func (o *StageEvent) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *StageEvent) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *StageEvent) SetTimestamp(v string) {
	o.Timestamp = v
}

func (o StageEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StageEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stage"] = o.Stage
	toSerialize["status"] = o.Status
	toSerialize["timestamp"] = o.Timestamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StageEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stage",
		"status",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStageEvent := _StageEvent{}

	err = json.Unmarshal(data, &varStageEvent)

	if err != nil {
		return err
	}

	*o = StageEvent(varStageEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "stage")
		delete(additionalProperties, "status")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStageEvent struct {
	value *StageEvent
	isSet bool
}

func (v NullableStageEvent) Get() *StageEvent {
	return v.value
}

func (v *NullableStageEvent) Set(val *StageEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableStageEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableStageEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStageEvent(val *StageEvent) *NullableStageEvent {
	return &NullableStageEvent{value: val, isSet: true}
}

func (v NullableStageEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStageEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


