/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FunctionInfoInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionInfoInput{}

// FunctionInfoInput struct for FunctionInfoInput
type FunctionInfoInput struct {
	FuncTypes NullableFunctionTypeInput `json:"func_types,omitempty"`
	// List of function dependencies
	FuncDeps []FuncDepsInner `json:"func_deps"`
}

type _FunctionInfoInput FunctionInfoInput

// NewFunctionInfoInput instantiates a new FunctionInfoInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionInfoInput(funcDeps []FuncDepsInner) *FunctionInfoInput {
	this := FunctionInfoInput{}
	this.FuncDeps = funcDeps
	return &this
}

// NewFunctionInfoInputWithDefaults instantiates a new FunctionInfoInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionInfoInputWithDefaults() *FunctionInfoInput {
	this := FunctionInfoInput{}
	return &this
}

// GetFuncTypes returns the FuncTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FunctionInfoInput) GetFuncTypes() FunctionTypeInput {
	if o == nil || IsNil(o.FuncTypes.Get()) {
		var ret FunctionTypeInput
		return ret
	}
	return *o.FuncTypes.Get()
}

// GetFuncTypesOk returns a tuple with the FuncTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FunctionInfoInput) GetFuncTypesOk() (*FunctionTypeInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.FuncTypes.Get(), o.FuncTypes.IsSet()
}

// HasFuncTypes returns a boolean if a field has been set.
func (o *FunctionInfoInput) HasFuncTypes() bool {
	if o != nil && o.FuncTypes.IsSet() {
		return true
	}

	return false
}

// SetFuncTypes gets a reference to the given NullableFunctionTypeInput and assigns it to the FuncTypes field.
func (o *FunctionInfoInput) SetFuncTypes(v FunctionTypeInput) {
	o.FuncTypes.Set(&v)
}
// SetFuncTypesNil sets the value for FuncTypes to be an explicit nil
func (o *FunctionInfoInput) SetFuncTypesNil() {
	o.FuncTypes.Set(nil)
}

// UnsetFuncTypes ensures that no value is present for FuncTypes, not even an explicit nil
func (o *FunctionInfoInput) UnsetFuncTypes() {
	o.FuncTypes.Unset()
}

// GetFuncDeps returns the FuncDeps field value
func (o *FunctionInfoInput) GetFuncDeps() []FuncDepsInner {
	if o == nil {
		var ret []FuncDepsInner
		return ret
	}

	return o.FuncDeps
}

// GetFuncDepsOk returns a tuple with the FuncDeps field value
// and a boolean to check if the value has been set.
func (o *FunctionInfoInput) GetFuncDepsOk() ([]FuncDepsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.FuncDeps, true
}

// SetFuncDeps sets field value
func (o *FunctionInfoInput) SetFuncDeps(v []FuncDepsInner) {
	o.FuncDeps = v
}

func (o FunctionInfoInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionInfoInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FuncTypes.IsSet() {
		toSerialize["func_types"] = o.FuncTypes.Get()
	}
	toSerialize["func_deps"] = o.FuncDeps
	return toSerialize, nil
}

func (o *FunctionInfoInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"func_deps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionInfoInput := _FunctionInfoInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFunctionInfoInput)

	if err != nil {
		return err
	}

	*o = FunctionInfoInput(varFunctionInfoInput)

	return err
}

type NullableFunctionInfoInput struct {
	value *FunctionInfoInput
	isSet bool
}

func (v NullableFunctionInfoInput) Get() *FunctionInfoInput {
	return v.value
}

func (v *NullableFunctionInfoInput) Set(val *FunctionInfoInput) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionInfoInput) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionInfoInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionInfoInput(val *FunctionInfoInput) *NullableFunctionInfoInput {
	return &NullableFunctionInfoInput{value: val, isSet: true}
}

func (v NullableFunctionInfoInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionInfoInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


