/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// SandboxTimeout the model 'SandboxTimeout'
type SandboxTimeout int32

// List of SandboxTimeout
const (
	SANDBOXTIMEOUT__120 SandboxTimeout = 120
	SANDBOXTIMEOUT__180 SandboxTimeout = 180
	SANDBOXTIMEOUT__300 SandboxTimeout = 300
	SANDBOXTIMEOUT__600 SandboxTimeout = 600
	SANDBOXTIMEOUT__unknown_default_open_api SandboxTimeout = 11184809
)

// All allowed values of SandboxTimeout enum
var AllowedSandboxTimeoutEnumValues = []SandboxTimeout{
	120,
	180,
	300,
	600,
	11184809,
}

func (v *SandboxTimeout) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SandboxTimeout(value)
	for _, existing := range AllowedSandboxTimeoutEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SANDBOXTIMEOUT__unknown_default_open_api
	return nil
}

// NewSandboxTimeoutFromValue returns a pointer to a valid SandboxTimeout
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSandboxTimeoutFromValue(v int32) (*SandboxTimeout, error) {
	ev := SandboxTimeout(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SandboxTimeout: valid values are %v", v, AllowedSandboxTimeoutEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SandboxTimeout) IsValid() bool {
	for _, existing := range AllowedSandboxTimeoutEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SandboxTimeout value
func (v SandboxTimeout) Ptr() *SandboxTimeout {
	return &v
}

type NullableSandboxTimeout struct {
	value *SandboxTimeout
	isSet bool
}

func (v NullableSandboxTimeout) Get() *SandboxTimeout {
	return v.value
}

func (v *NullableSandboxTimeout) Set(val *SandboxTimeout) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxTimeout) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxTimeout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxTimeout(val *SandboxTimeout) *NullableSandboxTimeout {
	return &NullableSandboxTimeout{value: val, isSet: true}
}

func (v NullableSandboxTimeout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxTimeout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

