/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// ISA the model 'ISA'
type ISA string

// List of ISA
const (
	ISA_X86 ISA = "x86"
	ISA_X86_64 ISA = "x86_64"
	ISA_ARM ISA = "arm"
)

// All allowed values of ISA enum
var AllowedISAEnumValues = []ISA{
	"x86",
	"x86_64",
	"arm",
}

func (v *ISA) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ISA(value)
	for _, existing := range AllowedISAEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ISA", value)
}

// NewISAFromValue returns a pointer to a valid ISA
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewISAFromValue(v string) (*ISA, error) {
	ev := ISA(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ISA: valid values are %v", v, AllowedISAEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ISA) IsValid() bool {
	for _, existing := range AllowedISAEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ISA value
func (v ISA) Ptr() *ISA {
	return &v
}

type NullableISA struct {
	value *ISA
	isSet bool
}

func (v NullableISA) Get() *ISA {
	return v.value
}

func (v *NullableISA) Set(val *ISA) {
	v.value = val
	v.isSet = true
}

func (v NullableISA) IsSet() bool {
	return v.isSet
}

func (v *NullableISA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableISA(val *ISA) *NullableISA {
	return &NullableISA{value: val, isSet: true}
}

func (v NullableISA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableISA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

