/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportModel{}

// ImportModel struct for ImportModel
type ImportModel struct {
	NumberOfImports int32 `json:"number_of_imports"`
	Imports []map[string]map[string]int32 `json:"imports"`
}

type _ImportModel ImportModel

// NewImportModel instantiates a new ImportModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportModel(numberOfImports int32, imports []map[string]map[string]int32) *ImportModel {
	this := ImportModel{}
	this.NumberOfImports = numberOfImports
	this.Imports = imports
	return &this
}

// NewImportModelWithDefaults instantiates a new ImportModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportModelWithDefaults() *ImportModel {
	this := ImportModel{}
	return &this
}

// GetNumberOfImports returns the NumberOfImports field value
func (o *ImportModel) GetNumberOfImports() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumberOfImports
}

// GetNumberOfImportsOk returns a tuple with the NumberOfImports field value
// and a boolean to check if the value has been set.
func (o *ImportModel) GetNumberOfImportsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumberOfImports, true
}

// SetNumberOfImports sets field value
func (o *ImportModel) SetNumberOfImports(v int32) {
	o.NumberOfImports = v
}

// GetImports returns the Imports field value
func (o *ImportModel) GetImports() []map[string]map[string]int32 {
	if o == nil {
		var ret []map[string]map[string]int32
		return ret
	}

	return o.Imports
}

// GetImportsOk returns a tuple with the Imports field value
// and a boolean to check if the value has been set.
func (o *ImportModel) GetImportsOk() ([]map[string]map[string]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Imports, true
}

// SetImports sets field value
func (o *ImportModel) SetImports(v []map[string]map[string]int32) {
	o.Imports = v
}

func (o ImportModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["number_of_imports"] = o.NumberOfImports
	toSerialize["imports"] = o.Imports
	return toSerialize, nil
}

func (o *ImportModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"number_of_imports",
		"imports",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportModel := _ImportModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportModel)

	if err != nil {
		return err
	}

	*o = ImportModel(varImportModel)

	return err
}

type NullableImportModel struct {
	value *ImportModel
	isSet bool
}

func (v NullableImportModel) Get() *ImportModel {
	return v.value
}

func (v *NullableImportModel) Set(val *ImportModel) {
	v.value = val
	v.isSet = true
}

func (v NullableImportModel) IsSet() bool {
	return v.isSet
}

func (v *NullableImportModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportModel(val *ImportModel) *NullableImportModel {
	return &NullableImportModel{value: val, isSet: true}
}

func (v NullableImportModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


