/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the CollectionUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionUpdateRequest{}

// CollectionUpdateRequest struct for CollectionUpdateRequest
type CollectionUpdateRequest struct {
	CollectionName NullableString `json:"collection_name,omitempty"`
	Description NullableString `json:"description,omitempty"`
	CollectionScope NullableCollectionScope `json:"collection_scope,omitempty"`
}

// NewCollectionUpdateRequest instantiates a new CollectionUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionUpdateRequest() *CollectionUpdateRequest {
	this := CollectionUpdateRequest{}
	return &this
}

// NewCollectionUpdateRequestWithDefaults instantiates a new CollectionUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionUpdateRequestWithDefaults() *CollectionUpdateRequest {
	this := CollectionUpdateRequest{}
	return &this
}

// GetCollectionName returns the CollectionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CollectionUpdateRequest) GetCollectionName() string {
	if o == nil || IsNil(o.CollectionName.Get()) {
		var ret string
		return ret
	}
	return *o.CollectionName.Get()
}

// GetCollectionNameOk returns a tuple with the CollectionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CollectionUpdateRequest) GetCollectionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionName.Get(), o.CollectionName.IsSet()
}

// HasCollectionName returns a boolean if a field has been set.
func (o *CollectionUpdateRequest) HasCollectionName() bool {
	if o != nil && o.CollectionName.IsSet() {
		return true
	}

	return false
}

// SetCollectionName gets a reference to the given NullableString and assigns it to the CollectionName field.
func (o *CollectionUpdateRequest) SetCollectionName(v string) {
	o.CollectionName.Set(&v)
}
// SetCollectionNameNil sets the value for CollectionName to be an explicit nil
func (o *CollectionUpdateRequest) SetCollectionNameNil() {
	o.CollectionName.Set(nil)
}

// UnsetCollectionName ensures that no value is present for CollectionName, not even an explicit nil
func (o *CollectionUpdateRequest) UnsetCollectionName() {
	o.CollectionName.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CollectionUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CollectionUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CollectionUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CollectionUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CollectionUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CollectionUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetCollectionScope returns the CollectionScope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CollectionUpdateRequest) GetCollectionScope() CollectionScope {
	if o == nil || IsNil(o.CollectionScope.Get()) {
		var ret CollectionScope
		return ret
	}
	return *o.CollectionScope.Get()
}

// GetCollectionScopeOk returns a tuple with the CollectionScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CollectionUpdateRequest) GetCollectionScopeOk() (*CollectionScope, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionScope.Get(), o.CollectionScope.IsSet()
}

// HasCollectionScope returns a boolean if a field has been set.
func (o *CollectionUpdateRequest) HasCollectionScope() bool {
	if o != nil && o.CollectionScope.IsSet() {
		return true
	}

	return false
}

// SetCollectionScope gets a reference to the given NullableCollectionScope and assigns it to the CollectionScope field.
func (o *CollectionUpdateRequest) SetCollectionScope(v CollectionScope) {
	o.CollectionScope.Set(&v)
}
// SetCollectionScopeNil sets the value for CollectionScope to be an explicit nil
func (o *CollectionUpdateRequest) SetCollectionScopeNil() {
	o.CollectionScope.Set(nil)
}

// UnsetCollectionScope ensures that no value is present for CollectionScope, not even an explicit nil
func (o *CollectionUpdateRequest) UnsetCollectionScope() {
	o.CollectionScope.Unset()
}

func (o CollectionUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CollectionName.IsSet() {
		toSerialize["collection_name"] = o.CollectionName.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.CollectionScope.IsSet() {
		toSerialize["collection_scope"] = o.CollectionScope.Get()
	}
	return toSerialize, nil
}

type NullableCollectionUpdateRequest struct {
	value *CollectionUpdateRequest
	isSet bool
}

func (v NullableCollectionUpdateRequest) Get() *CollectionUpdateRequest {
	return v.value
}

func (v *NullableCollectionUpdateRequest) Set(val *CollectionUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionUpdateRequest(val *CollectionUpdateRequest) *NullableCollectionUpdateRequest {
	return &NullableCollectionUpdateRequest{value: val, isSet: true}
}

func (v NullableCollectionUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


