/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfile{}

// UserProfile struct for UserProfile
type UserProfile struct {
	DefaultTeamId *int64 `json:"default_team_id,omitempty"`
	FirstName string `json:"first_name"`
	HideExampleBinaries bool `json:"hide_example_binaries"`
	LastName string `json:"last_name"`
	TimeZone string `json:"time_zone"`
	Username string `json:"username"`
}

type _UserProfile UserProfile

// NewUserProfile instantiates a new UserProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfile(firstName string, hideExampleBinaries bool, lastName string, timeZone string, username string) *UserProfile {
	this := UserProfile{}
	this.FirstName = firstName
	this.HideExampleBinaries = hideExampleBinaries
	this.LastName = lastName
	this.TimeZone = timeZone
	this.Username = username
	return &this
}

// NewUserProfileWithDefaults instantiates a new UserProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileWithDefaults() *UserProfile {
	this := UserProfile{}
	return &this
}

// GetDefaultTeamId returns the DefaultTeamId field value if set, zero value otherwise.
func (o *UserProfile) GetDefaultTeamId() int64 {
	if o == nil || IsNil(o.DefaultTeamId) {
		var ret int64
		return ret
	}
	return *o.DefaultTeamId
}

// GetDefaultTeamIdOk returns a tuple with the DefaultTeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfile) GetDefaultTeamIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DefaultTeamId) {
		return nil, false
	}
	return o.DefaultTeamId, true
}

// HasDefaultTeamId returns a boolean if a field has been set.
func (o *UserProfile) HasDefaultTeamId() bool {
	if o != nil && !IsNil(o.DefaultTeamId) {
		return true
	}

	return false
}

// SetDefaultTeamId gets a reference to the given int64 and assigns it to the DefaultTeamId field.
func (o *UserProfile) SetDefaultTeamId(v int64) {
	o.DefaultTeamId = &v
}

// GetFirstName returns the FirstName field value
func (o *UserProfile) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *UserProfile) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *UserProfile) SetFirstName(v string) {
	o.FirstName = v
}

// GetHideExampleBinaries returns the HideExampleBinaries field value
func (o *UserProfile) GetHideExampleBinaries() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HideExampleBinaries
}

// GetHideExampleBinariesOk returns a tuple with the HideExampleBinaries field value
// and a boolean to check if the value has been set.
func (o *UserProfile) GetHideExampleBinariesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HideExampleBinaries, true
}

// SetHideExampleBinaries sets field value
func (o *UserProfile) SetHideExampleBinaries(v bool) {
	o.HideExampleBinaries = v
}

// GetLastName returns the LastName field value
func (o *UserProfile) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *UserProfile) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *UserProfile) SetLastName(v string) {
	o.LastName = v
}

// GetTimeZone returns the TimeZone field value
func (o *UserProfile) GetTimeZone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value
// and a boolean to check if the value has been set.
func (o *UserProfile) GetTimeZoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeZone, true
}

// SetTimeZone sets field value
func (o *UserProfile) SetTimeZone(v string) {
	o.TimeZone = v
}

// GetUsername returns the Username field value
func (o *UserProfile) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserProfile) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserProfile) SetUsername(v string) {
	o.Username = v
}

func (o UserProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultTeamId) {
		toSerialize["default_team_id"] = o.DefaultTeamId
	}
	toSerialize["first_name"] = o.FirstName
	toSerialize["hide_example_binaries"] = o.HideExampleBinaries
	toSerialize["last_name"] = o.LastName
	toSerialize["time_zone"] = o.TimeZone
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UserProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"hide_example_binaries",
		"last_name",
		"time_zone",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserProfile := _UserProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserProfile)

	if err != nil {
		return err
	}

	*o = UserProfile(varUserProfile)

	return err
}

type NullableUserProfile struct {
	value *UserProfile
	isSet bool
}

func (v NullableUserProfile) Get() *UserProfile {
	return v.value
}

func (v *NullableUserProfile) Set(val *UserProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfile(val *UserProfile) *NullableUserProfile {
	return &NullableUserProfile{value: val, isSet: true}
}

func (v NullableUserProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


