/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ELFSymbol type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ELFSymbol{}

// ELFSymbol struct for ELFSymbol
type ELFSymbol struct {
	Binding string `json:"binding"`
	Name string `json:"name"`
	SectionIndex int32 `json:"section_index"`
	Size int32 `json:"size"`
	Type string `json:"type"`
	Value int32 `json:"value"`
	Visibility string `json:"visibility"`
	AdditionalProperties map[string]interface{}
}

type _ELFSymbol ELFSymbol

// NewELFSymbol instantiates a new ELFSymbol object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewELFSymbol(binding string, name string, sectionIndex int32, size int32, type_ string, value int32, visibility string) *ELFSymbol {
	this := ELFSymbol{}
	this.Binding = binding
	this.Name = name
	this.SectionIndex = sectionIndex
	this.Size = size
	this.Type = type_
	this.Value = value
	this.Visibility = visibility
	return &this
}

// NewELFSymbolWithDefaults instantiates a new ELFSymbol object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewELFSymbolWithDefaults() *ELFSymbol {
	this := ELFSymbol{}
	return &this
}

// GetBinding returns the Binding field value
func (o *ELFSymbol) GetBinding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Binding
}

// GetBindingOk returns a tuple with the Binding field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetBindingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Binding, true
}

// SetBinding sets field value
func (o *ELFSymbol) SetBinding(v string) {
	o.Binding = v
}

// GetName returns the Name field value
func (o *ELFSymbol) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ELFSymbol) SetName(v string) {
	o.Name = v
}

// GetSectionIndex returns the SectionIndex field value
func (o *ELFSymbol) GetSectionIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SectionIndex
}

// GetSectionIndexOk returns a tuple with the SectionIndex field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetSectionIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SectionIndex, true
}

// SetSectionIndex sets field value
func (o *ELFSymbol) SetSectionIndex(v int32) {
	o.SectionIndex = v
}

// GetSize returns the Size field value
func (o *ELFSymbol) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ELFSymbol) SetSize(v int32) {
	o.Size = v
}

// GetType returns the Type field value
func (o *ELFSymbol) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ELFSymbol) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *ELFSymbol) GetValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ELFSymbol) SetValue(v int32) {
	o.Value = v
}

// GetVisibility returns the Visibility field value
func (o *ELFSymbol) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *ELFSymbol) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *ELFSymbol) SetVisibility(v string) {
	o.Visibility = v
}

func (o ELFSymbol) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ELFSymbol) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["binding"] = o.Binding
	toSerialize["name"] = o.Name
	toSerialize["section_index"] = o.SectionIndex
	toSerialize["size"] = o.Size
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	toSerialize["visibility"] = o.Visibility

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ELFSymbol) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"binding",
		"name",
		"section_index",
		"size",
		"type",
		"value",
		"visibility",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varELFSymbol := _ELFSymbol{}

	err = json.Unmarshal(data, &varELFSymbol)

	if err != nil {
		return err
	}

	*o = ELFSymbol(varELFSymbol)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "binding")
		delete(additionalProperties, "name")
		delete(additionalProperties, "section_index")
		delete(additionalProperties, "size")
		delete(additionalProperties, "type")
		delete(additionalProperties, "value")
		delete(additionalProperties, "visibility")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableELFSymbol struct {
	value *ELFSymbol
	isSet bool
}

func (v NullableELFSymbol) Get() *ELFSymbol {
	return v.value
}

func (v *NullableELFSymbol) Set(val *ELFSymbol) {
	v.value = val
	v.isSet = true
}

func (v NullableELFSymbol) IsSet() bool {
	return v.isSet
}

func (v *NullableELFSymbol) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableELFSymbol(val *ELFSymbol) *NullableELFSymbol {
	return &NullableELFSymbol{value: val, isSet: true}
}

func (v NullableELFSymbol) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableELFSymbol) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


