/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the TokenInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenInputBody{}

// TokenInputBody struct for TokenInputBody
type TokenInputBody struct {
	// API key to exchange for a JWT
	ApiKey *string `json:"api_key,omitempty"`
	// User email address (required with password)
	Email *string `json:"email,omitempty"`
	// User password (required with email or username)
	Password *string `json:"password,omitempty"`
	// Username (alternative to email, required with password)
	Username *string `json:"username,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TokenInputBody TokenInputBody

// NewTokenInputBody instantiates a new TokenInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenInputBody() *TokenInputBody {
	this := TokenInputBody{}
	return &this
}

// NewTokenInputBodyWithDefaults instantiates a new TokenInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenInputBodyWithDefaults() *TokenInputBody {
	this := TokenInputBody{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *TokenInputBody) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInputBody) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *TokenInputBody) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *TokenInputBody) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *TokenInputBody) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInputBody) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *TokenInputBody) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *TokenInputBody) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *TokenInputBody) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInputBody) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *TokenInputBody) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *TokenInputBody) SetPassword(v string) {
	o.Password = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *TokenInputBody) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenInputBody) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *TokenInputBody) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *TokenInputBody) SetUsername(v string) {
	o.Username = &v
}

func (o TokenInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKey) {
		toSerialize["api_key"] = o.ApiKey
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenInputBody) UnmarshalJSON(data []byte) (err error) {
	varTokenInputBody := _TokenInputBody{}

	err = json.Unmarshal(data, &varTokenInputBody)

	if err != nil {
		return err
	}

	*o = TokenInputBody(varTokenInputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "api_key")
		delete(additionalProperties, "email")
		delete(additionalProperties, "password")
		delete(additionalProperties, "username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenInputBody struct {
	value *TokenInputBody
	isSet bool
}

func (v NullableTokenInputBody) Get() *TokenInputBody {
	return v.value
}

func (v *NullableTokenInputBody) Set(val *TokenInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenInputBody(val *TokenInputBody) *NullableTokenInputBody {
	return &NullableTokenInputBody{value: val, isSet: true}
}

func (v NullableTokenInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


