/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCall{}

// ApiCall struct for ApiCall
type ApiCall struct {
	CalledFrom *string `json:"called_from,omitempty"`
	CalledFromRva *string `json:"called_from_rva,omitempty"`
	FromModule *string `json:"from_module,omitempty"`
	Method string `json:"method"`
}

type _ApiCall ApiCall

// NewApiCall instantiates a new ApiCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCall(method string) *ApiCall {
	this := ApiCall{}
	this.Method = method
	return &this
}

// NewApiCallWithDefaults instantiates a new ApiCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCallWithDefaults() *ApiCall {
	this := ApiCall{}
	return &this
}

// GetCalledFrom returns the CalledFrom field value if set, zero value otherwise.
func (o *ApiCall) GetCalledFrom() string {
	if o == nil || IsNil(o.CalledFrom) {
		var ret string
		return ret
	}
	return *o.CalledFrom
}

// GetCalledFromOk returns a tuple with the CalledFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCall) GetCalledFromOk() (*string, bool) {
	if o == nil || IsNil(o.CalledFrom) {
		return nil, false
	}
	return o.CalledFrom, true
}

// HasCalledFrom returns a boolean if a field has been set.
func (o *ApiCall) HasCalledFrom() bool {
	if o != nil && !IsNil(o.CalledFrom) {
		return true
	}

	return false
}

// SetCalledFrom gets a reference to the given string and assigns it to the CalledFrom field.
func (o *ApiCall) SetCalledFrom(v string) {
	o.CalledFrom = &v
}

// GetCalledFromRva returns the CalledFromRva field value if set, zero value otherwise.
func (o *ApiCall) GetCalledFromRva() string {
	if o == nil || IsNil(o.CalledFromRva) {
		var ret string
		return ret
	}
	return *o.CalledFromRva
}

// GetCalledFromRvaOk returns a tuple with the CalledFromRva field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCall) GetCalledFromRvaOk() (*string, bool) {
	if o == nil || IsNil(o.CalledFromRva) {
		return nil, false
	}
	return o.CalledFromRva, true
}

// HasCalledFromRva returns a boolean if a field has been set.
func (o *ApiCall) HasCalledFromRva() bool {
	if o != nil && !IsNil(o.CalledFromRva) {
		return true
	}

	return false
}

// SetCalledFromRva gets a reference to the given string and assigns it to the CalledFromRva field.
func (o *ApiCall) SetCalledFromRva(v string) {
	o.CalledFromRva = &v
}

// GetFromModule returns the FromModule field value if set, zero value otherwise.
func (o *ApiCall) GetFromModule() string {
	if o == nil || IsNil(o.FromModule) {
		var ret string
		return ret
	}
	return *o.FromModule
}

// GetFromModuleOk returns a tuple with the FromModule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCall) GetFromModuleOk() (*string, bool) {
	if o == nil || IsNil(o.FromModule) {
		return nil, false
	}
	return o.FromModule, true
}

// HasFromModule returns a boolean if a field has been set.
func (o *ApiCall) HasFromModule() bool {
	if o != nil && !IsNil(o.FromModule) {
		return true
	}

	return false
}

// SetFromModule gets a reference to the given string and assigns it to the FromModule field.
func (o *ApiCall) SetFromModule(v string) {
	o.FromModule = &v
}

// GetMethod returns the Method field value
func (o *ApiCall) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *ApiCall) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *ApiCall) SetMethod(v string) {
	o.Method = v
}

func (o ApiCall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CalledFrom) {
		toSerialize["called_from"] = o.CalledFrom
	}
	if !IsNil(o.CalledFromRva) {
		toSerialize["called_from_rva"] = o.CalledFromRva
	}
	if !IsNil(o.FromModule) {
		toSerialize["from_module"] = o.FromModule
	}
	toSerialize["method"] = o.Method
	return toSerialize, nil
}

func (o *ApiCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCall := _ApiCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiCall)

	if err != nil {
		return err
	}

	*o = ApiCall(varApiCall)

	return err
}

type NullableApiCall struct {
	value *ApiCall
	isSet bool
}

func (v NullableApiCall) Get() *ApiCall {
	return v.value
}

func (v *NullableApiCall) Set(val *ApiCall) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCall) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCall(val *ApiCall) *NullableApiCall {
	return &NullableApiCall{value: val, isSet: true}
}

func (v NullableApiCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


