/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FunctionStringsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionStringsResponse{}

// FunctionStringsResponse Response for listing all the strings of a function.
type FunctionStringsResponse struct {
	// The strings associated with this function
	Strings []FunctionString `json:"strings"`
	// The total number of strings associated with this function
	TotalStrings int32 `json:"total_strings"`
}

type _FunctionStringsResponse FunctionStringsResponse

// NewFunctionStringsResponse instantiates a new FunctionStringsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionStringsResponse(strings []FunctionString, totalStrings int32) *FunctionStringsResponse {
	this := FunctionStringsResponse{}
	this.Strings = strings
	this.TotalStrings = totalStrings
	return &this
}

// NewFunctionStringsResponseWithDefaults instantiates a new FunctionStringsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionStringsResponseWithDefaults() *FunctionStringsResponse {
	this := FunctionStringsResponse{}
	return &this
}

// GetStrings returns the Strings field value
func (o *FunctionStringsResponse) GetStrings() []FunctionString {
	if o == nil {
		var ret []FunctionString
		return ret
	}

	return o.Strings
}

// GetStringsOk returns a tuple with the Strings field value
// and a boolean to check if the value has been set.
func (o *FunctionStringsResponse) GetStringsOk() ([]FunctionString, bool) {
	if o == nil {
		return nil, false
	}
	return o.Strings, true
}

// SetStrings sets field value
func (o *FunctionStringsResponse) SetStrings(v []FunctionString) {
	o.Strings = v
}

// GetTotalStrings returns the TotalStrings field value
func (o *FunctionStringsResponse) GetTotalStrings() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalStrings
}

// GetTotalStringsOk returns a tuple with the TotalStrings field value
// and a boolean to check if the value has been set.
func (o *FunctionStringsResponse) GetTotalStringsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalStrings, true
}

// SetTotalStrings sets field value
func (o *FunctionStringsResponse) SetTotalStrings(v int32) {
	o.TotalStrings = v
}

func (o FunctionStringsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionStringsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strings"] = o.Strings
	toSerialize["total_strings"] = o.TotalStrings
	return toSerialize, nil
}

func (o *FunctionStringsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"strings",
		"total_strings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionStringsResponse := _FunctionStringsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFunctionStringsResponse)

	if err != nil {
		return err
	}

	*o = FunctionStringsResponse(varFunctionStringsResponse)

	return err
}

type NullableFunctionStringsResponse struct {
	value *FunctionStringsResponse
	isSet bool
}

func (v NullableFunctionStringsResponse) Get() *FunctionStringsResponse {
	return v.value
}

func (v *NullableFunctionStringsResponse) Set(val *FunctionStringsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionStringsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionStringsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionStringsResponse(val *FunctionStringsResponse) *NullableFunctionStringsResponse {
	return &NullableFunctionStringsResponse{value: val, isSet: true}
}

func (v NullableFunctionStringsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionStringsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


