/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ELFSecurity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ELFSecurity{}

// ELFSecurity struct for ELFSecurity
type ELFSecurity struct {
	Pie bool `json:"pie"`
	Stripped bool `json:"stripped"`
	Canary bool `json:"canary"`
	Nx bool `json:"nx"`
	Relo bool `json:"relo"`
}

type _ELFSecurity ELFSecurity

// NewELFSecurity instantiates a new ELFSecurity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewELFSecurity(pie bool, stripped bool, canary bool, nx bool, relo bool) *ELFSecurity {
	this := ELFSecurity{}
	this.Pie = pie
	this.Stripped = stripped
	this.Canary = canary
	this.Nx = nx
	this.Relo = relo
	return &this
}

// NewELFSecurityWithDefaults instantiates a new ELFSecurity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewELFSecurityWithDefaults() *ELFSecurity {
	this := ELFSecurity{}
	return &this
}

// GetPie returns the Pie field value
func (o *ELFSecurity) GetPie() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pie
}

// GetPieOk returns a tuple with the Pie field value
// and a boolean to check if the value has been set.
func (o *ELFSecurity) GetPieOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pie, true
}

// SetPie sets field value
func (o *ELFSecurity) SetPie(v bool) {
	o.Pie = v
}

// GetStripped returns the Stripped field value
func (o *ELFSecurity) GetStripped() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Stripped
}

// GetStrippedOk returns a tuple with the Stripped field value
// and a boolean to check if the value has been set.
func (o *ELFSecurity) GetStrippedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stripped, true
}

// SetStripped sets field value
func (o *ELFSecurity) SetStripped(v bool) {
	o.Stripped = v
}

// GetCanary returns the Canary field value
func (o *ELFSecurity) GetCanary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Canary
}

// GetCanaryOk returns a tuple with the Canary field value
// and a boolean to check if the value has been set.
func (o *ELFSecurity) GetCanaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Canary, true
}

// SetCanary sets field value
func (o *ELFSecurity) SetCanary(v bool) {
	o.Canary = v
}

// GetNx returns the Nx field value
func (o *ELFSecurity) GetNx() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Nx
}

// GetNxOk returns a tuple with the Nx field value
// and a boolean to check if the value has been set.
func (o *ELFSecurity) GetNxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nx, true
}

// SetNx sets field value
func (o *ELFSecurity) SetNx(v bool) {
	o.Nx = v
}

// GetRelo returns the Relo field value
func (o *ELFSecurity) GetRelo() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Relo
}

// GetReloOk returns a tuple with the Relo field value
// and a boolean to check if the value has been set.
func (o *ELFSecurity) GetReloOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relo, true
}

// SetRelo sets field value
func (o *ELFSecurity) SetRelo(v bool) {
	o.Relo = v
}

func (o ELFSecurity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ELFSecurity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pie"] = o.Pie
	toSerialize["stripped"] = o.Stripped
	toSerialize["canary"] = o.Canary
	toSerialize["nx"] = o.Nx
	toSerialize["relo"] = o.Relo
	return toSerialize, nil
}

func (o *ELFSecurity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pie",
		"stripped",
		"canary",
		"nx",
		"relo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varELFSecurity := _ELFSecurity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varELFSecurity)

	if err != nil {
		return err
	}

	*o = ELFSecurity(varELFSecurity)

	return err
}

type NullableELFSecurity struct {
	value *ELFSecurity
	isSet bool
}

func (v NullableELFSecurity) Get() *ELFSecurity {
	return v.value
}

func (v *NullableELFSecurity) Set(val *ELFSecurity) {
	v.value = val
	v.isSet = true
}

func (v NullableELFSecurity) IsSet() bool {
	return v.isSet
}

func (v *NullableELFSecurity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableELFSecurity(val *ELFSecurity) *NullableELFSecurity {
	return &NullableELFSecurity{value: val, isSet: true}
}

func (v NullableELFSecurity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableELFSecurity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


