/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BaseResponseListCalleesCallerFunctionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponseListCalleesCallerFunctionsResponse{}

// BaseResponseListCalleesCallerFunctionsResponse struct for BaseResponseListCalleesCallerFunctionsResponse
type BaseResponseListCalleesCallerFunctionsResponse struct {
	// Response status on whether the request succeeded
	Status *bool `json:"status,omitempty"`
	Data []CalleesCallerFunctionsResponse `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
	Errors []ErrorModel `json:"errors,omitempty"`
	// Metadata
	Meta *MetaModel `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BaseResponseListCalleesCallerFunctionsResponse BaseResponseListCalleesCallerFunctionsResponse

// NewBaseResponseListCalleesCallerFunctionsResponse instantiates a new BaseResponseListCalleesCallerFunctionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponseListCalleesCallerFunctionsResponse() *BaseResponseListCalleesCallerFunctionsResponse {
	this := BaseResponseListCalleesCallerFunctionsResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// NewBaseResponseListCalleesCallerFunctionsResponseWithDefaults instantiates a new BaseResponseListCalleesCallerFunctionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponseListCalleesCallerFunctionsResponseWithDefaults() *BaseResponseListCalleesCallerFunctionsResponse {
	this := BaseResponseListCalleesCallerFunctionsResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetData() []CalleesCallerFunctionsResponse {
	if o == nil {
		var ret []CalleesCallerFunctionsResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetDataOk() ([]CalleesCallerFunctionsResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CalleesCallerFunctionsResponse and assigns it to the Data field.
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetData(v []CalleesCallerFunctionsResponse) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *BaseResponseListCalleesCallerFunctionsResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetErrors returns the Errors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetErrors() []ErrorModel {
	if o == nil {
		var ret []ErrorModel
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetErrorsOk() ([]ErrorModel, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorModel and assigns it to the Errors field.
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetErrors(v []ErrorModel) {
	o.Errors = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetMeta() MetaModel {
	if o == nil || IsNil(o.Meta) {
		var ret MetaModel
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) GetMetaOk() (*MetaModel, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BaseResponseListCalleesCallerFunctionsResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaModel and assigns it to the Meta field.
func (o *BaseResponseListCalleesCallerFunctionsResponse) SetMeta(v MetaModel) {
	o.Meta = &v
}

func (o BaseResponseListCalleesCallerFunctionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponseListCalleesCallerFunctionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BaseResponseListCalleesCallerFunctionsResponse) UnmarshalJSON(data []byte) (err error) {
	varBaseResponseListCalleesCallerFunctionsResponse := _BaseResponseListCalleesCallerFunctionsResponse{}

	err = json.Unmarshal(data, &varBaseResponseListCalleesCallerFunctionsResponse)

	if err != nil {
		return err
	}

	*o = BaseResponseListCalleesCallerFunctionsResponse(varBaseResponseListCalleesCallerFunctionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		delete(additionalProperties, "message")
		delete(additionalProperties, "errors")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBaseResponseListCalleesCallerFunctionsResponse struct {
	value *BaseResponseListCalleesCallerFunctionsResponse
	isSet bool
}

func (v NullableBaseResponseListCalleesCallerFunctionsResponse) Get() *BaseResponseListCalleesCallerFunctionsResponse {
	return v.value
}

func (v *NullableBaseResponseListCalleesCallerFunctionsResponse) Set(val *BaseResponseListCalleesCallerFunctionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponseListCalleesCallerFunctionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponseListCalleesCallerFunctionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponseListCalleesCallerFunctionsResponse(val *BaseResponseListCalleesCallerFunctionsResponse) *NullableBaseResponseListCalleesCallerFunctionsResponse {
	return &NullableBaseResponseListCalleesCallerFunctionsResponse{value: val, isSet: true}
}

func (v NullableBaseResponseListCalleesCallerFunctionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponseListCalleesCallerFunctionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


