/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the NetworkOverviewDnsAnswer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkOverviewDnsAnswer{}

// NetworkOverviewDnsAnswer struct for NetworkOverviewDnsAnswer
type NetworkOverviewDnsAnswer struct {
	Data string `json:"data"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _NetworkOverviewDnsAnswer NetworkOverviewDnsAnswer

// NewNetworkOverviewDnsAnswer instantiates a new NetworkOverviewDnsAnswer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkOverviewDnsAnswer(data string, type_ string) *NetworkOverviewDnsAnswer {
	this := NetworkOverviewDnsAnswer{}
	this.Data = data
	this.Type = type_
	return &this
}

// NewNetworkOverviewDnsAnswerWithDefaults instantiates a new NetworkOverviewDnsAnswer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkOverviewDnsAnswerWithDefaults() *NetworkOverviewDnsAnswer {
	this := NetworkOverviewDnsAnswer{}
	return &this
}

// GetData returns the Data field value
func (o *NetworkOverviewDnsAnswer) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewDnsAnswer) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *NetworkOverviewDnsAnswer) SetData(v string) {
	o.Data = v
}

// GetType returns the Type field value
func (o *NetworkOverviewDnsAnswer) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewDnsAnswer) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NetworkOverviewDnsAnswer) SetType(v string) {
	o.Type = v
}

func (o NetworkOverviewDnsAnswer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkOverviewDnsAnswer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkOverviewDnsAnswer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkOverviewDnsAnswer := _NetworkOverviewDnsAnswer{}

	err = json.Unmarshal(data, &varNetworkOverviewDnsAnswer)

	if err != nil {
		return err
	}

	*o = NetworkOverviewDnsAnswer(varNetworkOverviewDnsAnswer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkOverviewDnsAnswer struct {
	value *NetworkOverviewDnsAnswer
	isSet bool
}

func (v NullableNetworkOverviewDnsAnswer) Get() *NetworkOverviewDnsAnswer {
	return v.value
}

func (v *NullableNetworkOverviewDnsAnswer) Set(val *NetworkOverviewDnsAnswer) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkOverviewDnsAnswer) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkOverviewDnsAnswer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkOverviewDnsAnswer(val *NetworkOverviewDnsAnswer) *NullableNetworkOverviewDnsAnswer {
	return &NullableNetworkOverviewDnsAnswer{value: val, isSet: true}
}

func (v NullableNetworkOverviewDnsAnswer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkOverviewDnsAnswer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


