/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BinaryAdditionalDetailsDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BinaryAdditionalDetailsDataResponse{}

// BinaryAdditionalDetailsDataResponse struct for BinaryAdditionalDetailsDataResponse
type BinaryAdditionalDetailsDataResponse struct {
	File FileMetadata `json:"file"`
	Pe NullablePEModel `json:"pe,omitempty"`
	Elf NullableELFModel `json:"elf,omitempty"`
}

type _BinaryAdditionalDetailsDataResponse BinaryAdditionalDetailsDataResponse

// NewBinaryAdditionalDetailsDataResponse instantiates a new BinaryAdditionalDetailsDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBinaryAdditionalDetailsDataResponse(file FileMetadata) *BinaryAdditionalDetailsDataResponse {
	this := BinaryAdditionalDetailsDataResponse{}
	this.File = file
	return &this
}

// NewBinaryAdditionalDetailsDataResponseWithDefaults instantiates a new BinaryAdditionalDetailsDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBinaryAdditionalDetailsDataResponseWithDefaults() *BinaryAdditionalDetailsDataResponse {
	this := BinaryAdditionalDetailsDataResponse{}
	return &this
}

// GetFile returns the File field value
func (o *BinaryAdditionalDetailsDataResponse) GetFile() FileMetadata {
	if o == nil {
		var ret FileMetadata
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *BinaryAdditionalDetailsDataResponse) GetFileOk() (*FileMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *BinaryAdditionalDetailsDataResponse) SetFile(v FileMetadata) {
	o.File = v
}

// GetPe returns the Pe field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BinaryAdditionalDetailsDataResponse) GetPe() PEModel {
	if o == nil || IsNil(o.Pe.Get()) {
		var ret PEModel
		return ret
	}
	return *o.Pe.Get()
}

// GetPeOk returns a tuple with the Pe field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BinaryAdditionalDetailsDataResponse) GetPeOk() (*PEModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pe.Get(), o.Pe.IsSet()
}

// HasPe returns a boolean if a field has been set.
func (o *BinaryAdditionalDetailsDataResponse) HasPe() bool {
	if o != nil && o.Pe.IsSet() {
		return true
	}

	return false
}

// SetPe gets a reference to the given NullablePEModel and assigns it to the Pe field.
func (o *BinaryAdditionalDetailsDataResponse) SetPe(v PEModel) {
	o.Pe.Set(&v)
}
// SetPeNil sets the value for Pe to be an explicit nil
func (o *BinaryAdditionalDetailsDataResponse) SetPeNil() {
	o.Pe.Set(nil)
}

// UnsetPe ensures that no value is present for Pe, not even an explicit nil
func (o *BinaryAdditionalDetailsDataResponse) UnsetPe() {
	o.Pe.Unset()
}

// GetElf returns the Elf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BinaryAdditionalDetailsDataResponse) GetElf() ELFModel {
	if o == nil || IsNil(o.Elf.Get()) {
		var ret ELFModel
		return ret
	}
	return *o.Elf.Get()
}

// GetElfOk returns a tuple with the Elf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BinaryAdditionalDetailsDataResponse) GetElfOk() (*ELFModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Elf.Get(), o.Elf.IsSet()
}

// HasElf returns a boolean if a field has been set.
func (o *BinaryAdditionalDetailsDataResponse) HasElf() bool {
	if o != nil && o.Elf.IsSet() {
		return true
	}

	return false
}

// SetElf gets a reference to the given NullableELFModel and assigns it to the Elf field.
func (o *BinaryAdditionalDetailsDataResponse) SetElf(v ELFModel) {
	o.Elf.Set(&v)
}
// SetElfNil sets the value for Elf to be an explicit nil
func (o *BinaryAdditionalDetailsDataResponse) SetElfNil() {
	o.Elf.Set(nil)
}

// UnsetElf ensures that no value is present for Elf, not even an explicit nil
func (o *BinaryAdditionalDetailsDataResponse) UnsetElf() {
	o.Elf.Unset()
}

func (o BinaryAdditionalDetailsDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BinaryAdditionalDetailsDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	if o.Pe.IsSet() {
		toSerialize["pe"] = o.Pe.Get()
	}
	if o.Elf.IsSet() {
		toSerialize["elf"] = o.Elf.Get()
	}
	return toSerialize, nil
}

func (o *BinaryAdditionalDetailsDataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBinaryAdditionalDetailsDataResponse := _BinaryAdditionalDetailsDataResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBinaryAdditionalDetailsDataResponse)

	if err != nil {
		return err
	}

	*o = BinaryAdditionalDetailsDataResponse(varBinaryAdditionalDetailsDataResponse)

	return err
}

type NullableBinaryAdditionalDetailsDataResponse struct {
	value *BinaryAdditionalDetailsDataResponse
	isSet bool
}

func (v NullableBinaryAdditionalDetailsDataResponse) Get() *BinaryAdditionalDetailsDataResponse {
	return v.value
}

func (v *NullableBinaryAdditionalDetailsDataResponse) Set(val *BinaryAdditionalDetailsDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBinaryAdditionalDetailsDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBinaryAdditionalDetailsDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBinaryAdditionalDetailsDataResponse(val *BinaryAdditionalDetailsDataResponse) *NullableBinaryAdditionalDetailsDataResponse {
	return &NullableBinaryAdditionalDetailsDataResponse{value: val, isSet: true}
}

func (v NullableBinaryAdditionalDetailsDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBinaryAdditionalDetailsDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


