/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CallEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallEdge{}

// CallEdge struct for CallEdge
type CallEdge struct {
	CalleeFunctionId *int64 `json:"callee_function_id,omitempty"`
	CalleeName *string `json:"callee_name,omitempty"`
	CalleeVaddr int64 `json:"callee_vaddr"`
	CallerFunctionId int64 `json:"caller_function_id"`
	CallerName *string `json:"caller_name,omitempty"`
	// Entry vaddr of the caller function (joined from function_t).
	CallerVaddr int64 `json:"caller_vaddr"`
	IsExternal bool `json:"is_external"`
	ThunkedVaddr *int64 `json:"thunked_vaddr,omitempty"`
}

type _CallEdge CallEdge

// NewCallEdge instantiates a new CallEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallEdge(calleeVaddr int64, callerFunctionId int64, callerVaddr int64, isExternal bool) *CallEdge {
	this := CallEdge{}
	this.CalleeVaddr = calleeVaddr
	this.CallerFunctionId = callerFunctionId
	this.CallerVaddr = callerVaddr
	this.IsExternal = isExternal
	return &this
}

// NewCallEdgeWithDefaults instantiates a new CallEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallEdgeWithDefaults() *CallEdge {
	this := CallEdge{}
	return &this
}

// GetCalleeFunctionId returns the CalleeFunctionId field value if set, zero value otherwise.
func (o *CallEdge) GetCalleeFunctionId() int64 {
	if o == nil || IsNil(o.CalleeFunctionId) {
		var ret int64
		return ret
	}
	return *o.CalleeFunctionId
}

// GetCalleeFunctionIdOk returns a tuple with the CalleeFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCalleeFunctionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CalleeFunctionId) {
		return nil, false
	}
	return o.CalleeFunctionId, true
}

// HasCalleeFunctionId returns a boolean if a field has been set.
func (o *CallEdge) HasCalleeFunctionId() bool {
	if o != nil && !IsNil(o.CalleeFunctionId) {
		return true
	}

	return false
}

// SetCalleeFunctionId gets a reference to the given int64 and assigns it to the CalleeFunctionId field.
func (o *CallEdge) SetCalleeFunctionId(v int64) {
	o.CalleeFunctionId = &v
}

// GetCalleeName returns the CalleeName field value if set, zero value otherwise.
func (o *CallEdge) GetCalleeName() string {
	if o == nil || IsNil(o.CalleeName) {
		var ret string
		return ret
	}
	return *o.CalleeName
}

// GetCalleeNameOk returns a tuple with the CalleeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCalleeNameOk() (*string, bool) {
	if o == nil || IsNil(o.CalleeName) {
		return nil, false
	}
	return o.CalleeName, true
}

// HasCalleeName returns a boolean if a field has been set.
func (o *CallEdge) HasCalleeName() bool {
	if o != nil && !IsNil(o.CalleeName) {
		return true
	}

	return false
}

// SetCalleeName gets a reference to the given string and assigns it to the CalleeName field.
func (o *CallEdge) SetCalleeName(v string) {
	o.CalleeName = &v
}

// GetCalleeVaddr returns the CalleeVaddr field value
func (o *CallEdge) GetCalleeVaddr() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CalleeVaddr
}

// GetCalleeVaddrOk returns a tuple with the CalleeVaddr field value
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCalleeVaddrOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CalleeVaddr, true
}

// SetCalleeVaddr sets field value
func (o *CallEdge) SetCalleeVaddr(v int64) {
	o.CalleeVaddr = v
}

// GetCallerFunctionId returns the CallerFunctionId field value
func (o *CallEdge) GetCallerFunctionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CallerFunctionId
}

// GetCallerFunctionIdOk returns a tuple with the CallerFunctionId field value
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCallerFunctionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallerFunctionId, true
}

// SetCallerFunctionId sets field value
func (o *CallEdge) SetCallerFunctionId(v int64) {
	o.CallerFunctionId = v
}

// GetCallerName returns the CallerName field value if set, zero value otherwise.
func (o *CallEdge) GetCallerName() string {
	if o == nil || IsNil(o.CallerName) {
		var ret string
		return ret
	}
	return *o.CallerName
}

// GetCallerNameOk returns a tuple with the CallerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCallerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CallerName) {
		return nil, false
	}
	return o.CallerName, true
}

// HasCallerName returns a boolean if a field has been set.
func (o *CallEdge) HasCallerName() bool {
	if o != nil && !IsNil(o.CallerName) {
		return true
	}

	return false
}

// SetCallerName gets a reference to the given string and assigns it to the CallerName field.
func (o *CallEdge) SetCallerName(v string) {
	o.CallerName = &v
}

// GetCallerVaddr returns the CallerVaddr field value
func (o *CallEdge) GetCallerVaddr() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CallerVaddr
}

// GetCallerVaddrOk returns a tuple with the CallerVaddr field value
// and a boolean to check if the value has been set.
func (o *CallEdge) GetCallerVaddrOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallerVaddr, true
}

// SetCallerVaddr sets field value
func (o *CallEdge) SetCallerVaddr(v int64) {
	o.CallerVaddr = v
}

// GetIsExternal returns the IsExternal field value
func (o *CallEdge) GetIsExternal() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsExternal
}

// GetIsExternalOk returns a tuple with the IsExternal field value
// and a boolean to check if the value has been set.
func (o *CallEdge) GetIsExternalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsExternal, true
}

// SetIsExternal sets field value
func (o *CallEdge) SetIsExternal(v bool) {
	o.IsExternal = v
}

// GetThunkedVaddr returns the ThunkedVaddr field value if set, zero value otherwise.
func (o *CallEdge) GetThunkedVaddr() int64 {
	if o == nil || IsNil(o.ThunkedVaddr) {
		var ret int64
		return ret
	}
	return *o.ThunkedVaddr
}

// GetThunkedVaddrOk returns a tuple with the ThunkedVaddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallEdge) GetThunkedVaddrOk() (*int64, bool) {
	if o == nil || IsNil(o.ThunkedVaddr) {
		return nil, false
	}
	return o.ThunkedVaddr, true
}

// HasThunkedVaddr returns a boolean if a field has been set.
func (o *CallEdge) HasThunkedVaddr() bool {
	if o != nil && !IsNil(o.ThunkedVaddr) {
		return true
	}

	return false
}

// SetThunkedVaddr gets a reference to the given int64 and assigns it to the ThunkedVaddr field.
func (o *CallEdge) SetThunkedVaddr(v int64) {
	o.ThunkedVaddr = &v
}

func (o CallEdge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CalleeFunctionId) {
		toSerialize["callee_function_id"] = o.CalleeFunctionId
	}
	if !IsNil(o.CalleeName) {
		toSerialize["callee_name"] = o.CalleeName
	}
	toSerialize["callee_vaddr"] = o.CalleeVaddr
	toSerialize["caller_function_id"] = o.CallerFunctionId
	if !IsNil(o.CallerName) {
		toSerialize["caller_name"] = o.CallerName
	}
	toSerialize["caller_vaddr"] = o.CallerVaddr
	toSerialize["is_external"] = o.IsExternal
	if !IsNil(o.ThunkedVaddr) {
		toSerialize["thunked_vaddr"] = o.ThunkedVaddr
	}
	return toSerialize, nil
}

func (o *CallEdge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"callee_vaddr",
		"caller_function_id",
		"caller_vaddr",
		"is_external",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCallEdge := _CallEdge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCallEdge)

	if err != nil {
		return err
	}

	*o = CallEdge(varCallEdge)

	return err
}

type NullableCallEdge struct {
	value *CallEdge
	isSet bool
}

func (v NullableCallEdge) Get() *CallEdge {
	return v.value
}

func (v *NullableCallEdge) Set(val *CallEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableCallEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableCallEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallEdge(val *CallEdge) *NullableCallEdge {
	return &NullableCallEdge{value: val, isSet: true}
}

func (v NullableCallEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


