/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SegmentInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SegmentInfo{}

// SegmentInfo Represents the information about a segment.  Attributes:     name: The name of the segment.     r: Determines if the segment has read permission.     w: Determines if the segment has write permission.     x: Determines if the segment has execute permission.     start: The start address of the segment.     end: The end address of the segment.
type SegmentInfo struct {
	End *int32 `json:"end,omitempty"`
	Name *string `json:"name,omitempty"`
	R NullableBool `json:"r,omitempty"`
	Start *int32 `json:"start,omitempty"`
	W NullableBool `json:"w,omitempty"`
	X NullableBool `json:"x,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SegmentInfo SegmentInfo

// NewSegmentInfo instantiates a new SegmentInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSegmentInfo() *SegmentInfo {
	this := SegmentInfo{}
	var end int32 = 0
	this.End = &end
	var name string = ""
	this.Name = &name
	var start int32 = 0
	this.Start = &start
	return &this
}

// NewSegmentInfoWithDefaults instantiates a new SegmentInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSegmentInfoWithDefaults() *SegmentInfo {
	this := SegmentInfo{}
	var end int32 = 0
	this.End = &end
	var name string = ""
	this.Name = &name
	var start int32 = 0
	this.Start = &start
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *SegmentInfo) GetEnd() int32 {
	if o == nil || IsNil(o.End) {
		var ret int32
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentInfo) GetEndOk() (*int32, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *SegmentInfo) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int32 and assigns it to the End field.
func (o *SegmentInfo) SetEnd(v int32) {
	o.End = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SegmentInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SegmentInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SegmentInfo) SetName(v string) {
	o.Name = &v
}

// GetR returns the R field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SegmentInfo) GetR() bool {
	if o == nil || IsNil(o.R.Get()) {
		var ret bool
		return ret
	}
	return *o.R.Get()
}

// GetROk returns a tuple with the R field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentInfo) GetROk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.R.Get(), o.R.IsSet()
}

// HasR returns a boolean if a field has been set.
func (o *SegmentInfo) HasR() bool {
	if o != nil && o.R.IsSet() {
		return true
	}

	return false
}

// SetR gets a reference to the given NullableBool and assigns it to the R field.
func (o *SegmentInfo) SetR(v bool) {
	o.R.Set(&v)
}
// SetRNil sets the value for R to be an explicit nil
func (o *SegmentInfo) SetRNil() {
	o.R.Set(nil)
}

// UnsetR ensures that no value is present for R, not even an explicit nil
func (o *SegmentInfo) UnsetR() {
	o.R.Unset()
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *SegmentInfo) GetStart() int32 {
	if o == nil || IsNil(o.Start) {
		var ret int32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentInfo) GetStartOk() (*int32, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *SegmentInfo) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given int32 and assigns it to the Start field.
func (o *SegmentInfo) SetStart(v int32) {
	o.Start = &v
}

// GetW returns the W field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SegmentInfo) GetW() bool {
	if o == nil || IsNil(o.W.Get()) {
		var ret bool
		return ret
	}
	return *o.W.Get()
}

// GetWOk returns a tuple with the W field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentInfo) GetWOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.W.Get(), o.W.IsSet()
}

// HasW returns a boolean if a field has been set.
func (o *SegmentInfo) HasW() bool {
	if o != nil && o.W.IsSet() {
		return true
	}

	return false
}

// SetW gets a reference to the given NullableBool and assigns it to the W field.
func (o *SegmentInfo) SetW(v bool) {
	o.W.Set(&v)
}
// SetWNil sets the value for W to be an explicit nil
func (o *SegmentInfo) SetWNil() {
	o.W.Set(nil)
}

// UnsetW ensures that no value is present for W, not even an explicit nil
func (o *SegmentInfo) UnsetW() {
	o.W.Unset()
}

// GetX returns the X field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SegmentInfo) GetX() bool {
	if o == nil || IsNil(o.X.Get()) {
		var ret bool
		return ret
	}
	return *o.X.Get()
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentInfo) GetXOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.X.Get(), o.X.IsSet()
}

// HasX returns a boolean if a field has been set.
func (o *SegmentInfo) HasX() bool {
	if o != nil && o.X.IsSet() {
		return true
	}

	return false
}

// SetX gets a reference to the given NullableBool and assigns it to the X field.
func (o *SegmentInfo) SetX(v bool) {
	o.X.Set(&v)
}
// SetXNil sets the value for X to be an explicit nil
func (o *SegmentInfo) SetXNil() {
	o.X.Set(nil)
}

// UnsetX ensures that no value is present for X, not even an explicit nil
func (o *SegmentInfo) UnsetX() {
	o.X.Unset()
}

func (o SegmentInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SegmentInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.R.IsSet() {
		toSerialize["r"] = o.R.Get()
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if o.W.IsSet() {
		toSerialize["w"] = o.W.Get()
	}
	if o.X.IsSet() {
		toSerialize["x"] = o.X.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SegmentInfo) UnmarshalJSON(data []byte) (err error) {
	varSegmentInfo := _SegmentInfo{}

	err = json.Unmarshal(data, &varSegmentInfo)

	if err != nil {
		return err
	}

	*o = SegmentInfo(varSegmentInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "end")
		delete(additionalProperties, "name")
		delete(additionalProperties, "r")
		delete(additionalProperties, "start")
		delete(additionalProperties, "w")
		delete(additionalProperties, "x")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSegmentInfo struct {
	value *SegmentInfo
	isSet bool
}

func (v NullableSegmentInfo) Get() *SegmentInfo {
	return v.value
}

func (v *NullableSegmentInfo) Set(val *SegmentInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSegmentInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSegmentInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegmentInfo(val *SegmentInfo) *NullableSegmentInfo {
	return &NullableSegmentInfo{value: val, isSet: true}
}

func (v NullableSegmentInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegmentInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


