/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SuggestedTypeView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuggestedTypeView{}

// SuggestedTypeView struct for SuggestedTypeView
type SuggestedTypeView struct {
	// Existing data type the members were accessed through. Null when nothing resolved to a row; never minted for a suggestion.
	DataTypeId *int64 `json:"data_type_id,omitempty"`
	// Gaps between consecutive placed members, in offset order.
	Holes []SuggestedHole `json:"holes"`
	// Highest byte_offset+byte_size across the members. A lower bound on the type's size, not its size.
	ImpliedSize *int64 `json:"implied_size,omitempty"`
	// Identity of the suggestion: index:<data_type_id> where the access named a row, else token:<type_token>.
	Key string `json:"key"`
	// Members in offset order, unplaced ones last.
	Members []SuggestedMemberView `json:"members"`
	// Name the type renders as: a database or frozen name where one exists, else the suggested one.
	Name string `json:"name"`
	// Placeholder the type renders as, when it appears in this function's source.
	TypeToken *string `json:"type_token,omitempty"`
	// Set only for a type with no observed members, where the suggestion is a name and a scalar type rather than a layout.
	UnderlyingType *string `json:"underlying_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SuggestedTypeView SuggestedTypeView

// NewSuggestedTypeView instantiates a new SuggestedTypeView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuggestedTypeView(holes []SuggestedHole, key string, members []SuggestedMemberView, name string) *SuggestedTypeView {
	this := SuggestedTypeView{}
	this.Holes = holes
	this.Key = key
	this.Members = members
	this.Name = name
	return &this
}

// NewSuggestedTypeViewWithDefaults instantiates a new SuggestedTypeView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuggestedTypeViewWithDefaults() *SuggestedTypeView {
	this := SuggestedTypeView{}
	return &this
}

// GetDataTypeId returns the DataTypeId field value if set, zero value otherwise.
func (o *SuggestedTypeView) GetDataTypeId() int64 {
	if o == nil || IsNil(o.DataTypeId) {
		var ret int64
		return ret
	}
	return *o.DataTypeId
}

// GetDataTypeIdOk returns a tuple with the DataTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetDataTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DataTypeId) {
		return nil, false
	}
	return o.DataTypeId, true
}

// HasDataTypeId returns a boolean if a field has been set.
func (o *SuggestedTypeView) HasDataTypeId() bool {
	if o != nil && !IsNil(o.DataTypeId) {
		return true
	}

	return false
}

// SetDataTypeId gets a reference to the given int64 and assigns it to the DataTypeId field.
func (o *SuggestedTypeView) SetDataTypeId(v int64) {
	o.DataTypeId = &v
}

// GetHoles returns the Holes field value
// If the value is explicit nil, the zero value for []SuggestedHole will be returned
func (o *SuggestedTypeView) GetHoles() []SuggestedHole {
	if o == nil {
		var ret []SuggestedHole
		return ret
	}

	return o.Holes
}

// GetHolesOk returns a tuple with the Holes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuggestedTypeView) GetHolesOk() ([]SuggestedHole, bool) {
	if o == nil || IsNil(o.Holes) {
		return nil, false
	}
	return o.Holes, true
}

// SetHoles sets field value
func (o *SuggestedTypeView) SetHoles(v []SuggestedHole) {
	o.Holes = v
}

// GetImpliedSize returns the ImpliedSize field value if set, zero value otherwise.
func (o *SuggestedTypeView) GetImpliedSize() int64 {
	if o == nil || IsNil(o.ImpliedSize) {
		var ret int64
		return ret
	}
	return *o.ImpliedSize
}

// GetImpliedSizeOk returns a tuple with the ImpliedSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetImpliedSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.ImpliedSize) {
		return nil, false
	}
	return o.ImpliedSize, true
}

// HasImpliedSize returns a boolean if a field has been set.
func (o *SuggestedTypeView) HasImpliedSize() bool {
	if o != nil && !IsNil(o.ImpliedSize) {
		return true
	}

	return false
}

// SetImpliedSize gets a reference to the given int64 and assigns it to the ImpliedSize field.
func (o *SuggestedTypeView) SetImpliedSize(v int64) {
	o.ImpliedSize = &v
}

// GetKey returns the Key field value
func (o *SuggestedTypeView) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SuggestedTypeView) SetKey(v string) {
	o.Key = v
}

// GetMembers returns the Members field value
// If the value is explicit nil, the zero value for []SuggestedMemberView will be returned
func (o *SuggestedTypeView) GetMembers() []SuggestedMemberView {
	if o == nil {
		var ret []SuggestedMemberView
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SuggestedTypeView) GetMembersOk() ([]SuggestedMemberView, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *SuggestedTypeView) SetMembers(v []SuggestedMemberView) {
	o.Members = v
}

// GetName returns the Name field value
func (o *SuggestedTypeView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SuggestedTypeView) SetName(v string) {
	o.Name = v
}

// GetTypeToken returns the TypeToken field value if set, zero value otherwise.
func (o *SuggestedTypeView) GetTypeToken() string {
	if o == nil || IsNil(o.TypeToken) {
		var ret string
		return ret
	}
	return *o.TypeToken
}

// GetTypeTokenOk returns a tuple with the TypeToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetTypeTokenOk() (*string, bool) {
	if o == nil || IsNil(o.TypeToken) {
		return nil, false
	}
	return o.TypeToken, true
}

// HasTypeToken returns a boolean if a field has been set.
func (o *SuggestedTypeView) HasTypeToken() bool {
	if o != nil && !IsNil(o.TypeToken) {
		return true
	}

	return false
}

// SetTypeToken gets a reference to the given string and assigns it to the TypeToken field.
func (o *SuggestedTypeView) SetTypeToken(v string) {
	o.TypeToken = &v
}

// GetUnderlyingType returns the UnderlyingType field value if set, zero value otherwise.
func (o *SuggestedTypeView) GetUnderlyingType() string {
	if o == nil || IsNil(o.UnderlyingType) {
		var ret string
		return ret
	}
	return *o.UnderlyingType
}

// GetUnderlyingTypeOk returns a tuple with the UnderlyingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuggestedTypeView) GetUnderlyingTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UnderlyingType) {
		return nil, false
	}
	return o.UnderlyingType, true
}

// HasUnderlyingType returns a boolean if a field has been set.
func (o *SuggestedTypeView) HasUnderlyingType() bool {
	if o != nil && !IsNil(o.UnderlyingType) {
		return true
	}

	return false
}

// SetUnderlyingType gets a reference to the given string and assigns it to the UnderlyingType field.
func (o *SuggestedTypeView) SetUnderlyingType(v string) {
	o.UnderlyingType = &v
}

func (o SuggestedTypeView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuggestedTypeView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataTypeId) {
		toSerialize["data_type_id"] = o.DataTypeId
	}
	if o.Holes != nil {
		toSerialize["holes"] = o.Holes
	}
	if !IsNil(o.ImpliedSize) {
		toSerialize["implied_size"] = o.ImpliedSize
	}
	toSerialize["key"] = o.Key
	if o.Members != nil {
		toSerialize["members"] = o.Members
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.TypeToken) {
		toSerialize["type_token"] = o.TypeToken
	}
	if !IsNil(o.UnderlyingType) {
		toSerialize["underlying_type"] = o.UnderlyingType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SuggestedTypeView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"holes",
		"key",
		"members",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSuggestedTypeView := _SuggestedTypeView{}

	err = json.Unmarshal(data, &varSuggestedTypeView)

	if err != nil {
		return err
	}

	*o = SuggestedTypeView(varSuggestedTypeView)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data_type_id")
		delete(additionalProperties, "holes")
		delete(additionalProperties, "implied_size")
		delete(additionalProperties, "key")
		delete(additionalProperties, "members")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type_token")
		delete(additionalProperties, "underlying_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSuggestedTypeView struct {
	value *SuggestedTypeView
	isSet bool
}

func (v NullableSuggestedTypeView) Get() *SuggestedTypeView {
	return v.value
}

func (v *NullableSuggestedTypeView) Set(val *SuggestedTypeView) {
	v.value = val
	v.isSet = true
}

func (v NullableSuggestedTypeView) IsSet() bool {
	return v.isSet
}

func (v *NullableSuggestedTypeView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuggestedTypeView(val *SuggestedTypeView) *NullableSuggestedTypeView {
	return &NullableSuggestedTypeView{value: val, isSet: true}
}

func (v NullableSuggestedTypeView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuggestedTypeView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


