/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the IOC type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IOC{}

// IOC struct for IOC
type IOC struct {
	// Type of the IOC
	Type string `json:"type"`
	// Value of the IOC
	Value string `json:"value"`
	// Description of the IOC
	Description string `json:"description"`
	Source NullableString `json:"source,omitempty"`
	FunctionId NullableInt32 `json:"function_id,omitempty"`
	FunctionName NullableString `json:"function_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IOC IOC

// NewIOC instantiates a new IOC object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIOC(type_ string, value string, description string) *IOC {
	this := IOC{}
	this.Type = type_
	this.Value = value
	this.Description = description
	return &this
}

// NewIOCWithDefaults instantiates a new IOC object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIOCWithDefaults() *IOC {
	this := IOC{}
	return &this
}

// GetType returns the Type field value
func (o *IOC) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IOC) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IOC) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *IOC) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *IOC) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *IOC) SetValue(v string) {
	o.Value = v
}

// GetDescription returns the Description field value
func (o *IOC) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *IOC) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *IOC) SetDescription(v string) {
	o.Description = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IOC) GetSource() string {
	if o == nil || IsNil(o.Source.Get()) {
		var ret string
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IOC) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *IOC) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableString and assigns it to the Source field.
func (o *IOC) SetSource(v string) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *IOC) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *IOC) UnsetSource() {
	o.Source.Unset()
}

// GetFunctionId returns the FunctionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IOC) GetFunctionId() int32 {
	if o == nil || IsNil(o.FunctionId.Get()) {
		var ret int32
		return ret
	}
	return *o.FunctionId.Get()
}

// GetFunctionIdOk returns a tuple with the FunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IOC) GetFunctionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FunctionId.Get(), o.FunctionId.IsSet()
}

// HasFunctionId returns a boolean if a field has been set.
func (o *IOC) HasFunctionId() bool {
	if o != nil && o.FunctionId.IsSet() {
		return true
	}

	return false
}

// SetFunctionId gets a reference to the given NullableInt32 and assigns it to the FunctionId field.
func (o *IOC) SetFunctionId(v int32) {
	o.FunctionId.Set(&v)
}
// SetFunctionIdNil sets the value for FunctionId to be an explicit nil
func (o *IOC) SetFunctionIdNil() {
	o.FunctionId.Set(nil)
}

// UnsetFunctionId ensures that no value is present for FunctionId, not even an explicit nil
func (o *IOC) UnsetFunctionId() {
	o.FunctionId.Unset()
}

// GetFunctionName returns the FunctionName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IOC) GetFunctionName() string {
	if o == nil || IsNil(o.FunctionName.Get()) {
		var ret string
		return ret
	}
	return *o.FunctionName.Get()
}

// GetFunctionNameOk returns a tuple with the FunctionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IOC) GetFunctionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FunctionName.Get(), o.FunctionName.IsSet()
}

// HasFunctionName returns a boolean if a field has been set.
func (o *IOC) HasFunctionName() bool {
	if o != nil && o.FunctionName.IsSet() {
		return true
	}

	return false
}

// SetFunctionName gets a reference to the given NullableString and assigns it to the FunctionName field.
func (o *IOC) SetFunctionName(v string) {
	o.FunctionName.Set(&v)
}
// SetFunctionNameNil sets the value for FunctionName to be an explicit nil
func (o *IOC) SetFunctionNameNil() {
	o.FunctionName.Set(nil)
}

// UnsetFunctionName ensures that no value is present for FunctionName, not even an explicit nil
func (o *IOC) UnsetFunctionName() {
	o.FunctionName.Unset()
}

func (o IOC) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IOC) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	toSerialize["description"] = o.Description
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	if o.FunctionId.IsSet() {
		toSerialize["function_id"] = o.FunctionId.Get()
	}
	if o.FunctionName.IsSet() {
		toSerialize["function_name"] = o.FunctionName.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IOC) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIOC := _IOC{}

	err = json.Unmarshal(data, &varIOC)

	if err != nil {
		return err
	}

	*o = IOC(varIOC)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "value")
		delete(additionalProperties, "description")
		delete(additionalProperties, "source")
		delete(additionalProperties, "function_id")
		delete(additionalProperties, "function_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIOC struct {
	value *IOC
	isSet bool
}

func (v NullableIOC) Get() *IOC {
	return v.value
}

func (v *NullableIOC) Set(val *IOC) {
	v.value = val
	v.isSet = true
}

func (v NullableIOC) IsSet() bool {
	return v.isSet
}

func (v *NullableIOC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIOC(val *IOC) *NullableIOC {
	return &NullableIOC{value: val, isSet: true}
}

func (v NullableIOC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIOC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


