/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TypesSuggestedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesSuggestedEvent{}

// TypesSuggestedEvent struct for TypesSuggestedEvent
type TypesSuggestedEvent struct {
	Attempt int32 `json:"attempt"`
	Members int32 `json:"members"`
	Seq int32 `json:"seq"`
	Type string `json:"type"`
	Types int32 `json:"types"`
}

type _TypesSuggestedEvent TypesSuggestedEvent

// NewTypesSuggestedEvent instantiates a new TypesSuggestedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesSuggestedEvent(attempt int32, members int32, seq int32, type_ string, types int32) *TypesSuggestedEvent {
	this := TypesSuggestedEvent{}
	this.Attempt = attempt
	this.Members = members
	this.Seq = seq
	this.Type = type_
	this.Types = types
	return &this
}

// NewTypesSuggestedEventWithDefaults instantiates a new TypesSuggestedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesSuggestedEventWithDefaults() *TypesSuggestedEvent {
	this := TypesSuggestedEvent{}
	return &this
}

// GetAttempt returns the Attempt field value
func (o *TypesSuggestedEvent) GetAttempt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value
// and a boolean to check if the value has been set.
func (o *TypesSuggestedEvent) GetAttemptOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempt, true
}

// SetAttempt sets field value
func (o *TypesSuggestedEvent) SetAttempt(v int32) {
	o.Attempt = v
}

// GetMembers returns the Members field value
func (o *TypesSuggestedEvent) GetMembers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *TypesSuggestedEvent) GetMembersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Members, true
}

// SetMembers sets field value
func (o *TypesSuggestedEvent) SetMembers(v int32) {
	o.Members = v
}

// GetSeq returns the Seq field value
func (o *TypesSuggestedEvent) GetSeq() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *TypesSuggestedEvent) GetSeqOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *TypesSuggestedEvent) SetSeq(v int32) {
	o.Seq = v
}

// GetType returns the Type field value
func (o *TypesSuggestedEvent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TypesSuggestedEvent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TypesSuggestedEvent) SetType(v string) {
	o.Type = v
}

// GetTypes returns the Types field value
func (o *TypesSuggestedEvent) GetTypes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *TypesSuggestedEvent) GetTypesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Types, true
}

// SetTypes sets field value
func (o *TypesSuggestedEvent) SetTypes(v int32) {
	o.Types = v
}

func (o TypesSuggestedEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesSuggestedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attempt"] = o.Attempt
	toSerialize["members"] = o.Members
	toSerialize["seq"] = o.Seq
	toSerialize["type"] = o.Type
	toSerialize["types"] = o.Types
	return toSerialize, nil
}

func (o *TypesSuggestedEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attempt",
		"members",
		"seq",
		"type",
		"types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypesSuggestedEvent := _TypesSuggestedEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypesSuggestedEvent)

	if err != nil {
		return err
	}

	*o = TypesSuggestedEvent(varTypesSuggestedEvent)

	return err
}

type NullableTypesSuggestedEvent struct {
	value *TypesSuggestedEvent
	isSet bool
}

func (v NullableTypesSuggestedEvent) Get() *TypesSuggestedEvent {
	return v.value
}

func (v *NullableTypesSuggestedEvent) Set(val *TypesSuggestedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesSuggestedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesSuggestedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesSuggestedEvent(val *TypesSuggestedEvent) *NullableTypesSuggestedEvent {
	return &NullableTypesSuggestedEvent{value: val, isSet: true}
}

func (v NullableTypesSuggestedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesSuggestedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


