/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the FilesystemVerification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesystemVerification{}

// FilesystemVerification struct for FilesystemVerification
type FilesystemVerification struct {
	// LLM's confidence in the verdict. Absent when verified is null.
	Confidence *string `json:"confidence,omitempty"`
	// LLM's explanation for the verdict, or the reason verification could not be completed
	Reasoning string `json:"reasoning"`
	// Whether an LLM confirmed the finding against its decompilation; null if verification could not be completed, in which case the finding is kept unverified rather than dropped
	Verified NullableBool `json:"verified"`
	AdditionalProperties map[string]interface{}
}

type _FilesystemVerification FilesystemVerification

// NewFilesystemVerification instantiates a new FilesystemVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesystemVerification(reasoning string, verified NullableBool) *FilesystemVerification {
	this := FilesystemVerification{}
	this.Reasoning = reasoning
	this.Verified = verified
	return &this
}

// NewFilesystemVerificationWithDefaults instantiates a new FilesystemVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesystemVerificationWithDefaults() *FilesystemVerification {
	this := FilesystemVerification{}
	return &this
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *FilesystemVerification) GetConfidence() string {
	if o == nil || IsNil(o.Confidence) {
		var ret string
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesystemVerification) GetConfidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *FilesystemVerification) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given string and assigns it to the Confidence field.
func (o *FilesystemVerification) SetConfidence(v string) {
	o.Confidence = &v
}

// GetReasoning returns the Reasoning field value
func (o *FilesystemVerification) GetReasoning() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reasoning
}

// GetReasoningOk returns a tuple with the Reasoning field value
// and a boolean to check if the value has been set.
func (o *FilesystemVerification) GetReasoningOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reasoning, true
}

// SetReasoning sets field value
func (o *FilesystemVerification) SetReasoning(v string) {
	o.Reasoning = v
}

// GetVerified returns the Verified field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *FilesystemVerification) GetVerified() bool {
	if o == nil || o.Verified.Get() == nil {
		var ret bool
		return ret
	}

	return *o.Verified.Get()
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilesystemVerification) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Verified.Get(), o.Verified.IsSet()
}

// SetVerified sets field value
func (o *FilesystemVerification) SetVerified(v bool) {
	o.Verified.Set(&v)
}

func (o FilesystemVerification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesystemVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	toSerialize["reasoning"] = o.Reasoning
	toSerialize["verified"] = o.Verified.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FilesystemVerification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reasoning",
		"verified",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilesystemVerification := _FilesystemVerification{}

	err = json.Unmarshal(data, &varFilesystemVerification)

	if err != nil {
		return err
	}

	*o = FilesystemVerification(varFilesystemVerification)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "confidence")
		delete(additionalProperties, "reasoning")
		delete(additionalProperties, "verified")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFilesystemVerification struct {
	value *FilesystemVerification
	isSet bool
}

func (v NullableFilesystemVerification) Get() *FilesystemVerification {
	return v.value
}

func (v *NullableFilesystemVerification) Set(val *FilesystemVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesystemVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesystemVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesystemVerification(val *FilesystemVerification) *NullableFilesystemVerification {
	return &NullableFilesystemVerification{value: val, isSet: true}
}

func (v NullableFilesystemVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesystemVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


