/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AddTeamMemberInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTeamMemberInputBody{}

// AddTeamMemberInputBody struct for AddTeamMemberInputBody
type AddTeamMemberInputBody struct {
	// User ID to add
	UserId int64 `json:"user_id"`
	AdditionalProperties map[string]interface{}
}

type _AddTeamMemberInputBody AddTeamMemberInputBody

// NewAddTeamMemberInputBody instantiates a new AddTeamMemberInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTeamMemberInputBody(userId int64) *AddTeamMemberInputBody {
	this := AddTeamMemberInputBody{}
	this.UserId = userId
	return &this
}

// NewAddTeamMemberInputBodyWithDefaults instantiates a new AddTeamMemberInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTeamMemberInputBodyWithDefaults() *AddTeamMemberInputBody {
	this := AddTeamMemberInputBody{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AddTeamMemberInputBody) GetUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddTeamMemberInputBody) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddTeamMemberInputBody) SetUserId(v int64) {
	o.UserId = v
}

func (o AddTeamMemberInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTeamMemberInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddTeamMemberInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddTeamMemberInputBody := _AddTeamMemberInputBody{}

	err = json.Unmarshal(data, &varAddTeamMemberInputBody)

	if err != nil {
		return err
	}

	*o = AddTeamMemberInputBody(varAddTeamMemberInputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddTeamMemberInputBody struct {
	value *AddTeamMemberInputBody
	isSet bool
}

func (v NullableAddTeamMemberInputBody) Get() *AddTeamMemberInputBody {
	return v.value
}

func (v *NullableAddTeamMemberInputBody) Set(val *AddTeamMemberInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTeamMemberInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTeamMemberInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTeamMemberInputBody(val *AddTeamMemberInputBody) *NullableAddTeamMemberInputBody {
	return &NullableAddTeamMemberInputBody{value: val, isSet: true}
}

func (v NullableAddTeamMemberInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTeamMemberInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


