/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UnionDataType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnionDataType{}

// UnionDataType struct for UnionDataType
type UnionDataType struct {
	// When this type was extracted.
	CreatedAt time.Time `json:"created_at"`
	// Identifies the type within its analysis. 0 is a valid id.
	DataTypeId int64 `json:"data_type_id"`
	// Absent only for a type referenced but never defined.
	Definition *UnionDefinition `json:"definition,omitempty"`
	// Whether this type carries a definition. False for the kinds that never have one and for a type referenced but never defined.
	DefinitionPresent bool `json:"has_definition"`
	Kind string `json:"kind"`
	// Type name.
	Name string `json:"name"`
	// The scope qualifying the type name. Empty for a program-defined type.
	Namespace string `json:"namespace"`
	// Size in bytes, absent when it could not be determined.
	Size *int64 `json:"size,omitempty"`
	// ID of the analysis the source function belongs to, when it could be resolved.
	SourceAnalysisId *int64 `json:"source_analysis_id,omitempty"`
	// The function this type was copied from, when transferred rather than extracted.
	SourceFunctionId *int64 `json:"source_function_id,omitempty"`
	// Where this type came from.
	SourceType string `json:"source_type"`
	AdditionalProperties map[string]interface{}
}

type _UnionDataType UnionDataType

// NewUnionDataType instantiates a new UnionDataType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnionDataType(createdAt time.Time, dataTypeId int64, definitionPresent bool, kind string, name string, namespace string, sourceType string) *UnionDataType {
	this := UnionDataType{}
	this.CreatedAt = createdAt
	this.DataTypeId = dataTypeId
	this.DefinitionPresent = definitionPresent
	this.Kind = kind
	this.Name = name
	this.Namespace = namespace
	this.SourceType = sourceType
	return &this
}

// NewUnionDataTypeWithDefaults instantiates a new UnionDataType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnionDataTypeWithDefaults() *UnionDataType {
	this := UnionDataType{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *UnionDataType) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UnionDataType) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDataTypeId returns the DataTypeId field value
func (o *UnionDataType) GetDataTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DataTypeId
}

// GetDataTypeIdOk returns a tuple with the DataTypeId field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetDataTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataTypeId, true
}

// SetDataTypeId sets field value
func (o *UnionDataType) SetDataTypeId(v int64) {
	o.DataTypeId = v
}

// GetDefinition returns the Definition field value if set, zero value otherwise.
func (o *UnionDataType) GetDefinition() UnionDefinition {
	if o == nil || IsNil(o.Definition) {
		var ret UnionDefinition
		return ret
	}
	return *o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetDefinitionOk() (*UnionDefinition, bool) {
	if o == nil || IsNil(o.Definition) {
		return nil, false
	}
	return o.Definition, true
}

// HasDefinition returns a boolean if a field has been set.
func (o *UnionDataType) HasDefinition() bool {
	if o != nil && !IsNil(o.Definition) {
		return true
	}

	return false
}

// SetDefinition gets a reference to the given UnionDefinition and assigns it to the Definition field.
func (o *UnionDataType) SetDefinition(v UnionDefinition) {
	o.Definition = &v
}

// GetDefinitionPresent returns the DefinitionPresent field value
func (o *UnionDataType) GetDefinitionPresent() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DefinitionPresent
}

// GetDefinitionPresentOk returns a tuple with the DefinitionPresent field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetDefinitionPresentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefinitionPresent, true
}

// SetDefinitionPresent sets field value
func (o *UnionDataType) SetDefinitionPresent(v bool) {
	o.DefinitionPresent = v
}

// GetKind returns the Kind field value
func (o *UnionDataType) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *UnionDataType) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *UnionDataType) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UnionDataType) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *UnionDataType) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *UnionDataType) SetNamespace(v string) {
	o.Namespace = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *UnionDataType) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *UnionDataType) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *UnionDataType) SetSize(v int64) {
	o.Size = &v
}

// GetSourceAnalysisId returns the SourceAnalysisId field value if set, zero value otherwise.
func (o *UnionDataType) GetSourceAnalysisId() int64 {
	if o == nil || IsNil(o.SourceAnalysisId) {
		var ret int64
		return ret
	}
	return *o.SourceAnalysisId
}

// GetSourceAnalysisIdOk returns a tuple with the SourceAnalysisId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetSourceAnalysisIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SourceAnalysisId) {
		return nil, false
	}
	return o.SourceAnalysisId, true
}

// HasSourceAnalysisId returns a boolean if a field has been set.
func (o *UnionDataType) HasSourceAnalysisId() bool {
	if o != nil && !IsNil(o.SourceAnalysisId) {
		return true
	}

	return false
}

// SetSourceAnalysisId gets a reference to the given int64 and assigns it to the SourceAnalysisId field.
func (o *UnionDataType) SetSourceAnalysisId(v int64) {
	o.SourceAnalysisId = &v
}

// GetSourceFunctionId returns the SourceFunctionId field value if set, zero value otherwise.
func (o *UnionDataType) GetSourceFunctionId() int64 {
	if o == nil || IsNil(o.SourceFunctionId) {
		var ret int64
		return ret
	}
	return *o.SourceFunctionId
}

// GetSourceFunctionIdOk returns a tuple with the SourceFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetSourceFunctionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SourceFunctionId) {
		return nil, false
	}
	return o.SourceFunctionId, true
}

// HasSourceFunctionId returns a boolean if a field has been set.
func (o *UnionDataType) HasSourceFunctionId() bool {
	if o != nil && !IsNil(o.SourceFunctionId) {
		return true
	}

	return false
}

// SetSourceFunctionId gets a reference to the given int64 and assigns it to the SourceFunctionId field.
func (o *UnionDataType) SetSourceFunctionId(v int64) {
	o.SourceFunctionId = &v
}

// GetSourceType returns the SourceType field value
func (o *UnionDataType) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *UnionDataType) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *UnionDataType) SetSourceType(v string) {
	o.SourceType = v
}

func (o UnionDataType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnionDataType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["data_type_id"] = o.DataTypeId
	if !IsNil(o.Definition) {
		toSerialize["definition"] = o.Definition
	}
	toSerialize["has_definition"] = o.DefinitionPresent
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["namespace"] = o.Namespace
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.SourceAnalysisId) {
		toSerialize["source_analysis_id"] = o.SourceAnalysisId
	}
	if !IsNil(o.SourceFunctionId) {
		toSerialize["source_function_id"] = o.SourceFunctionId
	}
	toSerialize["source_type"] = o.SourceType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnionDataType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"data_type_id",
		"has_definition",
		"kind",
		"name",
		"namespace",
		"source_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnionDataType := _UnionDataType{}

	err = json.Unmarshal(data, &varUnionDataType)

	if err != nil {
		return err
	}

	*o = UnionDataType(varUnionDataType)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "data_type_id")
		delete(additionalProperties, "definition")
		delete(additionalProperties, "has_definition")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "name")
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "size")
		delete(additionalProperties, "source_analysis_id")
		delete(additionalProperties, "source_function_id")
		delete(additionalProperties, "source_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnionDataType struct {
	value *UnionDataType
	isSet bool
}

func (v NullableUnionDataType) Get() *UnionDataType {
	return v.value
}

func (v *NullableUnionDataType) Set(val *UnionDataType) {
	v.value = val
	v.isSet = true
}

func (v NullableUnionDataType) IsSet() bool {
	return v.isSet
}

func (v *NullableUnionDataType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnionDataType(val *UnionDataType) *NullableUnionDataType {
	return &NullableUnionDataType{value: val, isSet: true}
}

func (v NullableUnionDataType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnionDataType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


