/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SoftwareTypeCountsBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoftwareTypeCountsBody{}

// SoftwareTypeCountsBody struct for SoftwareTypeCountsBody
type SoftwareTypeCountsBody struct {
	// Reports classifying the software as benign
	Benign int64 `json:"benign"`
	// Reports classifying the software as legitimate
	Legitimate int64 `json:"legitimate"`
	// Reports classifying the software as a legitimate backdoor
	LegitimateSoftwareBackdoor int64 `json:"legitimate_software_backdoor"`
	// Reports classifying the software as malicious
	Malicious int64 `json:"malicious"`
	// Reports classifying the software as a potentially unwanted application
	PotentiallyUnwantedApplication int64 `json:"potentially_unwanted_application"`
	AdditionalProperties map[string]interface{}
}

type _SoftwareTypeCountsBody SoftwareTypeCountsBody

// NewSoftwareTypeCountsBody instantiates a new SoftwareTypeCountsBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoftwareTypeCountsBody(benign int64, legitimate int64, legitimateSoftwareBackdoor int64, malicious int64, potentiallyUnwantedApplication int64) *SoftwareTypeCountsBody {
	this := SoftwareTypeCountsBody{}
	this.Benign = benign
	this.Legitimate = legitimate
	this.LegitimateSoftwareBackdoor = legitimateSoftwareBackdoor
	this.Malicious = malicious
	this.PotentiallyUnwantedApplication = potentiallyUnwantedApplication
	return &this
}

// NewSoftwareTypeCountsBodyWithDefaults instantiates a new SoftwareTypeCountsBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoftwareTypeCountsBodyWithDefaults() *SoftwareTypeCountsBody {
	this := SoftwareTypeCountsBody{}
	return &this
}

// GetBenign returns the Benign field value
func (o *SoftwareTypeCountsBody) GetBenign() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Benign
}

// GetBenignOk returns a tuple with the Benign field value
// and a boolean to check if the value has been set.
func (o *SoftwareTypeCountsBody) GetBenignOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Benign, true
}

// SetBenign sets field value
func (o *SoftwareTypeCountsBody) SetBenign(v int64) {
	o.Benign = v
}

// GetLegitimate returns the Legitimate field value
func (o *SoftwareTypeCountsBody) GetLegitimate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Legitimate
}

// GetLegitimateOk returns a tuple with the Legitimate field value
// and a boolean to check if the value has been set.
func (o *SoftwareTypeCountsBody) GetLegitimateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Legitimate, true
}

// SetLegitimate sets field value
func (o *SoftwareTypeCountsBody) SetLegitimate(v int64) {
	o.Legitimate = v
}

// GetLegitimateSoftwareBackdoor returns the LegitimateSoftwareBackdoor field value
func (o *SoftwareTypeCountsBody) GetLegitimateSoftwareBackdoor() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LegitimateSoftwareBackdoor
}

// GetLegitimateSoftwareBackdoorOk returns a tuple with the LegitimateSoftwareBackdoor field value
// and a boolean to check if the value has been set.
func (o *SoftwareTypeCountsBody) GetLegitimateSoftwareBackdoorOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegitimateSoftwareBackdoor, true
}

// SetLegitimateSoftwareBackdoor sets field value
func (o *SoftwareTypeCountsBody) SetLegitimateSoftwareBackdoor(v int64) {
	o.LegitimateSoftwareBackdoor = v
}

// GetMalicious returns the Malicious field value
func (o *SoftwareTypeCountsBody) GetMalicious() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Malicious
}

// GetMaliciousOk returns a tuple with the Malicious field value
// and a boolean to check if the value has been set.
func (o *SoftwareTypeCountsBody) GetMaliciousOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Malicious, true
}

// SetMalicious sets field value
func (o *SoftwareTypeCountsBody) SetMalicious(v int64) {
	o.Malicious = v
}

// GetPotentiallyUnwantedApplication returns the PotentiallyUnwantedApplication field value
func (o *SoftwareTypeCountsBody) GetPotentiallyUnwantedApplication() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PotentiallyUnwantedApplication
}

// GetPotentiallyUnwantedApplicationOk returns a tuple with the PotentiallyUnwantedApplication field value
// and a boolean to check if the value has been set.
func (o *SoftwareTypeCountsBody) GetPotentiallyUnwantedApplicationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PotentiallyUnwantedApplication, true
}

// SetPotentiallyUnwantedApplication sets field value
func (o *SoftwareTypeCountsBody) SetPotentiallyUnwantedApplication(v int64) {
	o.PotentiallyUnwantedApplication = v
}

func (o SoftwareTypeCountsBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoftwareTypeCountsBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["benign"] = o.Benign
	toSerialize["legitimate"] = o.Legitimate
	toSerialize["legitimate_software_backdoor"] = o.LegitimateSoftwareBackdoor
	toSerialize["malicious"] = o.Malicious
	toSerialize["potentially_unwanted_application"] = o.PotentiallyUnwantedApplication

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SoftwareTypeCountsBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"benign",
		"legitimate",
		"legitimate_software_backdoor",
		"malicious",
		"potentially_unwanted_application",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSoftwareTypeCountsBody := _SoftwareTypeCountsBody{}

	err = json.Unmarshal(data, &varSoftwareTypeCountsBody)

	if err != nil {
		return err
	}

	*o = SoftwareTypeCountsBody(varSoftwareTypeCountsBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "benign")
		delete(additionalProperties, "legitimate")
		delete(additionalProperties, "legitimate_software_backdoor")
		delete(additionalProperties, "malicious")
		delete(additionalProperties, "potentially_unwanted_application")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSoftwareTypeCountsBody struct {
	value *SoftwareTypeCountsBody
	isSet bool
}

func (v NullableSoftwareTypeCountsBody) Get() *SoftwareTypeCountsBody {
	return v.value
}

func (v *NullableSoftwareTypeCountsBody) Set(val *SoftwareTypeCountsBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSoftwareTypeCountsBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSoftwareTypeCountsBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoftwareTypeCountsBody(val *SoftwareTypeCountsBody) *NullableSoftwareTypeCountsBody {
	return &NullableSoftwareTypeCountsBody{value: val, isSet: true}
}

func (v NullableSoftwareTypeCountsBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoftwareTypeCountsBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


