/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateUnionDataType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUnionDataType{}

// UpdateUnionDataType struct for UpdateUnionDataType
type UpdateUnionDataType struct {
	// The type to replace, as returned by the data types list for this analysis.
	DataTypeId int64 `json:"data_type_id"`
	Definition UnionDefinition `json:"definition"`
	Kind string `json:"kind"`
	// Type name. Unique within the analysis for a given namespace and kind.
	Name string `json:"name"`
	// The scope qualifying the type name. Omit for a type of the binary's own.
	Namespace *string `json:"namespace,omitempty"`
	// Size in bytes. Omit when it is not known.
	Size *int64 `json:"size,omitempty"`
}

type _UpdateUnionDataType UpdateUnionDataType

// NewUpdateUnionDataType instantiates a new UpdateUnionDataType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUnionDataType(dataTypeId int64, definition UnionDefinition, kind string, name string) *UpdateUnionDataType {
	this := UpdateUnionDataType{}
	this.DataTypeId = dataTypeId
	this.Definition = definition
	this.Kind = kind
	this.Name = name
	return &this
}

// NewUpdateUnionDataTypeWithDefaults instantiates a new UpdateUnionDataType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUnionDataTypeWithDefaults() *UpdateUnionDataType {
	this := UpdateUnionDataType{}
	return &this
}

// GetDataTypeId returns the DataTypeId field value
func (o *UpdateUnionDataType) GetDataTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DataTypeId
}

// GetDataTypeIdOk returns a tuple with the DataTypeId field value
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetDataTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataTypeId, true
}

// SetDataTypeId sets field value
func (o *UpdateUnionDataType) SetDataTypeId(v int64) {
	o.DataTypeId = v
}

// GetDefinition returns the Definition field value
func (o *UpdateUnionDataType) GetDefinition() UnionDefinition {
	if o == nil {
		var ret UnionDefinition
		return ret
	}

	return o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetDefinitionOk() (*UnionDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Definition, true
}

// SetDefinition sets field value
func (o *UpdateUnionDataType) SetDefinition(v UnionDefinition) {
	o.Definition = v
}

// GetKind returns the Kind field value
func (o *UpdateUnionDataType) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *UpdateUnionDataType) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *UpdateUnionDataType) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateUnionDataType) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *UpdateUnionDataType) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *UpdateUnionDataType) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *UpdateUnionDataType) SetNamespace(v string) {
	o.Namespace = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *UpdateUnionDataType) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUnionDataType) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *UpdateUnionDataType) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *UpdateUnionDataType) SetSize(v int64) {
	o.Size = &v
}

func (o UpdateUnionDataType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUnionDataType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data_type_id"] = o.DataTypeId
	toSerialize["definition"] = o.Definition
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

func (o *UpdateUnionDataType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data_type_id",
		"definition",
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateUnionDataType := _UpdateUnionDataType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateUnionDataType)

	if err != nil {
		return err
	}

	*o = UpdateUnionDataType(varUpdateUnionDataType)

	return err
}

type NullableUpdateUnionDataType struct {
	value *UpdateUnionDataType
	isSet bool
}

func (v NullableUpdateUnionDataType) Get() *UpdateUnionDataType {
	return v.value
}

func (v *NullableUpdateUnionDataType) Set(val *UpdateUnionDataType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUnionDataType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUnionDataType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUnionDataType(val *UpdateUnionDataType) *NullableUpdateUnionDataType {
	return &NullableUpdateUnionDataType{value: val, isSet: true}
}

func (v NullableUpdateUnionDataType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUnionDataType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


