/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UploadOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadOutputBody{}

// UploadOutputBody struct for UploadOutputBody
type UploadOutputBody struct {
	// Ways to unblock POST /v3/analyses for this file if it cannot be statically analysed as-is; empty if no requirement applies.
	AnalysisRequirements []AnalysisRequirement `json:"analysis_requirements"`
	// Whether the firmware/extraction flow can accept this file.
	CanExtract bool `json:"can_extract"`
	// Whether the file can be extracted and run in the Windows sandbox.
	CanSandbox bool `json:"can_sandbox"`
	// The kind of file that was uploaded.
	FileType string `json:"file_type"`
	// The filename as given by the caller.
	Filename string `json:"filename"`
	// Whether the detected format is a container/compression archive.
	IsArchive bool `json:"is_archive"`
	// The MIME type detected from the file's contents, independent of upload_file_type.
	Mime string `json:"mime"`
	// SHA-256 hash of the uploaded file; the storage key for every subsequent reference to it.
	Sha256Hash string `json:"sha_256_hash"`
	AdditionalProperties map[string]interface{}
}

type _UploadOutputBody UploadOutputBody

// NewUploadOutputBody instantiates a new UploadOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadOutputBody(analysisRequirements []AnalysisRequirement, canExtract bool, canSandbox bool, fileType string, filename string, isArchive bool, mime string, sha256Hash string) *UploadOutputBody {
	this := UploadOutputBody{}
	this.AnalysisRequirements = analysisRequirements
	this.CanExtract = canExtract
	this.CanSandbox = canSandbox
	this.FileType = fileType
	this.Filename = filename
	this.IsArchive = isArchive
	this.Mime = mime
	this.Sha256Hash = sha256Hash
	return &this
}

// NewUploadOutputBodyWithDefaults instantiates a new UploadOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadOutputBodyWithDefaults() *UploadOutputBody {
	this := UploadOutputBody{}
	return &this
}

// GetAnalysisRequirements returns the AnalysisRequirements field value
// If the value is explicit nil, the zero value for []AnalysisRequirement will be returned
func (o *UploadOutputBody) GetAnalysisRequirements() []AnalysisRequirement {
	if o == nil {
		var ret []AnalysisRequirement
		return ret
	}

	return o.AnalysisRequirements
}

// GetAnalysisRequirementsOk returns a tuple with the AnalysisRequirements field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadOutputBody) GetAnalysisRequirementsOk() ([]AnalysisRequirement, bool) {
	if o == nil || IsNil(o.AnalysisRequirements) {
		return nil, false
	}
	return o.AnalysisRequirements, true
}

// SetAnalysisRequirements sets field value
func (o *UploadOutputBody) SetAnalysisRequirements(v []AnalysisRequirement) {
	o.AnalysisRequirements = v
}

// GetCanExtract returns the CanExtract field value
func (o *UploadOutputBody) GetCanExtract() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanExtract
}

// GetCanExtractOk returns a tuple with the CanExtract field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetCanExtractOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanExtract, true
}

// SetCanExtract sets field value
func (o *UploadOutputBody) SetCanExtract(v bool) {
	o.CanExtract = v
}

// GetCanSandbox returns the CanSandbox field value
func (o *UploadOutputBody) GetCanSandbox() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanSandbox
}

// GetCanSandboxOk returns a tuple with the CanSandbox field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetCanSandboxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanSandbox, true
}

// SetCanSandbox sets field value
func (o *UploadOutputBody) SetCanSandbox(v bool) {
	o.CanSandbox = v
}

// GetFileType returns the FileType field value
func (o *UploadOutputBody) GetFileType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetFileTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *UploadOutputBody) SetFileType(v string) {
	o.FileType = v
}

// GetFilename returns the Filename field value
func (o *UploadOutputBody) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *UploadOutputBody) SetFilename(v string) {
	o.Filename = v
}

// GetIsArchive returns the IsArchive field value
func (o *UploadOutputBody) GetIsArchive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsArchive
}

// GetIsArchiveOk returns a tuple with the IsArchive field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetIsArchiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsArchive, true
}

// SetIsArchive sets field value
func (o *UploadOutputBody) SetIsArchive(v bool) {
	o.IsArchive = v
}

// GetMime returns the Mime field value
func (o *UploadOutputBody) GetMime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mime
}

// GetMimeOk returns a tuple with the Mime field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetMimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mime, true
}

// SetMime sets field value
func (o *UploadOutputBody) SetMime(v string) {
	o.Mime = v
}

// GetSha256Hash returns the Sha256Hash field value
func (o *UploadOutputBody) GetSha256Hash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sha256Hash
}

// GetSha256HashOk returns a tuple with the Sha256Hash field value
// and a boolean to check if the value has been set.
func (o *UploadOutputBody) GetSha256HashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sha256Hash, true
}

// SetSha256Hash sets field value
func (o *UploadOutputBody) SetSha256Hash(v string) {
	o.Sha256Hash = v
}

func (o UploadOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AnalysisRequirements != nil {
		toSerialize["analysis_requirements"] = o.AnalysisRequirements
	}
	toSerialize["can_extract"] = o.CanExtract
	toSerialize["can_sandbox"] = o.CanSandbox
	toSerialize["file_type"] = o.FileType
	toSerialize["filename"] = o.Filename
	toSerialize["is_archive"] = o.IsArchive
	toSerialize["mime"] = o.Mime
	toSerialize["sha_256_hash"] = o.Sha256Hash

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UploadOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"analysis_requirements",
		"can_extract",
		"can_sandbox",
		"file_type",
		"filename",
		"is_archive",
		"mime",
		"sha_256_hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadOutputBody := _UploadOutputBody{}

	err = json.Unmarshal(data, &varUploadOutputBody)

	if err != nil {
		return err
	}

	*o = UploadOutputBody(varUploadOutputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "analysis_requirements")
		delete(additionalProperties, "can_extract")
		delete(additionalProperties, "can_sandbox")
		delete(additionalProperties, "file_type")
		delete(additionalProperties, "filename")
		delete(additionalProperties, "is_archive")
		delete(additionalProperties, "mime")
		delete(additionalProperties, "sha_256_hash")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUploadOutputBody struct {
	value *UploadOutputBody
	isSet bool
}

func (v NullableUploadOutputBody) Get() *UploadOutputBody {
	return v.value
}

func (v *NullableUploadOutputBody) Set(val *UploadOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadOutputBody(val *UploadOutputBody) *NullableUploadOutputBody {
	return &NullableUploadOutputBody{value: val, isSet: true}
}

func (v NullableUploadOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


