/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the RenderedToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderedToken{}

// RenderedToken struct for RenderedToken
type RenderedToken struct {
	// Data type this token names, or for a field the type that declares it. Scoped by the response's analysis_id.
	DataTypeId *int64 `json:"data_type_id,omitempty"`
	// Function this token calls or names. Absent when the address reaches no function of this binary.
	FunctionId *int64 `json:"function_id,omitempty"`
	// Imported function this token calls. Set instead of function_id for an external call.
	ImportedFunctionId *int64 `json:"imported_function_id,omitempty"`
	// What the token names.
	Kind string `json:"kind"`
	// Virtual address the token resolves to. Absent for a token with no address.
	Vaddr *int64 `json:"vaddr,omitempty"`
	// Name the token resolves to.
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _RenderedToken RenderedToken

// NewRenderedToken instantiates a new RenderedToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderedToken(kind string, value string) *RenderedToken {
	this := RenderedToken{}
	this.Kind = kind
	this.Value = value
	return &this
}

// NewRenderedTokenWithDefaults instantiates a new RenderedToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderedTokenWithDefaults() *RenderedToken {
	this := RenderedToken{}
	return &this
}

// GetDataTypeId returns the DataTypeId field value if set, zero value otherwise.
func (o *RenderedToken) GetDataTypeId() int64 {
	if o == nil || IsNil(o.DataTypeId) {
		var ret int64
		return ret
	}
	return *o.DataTypeId
}

// GetDataTypeIdOk returns a tuple with the DataTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetDataTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DataTypeId) {
		return nil, false
	}
	return o.DataTypeId, true
}

// HasDataTypeId returns a boolean if a field has been set.
func (o *RenderedToken) HasDataTypeId() bool {
	if o != nil && !IsNil(o.DataTypeId) {
		return true
	}

	return false
}

// SetDataTypeId gets a reference to the given int64 and assigns it to the DataTypeId field.
func (o *RenderedToken) SetDataTypeId(v int64) {
	o.DataTypeId = &v
}

// GetFunctionId returns the FunctionId field value if set, zero value otherwise.
func (o *RenderedToken) GetFunctionId() int64 {
	if o == nil || IsNil(o.FunctionId) {
		var ret int64
		return ret
	}
	return *o.FunctionId
}

// GetFunctionIdOk returns a tuple with the FunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetFunctionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.FunctionId) {
		return nil, false
	}
	return o.FunctionId, true
}

// HasFunctionId returns a boolean if a field has been set.
func (o *RenderedToken) HasFunctionId() bool {
	if o != nil && !IsNil(o.FunctionId) {
		return true
	}

	return false
}

// SetFunctionId gets a reference to the given int64 and assigns it to the FunctionId field.
func (o *RenderedToken) SetFunctionId(v int64) {
	o.FunctionId = &v
}

// GetImportedFunctionId returns the ImportedFunctionId field value if set, zero value otherwise.
func (o *RenderedToken) GetImportedFunctionId() int64 {
	if o == nil || IsNil(o.ImportedFunctionId) {
		var ret int64
		return ret
	}
	return *o.ImportedFunctionId
}

// GetImportedFunctionIdOk returns a tuple with the ImportedFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetImportedFunctionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ImportedFunctionId) {
		return nil, false
	}
	return o.ImportedFunctionId, true
}

// HasImportedFunctionId returns a boolean if a field has been set.
func (o *RenderedToken) HasImportedFunctionId() bool {
	if o != nil && !IsNil(o.ImportedFunctionId) {
		return true
	}

	return false
}

// SetImportedFunctionId gets a reference to the given int64 and assigns it to the ImportedFunctionId field.
func (o *RenderedToken) SetImportedFunctionId(v int64) {
	o.ImportedFunctionId = &v
}

// GetKind returns the Kind field value
func (o *RenderedToken) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *RenderedToken) SetKind(v string) {
	o.Kind = v
}

// GetVaddr returns the Vaddr field value if set, zero value otherwise.
func (o *RenderedToken) GetVaddr() int64 {
	if o == nil || IsNil(o.Vaddr) {
		var ret int64
		return ret
	}
	return *o.Vaddr
}

// GetVaddrOk returns a tuple with the Vaddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetVaddrOk() (*int64, bool) {
	if o == nil || IsNil(o.Vaddr) {
		return nil, false
	}
	return o.Vaddr, true
}

// HasVaddr returns a boolean if a field has been set.
func (o *RenderedToken) HasVaddr() bool {
	if o != nil && !IsNil(o.Vaddr) {
		return true
	}

	return false
}

// SetVaddr gets a reference to the given int64 and assigns it to the Vaddr field.
func (o *RenderedToken) SetVaddr(v int64) {
	o.Vaddr = &v
}

// GetValue returns the Value field value
func (o *RenderedToken) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RenderedToken) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RenderedToken) SetValue(v string) {
	o.Value = v
}

func (o RenderedToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderedToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataTypeId) {
		toSerialize["data_type_id"] = o.DataTypeId
	}
	if !IsNil(o.FunctionId) {
		toSerialize["function_id"] = o.FunctionId
	}
	if !IsNil(o.ImportedFunctionId) {
		toSerialize["imported_function_id"] = o.ImportedFunctionId
	}
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Vaddr) {
		toSerialize["vaddr"] = o.Vaddr
	}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RenderedToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenderedToken := _RenderedToken{}

	err = json.Unmarshal(data, &varRenderedToken)

	if err != nil {
		return err
	}

	*o = RenderedToken(varRenderedToken)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data_type_id")
		delete(additionalProperties, "function_id")
		delete(additionalProperties, "imported_function_id")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "vaddr")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRenderedToken struct {
	value *RenderedToken
	isSet bool
}

func (v NullableRenderedToken) Get() *RenderedToken {
	return v.value
}

func (v *NullableRenderedToken) Set(val *RenderedToken) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderedToken) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderedToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderedToken(val *RenderedToken) *NullableRenderedToken {
	return &NullableRenderedToken{value: val, isSet: true}
}

func (v NullableRenderedToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderedToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


