/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AnalysisCapabilitiesOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisCapabilitiesOutputBody{}

// AnalysisCapabilitiesOutputBody struct for AnalysisCapabilitiesOutputBody
type AnalysisCapabilitiesOutputBody struct {
	// Capabilities found across the binary, ordered by function address. Empty when the binary has no capability record
	Capabilities []AnalysisCapabilityBody `json:"capabilities"`
	AdditionalProperties map[string]interface{}
}

type _AnalysisCapabilitiesOutputBody AnalysisCapabilitiesOutputBody

// NewAnalysisCapabilitiesOutputBody instantiates a new AnalysisCapabilitiesOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisCapabilitiesOutputBody(capabilities []AnalysisCapabilityBody) *AnalysisCapabilitiesOutputBody {
	this := AnalysisCapabilitiesOutputBody{}
	this.Capabilities = capabilities
	return &this
}

// NewAnalysisCapabilitiesOutputBodyWithDefaults instantiates a new AnalysisCapabilitiesOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisCapabilitiesOutputBodyWithDefaults() *AnalysisCapabilitiesOutputBody {
	this := AnalysisCapabilitiesOutputBody{}
	return &this
}

// GetCapabilities returns the Capabilities field value
// If the value is explicit nil, the zero value for []AnalysisCapabilityBody will be returned
func (o *AnalysisCapabilitiesOutputBody) GetCapabilities() []AnalysisCapabilityBody {
	if o == nil {
		var ret []AnalysisCapabilityBody
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AnalysisCapabilitiesOutputBody) GetCapabilitiesOk() ([]AnalysisCapabilityBody, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// SetCapabilities sets field value
func (o *AnalysisCapabilitiesOutputBody) SetCapabilities(v []AnalysisCapabilityBody) {
	o.Capabilities = v
}

func (o AnalysisCapabilitiesOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisCapabilitiesOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AnalysisCapabilitiesOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capabilities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalysisCapabilitiesOutputBody := _AnalysisCapabilitiesOutputBody{}

	err = json.Unmarshal(data, &varAnalysisCapabilitiesOutputBody)

	if err != nil {
		return err
	}

	*o = AnalysisCapabilitiesOutputBody(varAnalysisCapabilitiesOutputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "capabilities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAnalysisCapabilitiesOutputBody struct {
	value *AnalysisCapabilitiesOutputBody
	isSet bool
}

func (v NullableAnalysisCapabilitiesOutputBody) Get() *AnalysisCapabilitiesOutputBody {
	return v.value
}

func (v *NullableAnalysisCapabilitiesOutputBody) Set(val *AnalysisCapabilitiesOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisCapabilitiesOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisCapabilitiesOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisCapabilitiesOutputBody(val *AnalysisCapabilitiesOutputBody) *NullableAnalysisCapabilitiesOutputBody {
	return &NullableAnalysisCapabilitiesOutputBody{value: val, isSet: true}
}

func (v NullableAnalysisCapabilitiesOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisCapabilitiesOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


