/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the TriggerNetworkingScanInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerNetworkingScanInputBody{}

// TriggerNetworkingScanInputBody struct for TriggerNetworkingScanInputBody
type TriggerNetworkingScanInputBody struct {
	// Restrict findings to these categories. Omit to scan the default remote-communication set.
	Categories []string `json:"categories,omitempty"`
	// Only report functions whose own name matches a known networking API; skips the calls-into-networking pass, avoiding a bulk call-graph fetch.
	DirectOnly *bool `json:"direct_only,omitempty"`
	// Restrict findings to these sources. Omit to scan every source.
	Sources []string `json:"sources,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TriggerNetworkingScanInputBody TriggerNetworkingScanInputBody

// NewTriggerNetworkingScanInputBody instantiates a new TriggerNetworkingScanInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerNetworkingScanInputBody() *TriggerNetworkingScanInputBody {
	this := TriggerNetworkingScanInputBody{}
	return &this
}

// NewTriggerNetworkingScanInputBodyWithDefaults instantiates a new TriggerNetworkingScanInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerNetworkingScanInputBodyWithDefaults() *TriggerNetworkingScanInputBody {
	this := TriggerNetworkingScanInputBody{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerNetworkingScanInputBody) GetCategories() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerNetworkingScanInputBody) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *TriggerNetworkingScanInputBody) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *TriggerNetworkingScanInputBody) SetCategories(v []string) {
	o.Categories = v
}

// GetDirectOnly returns the DirectOnly field value if set, zero value otherwise.
func (o *TriggerNetworkingScanInputBody) GetDirectOnly() bool {
	if o == nil || IsNil(o.DirectOnly) {
		var ret bool
		return ret
	}
	return *o.DirectOnly
}

// GetDirectOnlyOk returns a tuple with the DirectOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerNetworkingScanInputBody) GetDirectOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.DirectOnly) {
		return nil, false
	}
	return o.DirectOnly, true
}

// HasDirectOnly returns a boolean if a field has been set.
func (o *TriggerNetworkingScanInputBody) HasDirectOnly() bool {
	if o != nil && !IsNil(o.DirectOnly) {
		return true
	}

	return false
}

// SetDirectOnly gets a reference to the given bool and assigns it to the DirectOnly field.
func (o *TriggerNetworkingScanInputBody) SetDirectOnly(v bool) {
	o.DirectOnly = &v
}

// GetSources returns the Sources field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TriggerNetworkingScanInputBody) GetSources() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TriggerNetworkingScanInputBody) GetSourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *TriggerNetworkingScanInputBody) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []string and assigns it to the Sources field.
func (o *TriggerNetworkingScanInputBody) SetSources(v []string) {
	o.Sources = v
}

func (o TriggerNetworkingScanInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerNetworkingScanInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Categories != nil {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.DirectOnly) {
		toSerialize["direct_only"] = o.DirectOnly
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TriggerNetworkingScanInputBody) UnmarshalJSON(data []byte) (err error) {
	varTriggerNetworkingScanInputBody := _TriggerNetworkingScanInputBody{}

	err = json.Unmarshal(data, &varTriggerNetworkingScanInputBody)

	if err != nil {
		return err
	}

	*o = TriggerNetworkingScanInputBody(varTriggerNetworkingScanInputBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "categories")
		delete(additionalProperties, "direct_only")
		delete(additionalProperties, "sources")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTriggerNetworkingScanInputBody struct {
	value *TriggerNetworkingScanInputBody
	isSet bool
}

func (v NullableTriggerNetworkingScanInputBody) Get() *TriggerNetworkingScanInputBody {
	return v.value
}

func (v *NullableTriggerNetworkingScanInputBody) Set(val *TriggerNetworkingScanInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerNetworkingScanInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerNetworkingScanInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerNetworkingScanInputBody(val *TriggerNetworkingScanInputBody) *NullableTriggerNetworkingScanInputBody {
	return &NullableTriggerNetworkingScanInputBody{value: val, isSet: true}
}

func (v NullableTriggerNetworkingScanInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerNetworkingScanInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


