/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PcapBodyInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PcapBodyInfo{}

// PcapBodyInfo struct for PcapBodyInfo
type PcapBodyInfo struct {
	Filename *string `json:"filename,omitempty"`
	IsPe bool `json:"is_pe"`
	MimeType *string `json:"mime_type,omitempty"`
	Preview *string `json:"preview,omitempty"`
	Sha256 *string `json:"sha256,omitempty"`
	Size int64 `json:"size"`
	YaraHits []string `json:"yara_hits,omitempty"`
}

type _PcapBodyInfo PcapBodyInfo

// NewPcapBodyInfo instantiates a new PcapBodyInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPcapBodyInfo(isPe bool, size int64) *PcapBodyInfo {
	this := PcapBodyInfo{}
	this.IsPe = isPe
	this.Size = size
	return &this
}

// NewPcapBodyInfoWithDefaults instantiates a new PcapBodyInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPcapBodyInfoWithDefaults() *PcapBodyInfo {
	this := PcapBodyInfo{}
	return &this
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *PcapBodyInfo) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *PcapBodyInfo) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *PcapBodyInfo) SetFilename(v string) {
	o.Filename = &v
}

// GetIsPe returns the IsPe field value
func (o *PcapBodyInfo) GetIsPe() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPe
}

// GetIsPeOk returns a tuple with the IsPe field value
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetIsPeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPe, true
}

// SetIsPe sets field value
func (o *PcapBodyInfo) SetIsPe(v bool) {
	o.IsPe = v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *PcapBodyInfo) GetMimeType() string {
	if o == nil || IsNil(o.MimeType) {
		var ret string
		return ret
	}
	return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MimeType) {
		return nil, false
	}
	return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *PcapBodyInfo) HasMimeType() bool {
	if o != nil && !IsNil(o.MimeType) {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *PcapBodyInfo) SetMimeType(v string) {
	o.MimeType = &v
}

// GetPreview returns the Preview field value if set, zero value otherwise.
func (o *PcapBodyInfo) GetPreview() string {
	if o == nil || IsNil(o.Preview) {
		var ret string
		return ret
	}
	return *o.Preview
}

// GetPreviewOk returns a tuple with the Preview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetPreviewOk() (*string, bool) {
	if o == nil || IsNil(o.Preview) {
		return nil, false
	}
	return o.Preview, true
}

// HasPreview returns a boolean if a field has been set.
func (o *PcapBodyInfo) HasPreview() bool {
	if o != nil && !IsNil(o.Preview) {
		return true
	}

	return false
}

// SetPreview gets a reference to the given string and assigns it to the Preview field.
func (o *PcapBodyInfo) SetPreview(v string) {
	o.Preview = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *PcapBodyInfo) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *PcapBodyInfo) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *PcapBodyInfo) SetSha256(v string) {
	o.Sha256 = &v
}

// GetSize returns the Size field value
func (o *PcapBodyInfo) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PcapBodyInfo) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PcapBodyInfo) SetSize(v int64) {
	o.Size = v
}

// GetYaraHits returns the YaraHits field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PcapBodyInfo) GetYaraHits() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.YaraHits
}

// GetYaraHitsOk returns a tuple with the YaraHits field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PcapBodyInfo) GetYaraHitsOk() ([]string, bool) {
	if o == nil || IsNil(o.YaraHits) {
		return nil, false
	}
	return o.YaraHits, true
}

// HasYaraHits returns a boolean if a field has been set.
func (o *PcapBodyInfo) HasYaraHits() bool {
	if o != nil && !IsNil(o.YaraHits) {
		return true
	}

	return false
}

// SetYaraHits gets a reference to the given []string and assigns it to the YaraHits field.
func (o *PcapBodyInfo) SetYaraHits(v []string) {
	o.YaraHits = v
}

func (o PcapBodyInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PcapBodyInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	toSerialize["is_pe"] = o.IsPe
	if !IsNil(o.MimeType) {
		toSerialize["mime_type"] = o.MimeType
	}
	if !IsNil(o.Preview) {
		toSerialize["preview"] = o.Preview
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	toSerialize["size"] = o.Size
	if o.YaraHits != nil {
		toSerialize["yara_hits"] = o.YaraHits
	}
	return toSerialize, nil
}

func (o *PcapBodyInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_pe",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPcapBodyInfo := _PcapBodyInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPcapBodyInfo)

	if err != nil {
		return err
	}

	*o = PcapBodyInfo(varPcapBodyInfo)

	return err
}

type NullablePcapBodyInfo struct {
	value *PcapBodyInfo
	isSet bool
}

func (v NullablePcapBodyInfo) Get() *PcapBodyInfo {
	return v.value
}

func (v *NullablePcapBodyInfo) Set(val *PcapBodyInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePcapBodyInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePcapBodyInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePcapBodyInfo(val *PcapBodyInfo) *NullablePcapBodyInfo {
	return &NullablePcapBodyInfo{value: val, isSet: true}
}

func (v NullablePcapBodyInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePcapBodyInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


