/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the Capability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Capability{}

// Capability struct for Capability
type Capability struct {
	// The capability itself
	Capability string `json:"capability"`
	// What the function does to exhibit the capability
	Description string `json:"description"`
	// ID of the function
	FunctionId int64 `json:"function_id"`
	// Name of the function
	FunctionName string `json:"function_name"`
	// Virtual address of the function, hex-encoded
	FunctionVaddr string `json:"function_vaddr"`
	// Capability category
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _Capability Capability

// NewCapability instantiates a new Capability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapability(capability string, description string, functionId int64, functionName string, functionVaddr string, type_ string) *Capability {
	this := Capability{}
	this.Capability = capability
	this.Description = description
	this.FunctionId = functionId
	this.FunctionName = functionName
	this.FunctionVaddr = functionVaddr
	this.Type = type_
	return &this
}

// NewCapabilityWithDefaults instantiates a new Capability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilityWithDefaults() *Capability {
	this := Capability{}
	return &this
}

// GetCapability returns the Capability field value
func (o *Capability) GetCapability() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Capability
}

// GetCapabilityOk returns a tuple with the Capability field value
// and a boolean to check if the value has been set.
func (o *Capability) GetCapabilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capability, true
}

// SetCapability sets field value
func (o *Capability) SetCapability(v string) {
	o.Capability = v
}

// GetDescription returns the Description field value
func (o *Capability) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Capability) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Capability) SetDescription(v string) {
	o.Description = v
}

// GetFunctionId returns the FunctionId field value
func (o *Capability) GetFunctionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FunctionId
}

// GetFunctionIdOk returns a tuple with the FunctionId field value
// and a boolean to check if the value has been set.
func (o *Capability) GetFunctionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionId, true
}

// SetFunctionId sets field value
func (o *Capability) SetFunctionId(v int64) {
	o.FunctionId = v
}

// GetFunctionName returns the FunctionName field value
func (o *Capability) GetFunctionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FunctionName
}

// GetFunctionNameOk returns a tuple with the FunctionName field value
// and a boolean to check if the value has been set.
func (o *Capability) GetFunctionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionName, true
}

// SetFunctionName sets field value
func (o *Capability) SetFunctionName(v string) {
	o.FunctionName = v
}

// GetFunctionVaddr returns the FunctionVaddr field value
func (o *Capability) GetFunctionVaddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FunctionVaddr
}

// GetFunctionVaddrOk returns a tuple with the FunctionVaddr field value
// and a boolean to check if the value has been set.
func (o *Capability) GetFunctionVaddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionVaddr, true
}

// SetFunctionVaddr sets field value
func (o *Capability) SetFunctionVaddr(v string) {
	o.FunctionVaddr = v
}

// GetType returns the Type field value
func (o *Capability) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Capability) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Capability) SetType(v string) {
	o.Type = v
}

func (o Capability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Capability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capability"] = o.Capability
	toSerialize["description"] = o.Description
	toSerialize["function_id"] = o.FunctionId
	toSerialize["function_name"] = o.FunctionName
	toSerialize["function_vaddr"] = o.FunctionVaddr
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Capability) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capability",
		"description",
		"function_id",
		"function_name",
		"function_vaddr",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCapability := _Capability{}

	err = json.Unmarshal(data, &varCapability)

	if err != nil {
		return err
	}

	*o = Capability(varCapability)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "capability")
		delete(additionalProperties, "description")
		delete(additionalProperties, "function_id")
		delete(additionalProperties, "function_name")
		delete(additionalProperties, "function_vaddr")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCapability struct {
	value *Capability
	isSet bool
}

func (v NullableCapability) Get() *Capability {
	return v.value
}

func (v *NullableCapability) Set(val *Capability) {
	v.value = val
	v.isSet = true
}

func (v NullableCapability) IsSet() bool {
	return v.isSet
}

func (v *NullableCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapability(val *Capability) *NullableCapability {
	return &NullableCapability{value: val, isSet: true}
}

func (v NullableCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


