/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Connection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Connection{}

// Connection struct for Connection
type Connection struct {
	BytesReceived *int64 `json:"bytes_received,omitempty"`
	BytesSent *int64 `json:"bytes_sent,omitempty"`
	Events []ReportEvent `json:"events,omitempty"`
	Ja3 *string `json:"ja3,omitempty"`
	Ja3s *string `json:"ja3s,omitempty"`
	LocalIp string `json:"local_ip"`
	LocalPort interface{} `json:"local_port"`
	Protocol string `json:"protocol"`
	RemoteIp string `json:"remote_ip"`
	RemotePort interface{} `json:"remote_port"`
	TcpCarvedFiles []TcpCarvedFile `json:"tcp_carved_files,omitempty"`
}

type _Connection Connection

// NewConnection instantiates a new Connection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnection(localIp string, localPort interface{}, protocol string, remoteIp string, remotePort interface{}) *Connection {
	this := Connection{}
	this.LocalIp = localIp
	this.LocalPort = localPort
	this.Protocol = protocol
	this.RemoteIp = remoteIp
	this.RemotePort = remotePort
	return &this
}

// NewConnectionWithDefaults instantiates a new Connection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionWithDefaults() *Connection {
	this := Connection{}
	return &this
}

// GetBytesReceived returns the BytesReceived field value if set, zero value otherwise.
func (o *Connection) GetBytesReceived() int64 {
	if o == nil || IsNil(o.BytesReceived) {
		var ret int64
		return ret
	}
	return *o.BytesReceived
}

// GetBytesReceivedOk returns a tuple with the BytesReceived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connection) GetBytesReceivedOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesReceived) {
		return nil, false
	}
	return o.BytesReceived, true
}

// HasBytesReceived returns a boolean if a field has been set.
func (o *Connection) HasBytesReceived() bool {
	if o != nil && !IsNil(o.BytesReceived) {
		return true
	}

	return false
}

// SetBytesReceived gets a reference to the given int64 and assigns it to the BytesReceived field.
func (o *Connection) SetBytesReceived(v int64) {
	o.BytesReceived = &v
}

// GetBytesSent returns the BytesSent field value if set, zero value otherwise.
func (o *Connection) GetBytesSent() int64 {
	if o == nil || IsNil(o.BytesSent) {
		var ret int64
		return ret
	}
	return *o.BytesSent
}

// GetBytesSentOk returns a tuple with the BytesSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connection) GetBytesSentOk() (*int64, bool) {
	if o == nil || IsNil(o.BytesSent) {
		return nil, false
	}
	return o.BytesSent, true
}

// HasBytesSent returns a boolean if a field has been set.
func (o *Connection) HasBytesSent() bool {
	if o != nil && !IsNil(o.BytesSent) {
		return true
	}

	return false
}

// SetBytesSent gets a reference to the given int64 and assigns it to the BytesSent field.
func (o *Connection) SetBytesSent(v int64) {
	o.BytesSent = &v
}

// GetEvents returns the Events field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connection) GetEvents() []ReportEvent {
	if o == nil {
		var ret []ReportEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connection) GetEventsOk() ([]ReportEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *Connection) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []ReportEvent and assigns it to the Events field.
func (o *Connection) SetEvents(v []ReportEvent) {
	o.Events = v
}

// GetJa3 returns the Ja3 field value if set, zero value otherwise.
func (o *Connection) GetJa3() string {
	if o == nil || IsNil(o.Ja3) {
		var ret string
		return ret
	}
	return *o.Ja3
}

// GetJa3Ok returns a tuple with the Ja3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connection) GetJa3Ok() (*string, bool) {
	if o == nil || IsNil(o.Ja3) {
		return nil, false
	}
	return o.Ja3, true
}

// HasJa3 returns a boolean if a field has been set.
func (o *Connection) HasJa3() bool {
	if o != nil && !IsNil(o.Ja3) {
		return true
	}

	return false
}

// SetJa3 gets a reference to the given string and assigns it to the Ja3 field.
func (o *Connection) SetJa3(v string) {
	o.Ja3 = &v
}

// GetJa3s returns the Ja3s field value if set, zero value otherwise.
func (o *Connection) GetJa3s() string {
	if o == nil || IsNil(o.Ja3s) {
		var ret string
		return ret
	}
	return *o.Ja3s
}

// GetJa3sOk returns a tuple with the Ja3s field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connection) GetJa3sOk() (*string, bool) {
	if o == nil || IsNil(o.Ja3s) {
		return nil, false
	}
	return o.Ja3s, true
}

// HasJa3s returns a boolean if a field has been set.
func (o *Connection) HasJa3s() bool {
	if o != nil && !IsNil(o.Ja3s) {
		return true
	}

	return false
}

// SetJa3s gets a reference to the given string and assigns it to the Ja3s field.
func (o *Connection) SetJa3s(v string) {
	o.Ja3s = &v
}

// GetLocalIp returns the LocalIp field value
func (o *Connection) GetLocalIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocalIp
}

// GetLocalIpOk returns a tuple with the LocalIp field value
// and a boolean to check if the value has been set.
func (o *Connection) GetLocalIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocalIp, true
}

// SetLocalIp sets field value
func (o *Connection) SetLocalIp(v string) {
	o.LocalIp = v
}

// GetLocalPort returns the LocalPort field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Connection) GetLocalPort() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.LocalPort
}

// GetLocalPortOk returns a tuple with the LocalPort field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connection) GetLocalPortOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LocalPort) {
		return nil, false
	}
	return &o.LocalPort, true
}

// SetLocalPort sets field value
func (o *Connection) SetLocalPort(v interface{}) {
	o.LocalPort = v
}

// GetProtocol returns the Protocol field value
func (o *Connection) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *Connection) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *Connection) SetProtocol(v string) {
	o.Protocol = v
}

// GetRemoteIp returns the RemoteIp field value
func (o *Connection) GetRemoteIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteIp
}

// GetRemoteIpOk returns a tuple with the RemoteIp field value
// and a boolean to check if the value has been set.
func (o *Connection) GetRemoteIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteIp, true
}

// SetRemoteIp sets field value
func (o *Connection) SetRemoteIp(v string) {
	o.RemoteIp = v
}

// GetRemotePort returns the RemotePort field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Connection) GetRemotePort() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.RemotePort
}

// GetRemotePortOk returns a tuple with the RemotePort field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connection) GetRemotePortOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RemotePort) {
		return nil, false
	}
	return &o.RemotePort, true
}

// SetRemotePort sets field value
func (o *Connection) SetRemotePort(v interface{}) {
	o.RemotePort = v
}

// GetTcpCarvedFiles returns the TcpCarvedFiles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connection) GetTcpCarvedFiles() []TcpCarvedFile {
	if o == nil {
		var ret []TcpCarvedFile
		return ret
	}
	return o.TcpCarvedFiles
}

// GetTcpCarvedFilesOk returns a tuple with the TcpCarvedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connection) GetTcpCarvedFilesOk() ([]TcpCarvedFile, bool) {
	if o == nil || IsNil(o.TcpCarvedFiles) {
		return nil, false
	}
	return o.TcpCarvedFiles, true
}

// HasTcpCarvedFiles returns a boolean if a field has been set.
func (o *Connection) HasTcpCarvedFiles() bool {
	if o != nil && !IsNil(o.TcpCarvedFiles) {
		return true
	}

	return false
}

// SetTcpCarvedFiles gets a reference to the given []TcpCarvedFile and assigns it to the TcpCarvedFiles field.
func (o *Connection) SetTcpCarvedFiles(v []TcpCarvedFile) {
	o.TcpCarvedFiles = v
}

func (o Connection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Connection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BytesReceived) {
		toSerialize["bytes_received"] = o.BytesReceived
	}
	if !IsNil(o.BytesSent) {
		toSerialize["bytes_sent"] = o.BytesSent
	}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Ja3) {
		toSerialize["ja3"] = o.Ja3
	}
	if !IsNil(o.Ja3s) {
		toSerialize["ja3s"] = o.Ja3s
	}
	toSerialize["local_ip"] = o.LocalIp
	if o.LocalPort != nil {
		toSerialize["local_port"] = o.LocalPort
	}
	toSerialize["protocol"] = o.Protocol
	toSerialize["remote_ip"] = o.RemoteIp
	if o.RemotePort != nil {
		toSerialize["remote_port"] = o.RemotePort
	}
	if o.TcpCarvedFiles != nil {
		toSerialize["tcp_carved_files"] = o.TcpCarvedFiles
	}
	return toSerialize, nil
}

func (o *Connection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"local_ip",
		"local_port",
		"protocol",
		"remote_ip",
		"remote_port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnection := _Connection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnection)

	if err != nil {
		return err
	}

	*o = Connection(varConnection)

	return err
}

type NullableConnection struct {
	value *Connection
	isSet bool
}

func (v NullableConnection) Get() *Connection {
	return v.value
}

func (v *NullableConnection) Set(val *Connection) {
	v.value = val
	v.isSet = true
}

func (v NullableConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnection(val *Connection) *NullableConnection {
	return &NullableConnection{value: val, isSet: true}
}

func (v NullableConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


