/*
RevEng.AI API

RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GetDataTypeHistoryBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDataTypeHistoryBody{}

// GetDataTypeHistoryBody struct for GetDataTypeHistoryBody
type GetDataTypeHistoryBody struct {
	// Every version of the type, newest first. The first element is the current value, so the list is never empty; a type that has never been edited has that one element only.
	Versions []DataTypeVersion `json:"versions"`
	AdditionalProperties map[string]interface{}
}

type _GetDataTypeHistoryBody GetDataTypeHistoryBody

// NewGetDataTypeHistoryBody instantiates a new GetDataTypeHistoryBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDataTypeHistoryBody(versions []DataTypeVersion) *GetDataTypeHistoryBody {
	this := GetDataTypeHistoryBody{}
	this.Versions = versions
	return &this
}

// NewGetDataTypeHistoryBodyWithDefaults instantiates a new GetDataTypeHistoryBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDataTypeHistoryBodyWithDefaults() *GetDataTypeHistoryBody {
	this := GetDataTypeHistoryBody{}
	return &this
}

// GetVersions returns the Versions field value
func (o *GetDataTypeHistoryBody) GetVersions() []DataTypeVersion {
	if o == nil {
		var ret []DataTypeVersion
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *GetDataTypeHistoryBody) GetVersionsOk() ([]DataTypeVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *GetDataTypeHistoryBody) SetVersions(v []DataTypeVersion) {
	o.Versions = v
}

func (o GetDataTypeHistoryBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDataTypeHistoryBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versions"] = o.Versions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetDataTypeHistoryBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDataTypeHistoryBody := _GetDataTypeHistoryBody{}

	err = json.Unmarshal(data, &varGetDataTypeHistoryBody)

	if err != nil {
		return err
	}

	*o = GetDataTypeHistoryBody(varGetDataTypeHistoryBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetDataTypeHistoryBody struct {
	value *GetDataTypeHistoryBody
	isSet bool
}

func (v NullableGetDataTypeHistoryBody) Get() *GetDataTypeHistoryBody {
	return v.value
}

func (v *NullableGetDataTypeHistoryBody) Set(val *GetDataTypeHistoryBody) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDataTypeHistoryBody) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDataTypeHistoryBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDataTypeHistoryBody(val *GetDataTypeHistoryBody) *NullableGetDataTypeHistoryBody {
	return &NullableGetDataTypeHistoryBody{value: val, isSet: true}
}

func (v NullableGetDataTypeHistoryBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDataTypeHistoryBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


