/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecurityChecksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityChecksResponse{}

// SecurityChecksResponse struct for SecurityChecksResponse
type SecurityChecksResponse struct {
	BinaryId int32 `json:"binary_id"`
	TotalResults int32 `json:"total_results"`
	Results []SecurityChecksResult `json:"results"`
}

type _SecurityChecksResponse SecurityChecksResponse

// NewSecurityChecksResponse instantiates a new SecurityChecksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityChecksResponse(binaryId int32, totalResults int32, results []SecurityChecksResult) *SecurityChecksResponse {
	this := SecurityChecksResponse{}
	this.BinaryId = binaryId
	this.TotalResults = totalResults
	this.Results = results
	return &this
}

// NewSecurityChecksResponseWithDefaults instantiates a new SecurityChecksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityChecksResponseWithDefaults() *SecurityChecksResponse {
	this := SecurityChecksResponse{}
	return &this
}

// GetBinaryId returns the BinaryId field value
func (o *SecurityChecksResponse) GetBinaryId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BinaryId
}

// GetBinaryIdOk returns a tuple with the BinaryId field value
// and a boolean to check if the value has been set.
func (o *SecurityChecksResponse) GetBinaryIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BinaryId, true
}

// SetBinaryId sets field value
func (o *SecurityChecksResponse) SetBinaryId(v int32) {
	o.BinaryId = v
}

// GetTotalResults returns the TotalResults field value
func (o *SecurityChecksResponse) GetTotalResults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalResults
}

// GetTotalResultsOk returns a tuple with the TotalResults field value
// and a boolean to check if the value has been set.
func (o *SecurityChecksResponse) GetTotalResultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalResults, true
}

// SetTotalResults sets field value
func (o *SecurityChecksResponse) SetTotalResults(v int32) {
	o.TotalResults = v
}

// GetResults returns the Results field value
func (o *SecurityChecksResponse) GetResults() []SecurityChecksResult {
	if o == nil {
		var ret []SecurityChecksResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *SecurityChecksResponse) GetResultsOk() ([]SecurityChecksResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *SecurityChecksResponse) SetResults(v []SecurityChecksResult) {
	o.Results = v
}

func (o SecurityChecksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityChecksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["binary_id"] = o.BinaryId
	toSerialize["total_results"] = o.TotalResults
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *SecurityChecksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"binary_id",
		"total_results",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecurityChecksResponse := _SecurityChecksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecurityChecksResponse)

	if err != nil {
		return err
	}

	*o = SecurityChecksResponse(varSecurityChecksResponse)

	return err
}

type NullableSecurityChecksResponse struct {
	value *SecurityChecksResponse
	isSet bool
}

func (v NullableSecurityChecksResponse) Get() *SecurityChecksResponse {
	return v.value
}

func (v *NullableSecurityChecksResponse) Set(val *SecurityChecksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityChecksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityChecksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityChecksResponse(val *SecurityChecksResponse) *NullableSecurityChecksResponse {
	return &NullableSecurityChecksResponse{value: val, isSet: true}
}

func (v NullableSecurityChecksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityChecksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


