/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateFunctionDataTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFunctionDataTypes{}

// UpdateFunctionDataTypes struct for UpdateFunctionDataTypes
type UpdateFunctionDataTypes struct {
	// Version of the function data types, used to check this update is not overwriting a newer one
	DataTypesVersion int32 `json:"data_types_version"`
	// Function data types information to update
	DataTypes FunctionInfoInput `json:"data_types"`
}

type _UpdateFunctionDataTypes UpdateFunctionDataTypes

// NewUpdateFunctionDataTypes instantiates a new UpdateFunctionDataTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFunctionDataTypes(dataTypesVersion int32, dataTypes FunctionInfoInput) *UpdateFunctionDataTypes {
	this := UpdateFunctionDataTypes{}
	this.DataTypesVersion = dataTypesVersion
	this.DataTypes = dataTypes
	return &this
}

// NewUpdateFunctionDataTypesWithDefaults instantiates a new UpdateFunctionDataTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFunctionDataTypesWithDefaults() *UpdateFunctionDataTypes {
	this := UpdateFunctionDataTypes{}
	return &this
}

// GetDataTypesVersion returns the DataTypesVersion field value
func (o *UpdateFunctionDataTypes) GetDataTypesVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DataTypesVersion
}

// GetDataTypesVersionOk returns a tuple with the DataTypesVersion field value
// and a boolean to check if the value has been set.
func (o *UpdateFunctionDataTypes) GetDataTypesVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataTypesVersion, true
}

// SetDataTypesVersion sets field value
func (o *UpdateFunctionDataTypes) SetDataTypesVersion(v int32) {
	o.DataTypesVersion = v
}

// GetDataTypes returns the DataTypes field value
func (o *UpdateFunctionDataTypes) GetDataTypes() FunctionInfoInput {
	if o == nil {
		var ret FunctionInfoInput
		return ret
	}

	return o.DataTypes
}

// GetDataTypesOk returns a tuple with the DataTypes field value
// and a boolean to check if the value has been set.
func (o *UpdateFunctionDataTypes) GetDataTypesOk() (*FunctionInfoInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataTypes, true
}

// SetDataTypes sets field value
func (o *UpdateFunctionDataTypes) SetDataTypes(v FunctionInfoInput) {
	o.DataTypes = v
}

func (o UpdateFunctionDataTypes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFunctionDataTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data_types_version"] = o.DataTypesVersion
	toSerialize["data_types"] = o.DataTypes
	return toSerialize, nil
}

func (o *UpdateFunctionDataTypes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data_types_version",
		"data_types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateFunctionDataTypes := _UpdateFunctionDataTypes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateFunctionDataTypes)

	if err != nil {
		return err
	}

	*o = UpdateFunctionDataTypes(varUpdateFunctionDataTypes)

	return err
}

type NullableUpdateFunctionDataTypes struct {
	value *UpdateFunctionDataTypes
	isSet bool
}

func (v NullableUpdateFunctionDataTypes) Get() *UpdateFunctionDataTypes {
	return v.value
}

func (v *NullableUpdateFunctionDataTypes) Set(val *UpdateFunctionDataTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFunctionDataTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFunctionDataTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFunctionDataTypes(val *UpdateFunctionDataTypes) *NullableUpdateFunctionDataTypes {
	return &NullableUpdateFunctionDataTypes{value: val, isSet: true}
}

func (v NullableUpdateFunctionDataTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFunctionDataTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


