/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Process type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Process{}

// Process struct for Process
type Process struct {
	Pid int32 `json:"pid"`
	Procname string `json:"procname"`
	ExecutableName string `json:"executable_name"`
	Args []string `json:"args"`
	TsFrom float32 `json:"ts_from"`
	TsTo NullableFloat32 `json:"ts_to"`
	Children []interface{} `json:"children"`
}

type _Process Process

// NewProcess instantiates a new Process object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcess(pid int32, procname string, executableName string, args []string, tsFrom float32, tsTo NullableFloat32, children []interface{}) *Process {
	this := Process{}
	this.Pid = pid
	this.Procname = procname
	this.ExecutableName = executableName
	this.Args = args
	this.TsFrom = tsFrom
	this.TsTo = tsTo
	this.Children = children
	return &this
}

// NewProcessWithDefaults instantiates a new Process object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessWithDefaults() *Process {
	this := Process{}
	return &this
}

// GetPid returns the Pid field value
func (o *Process) GetPid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Pid
}

// GetPidOk returns a tuple with the Pid field value
// and a boolean to check if the value has been set.
func (o *Process) GetPidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pid, true
}

// SetPid sets field value
func (o *Process) SetPid(v int32) {
	o.Pid = v
}

// GetProcname returns the Procname field value
func (o *Process) GetProcname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Procname
}

// GetProcnameOk returns a tuple with the Procname field value
// and a boolean to check if the value has been set.
func (o *Process) GetProcnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Procname, true
}

// SetProcname sets field value
func (o *Process) SetProcname(v string) {
	o.Procname = v
}

// GetExecutableName returns the ExecutableName field value
func (o *Process) GetExecutableName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutableName
}

// GetExecutableNameOk returns a tuple with the ExecutableName field value
// and a boolean to check if the value has been set.
func (o *Process) GetExecutableNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutableName, true
}

// SetExecutableName sets field value
func (o *Process) SetExecutableName(v string) {
	o.ExecutableName = v
}

// GetArgs returns the Args field value
func (o *Process) GetArgs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *Process) GetArgsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *Process) SetArgs(v []string) {
	o.Args = v
}

// GetTsFrom returns the TsFrom field value
func (o *Process) GetTsFrom() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TsFrom
}

// GetTsFromOk returns a tuple with the TsFrom field value
// and a boolean to check if the value has been set.
func (o *Process) GetTsFromOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TsFrom, true
}

// SetTsFrom sets field value
func (o *Process) SetTsFrom(v float32) {
	o.TsFrom = v
}

// GetTsTo returns the TsTo field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *Process) GetTsTo() float32 {
	if o == nil || o.TsTo.Get() == nil {
		var ret float32
		return ret
	}

	return *o.TsTo.Get()
}

// GetTsToOk returns a tuple with the TsTo field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Process) GetTsToOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TsTo.Get(), o.TsTo.IsSet()
}

// SetTsTo sets field value
func (o *Process) SetTsTo(v float32) {
	o.TsTo.Set(&v)
}

// GetChildren returns the Children field value
func (o *Process) GetChildren() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value
// and a boolean to check if the value has been set.
func (o *Process) GetChildrenOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Children, true
}

// SetChildren sets field value
func (o *Process) SetChildren(v []interface{}) {
	o.Children = v
}

func (o Process) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Process) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pid"] = o.Pid
	toSerialize["procname"] = o.Procname
	toSerialize["executable_name"] = o.ExecutableName
	toSerialize["args"] = o.Args
	toSerialize["ts_from"] = o.TsFrom
	toSerialize["ts_to"] = o.TsTo.Get()
	toSerialize["children"] = o.Children
	return toSerialize, nil
}

func (o *Process) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pid",
		"procname",
		"executable_name",
		"args",
		"ts_from",
		"ts_to",
		"children",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcess := _Process{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProcess)

	if err != nil {
		return err
	}

	*o = Process(varProcess)

	return err
}

type NullableProcess struct {
	value *Process
	isSet bool
}

func (v NullableProcess) Get() *Process {
	return v.value
}

func (v *NullableProcess) Set(val *Process) {
	v.value = val
	v.isSet = true
}

func (v NullableProcess) IsSet() bool {
	return v.isSet
}

func (v *NullableProcess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcess(val *Process) *NullableProcess {
	return &NullableProcess{value: val, isSet: true}
}

func (v NullableProcess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


