/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkOverviewMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkOverviewMetadata{}

// NetworkOverviewMetadata struct for NetworkOverviewMetadata
type NetworkOverviewMetadata struct {
	Host string `json:"host"`
	CountryCode string `json:"country_code"`
	ASN string `json:"ASN"`
	Type string `json:"type"`
}

type _NetworkOverviewMetadata NetworkOverviewMetadata

// NewNetworkOverviewMetadata instantiates a new NetworkOverviewMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkOverviewMetadata(host string, countryCode string, aSN string, type_ string) *NetworkOverviewMetadata {
	this := NetworkOverviewMetadata{}
	this.Host = host
	this.CountryCode = countryCode
	this.ASN = aSN
	this.Type = type_
	return &this
}

// NewNetworkOverviewMetadataWithDefaults instantiates a new NetworkOverviewMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkOverviewMetadataWithDefaults() *NetworkOverviewMetadata {
	this := NetworkOverviewMetadata{}
	return &this
}

// GetHost returns the Host field value
func (o *NetworkOverviewMetadata) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewMetadata) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *NetworkOverviewMetadata) SetHost(v string) {
	o.Host = v
}

// GetCountryCode returns the CountryCode field value
func (o *NetworkOverviewMetadata) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewMetadata) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *NetworkOverviewMetadata) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetASN returns the ASN field value
func (o *NetworkOverviewMetadata) GetASN() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ASN
}

// GetASNOk returns a tuple with the ASN field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewMetadata) GetASNOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ASN, true
}

// SetASN sets field value
func (o *NetworkOverviewMetadata) SetASN(v string) {
	o.ASN = v
}

// GetType returns the Type field value
func (o *NetworkOverviewMetadata) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NetworkOverviewMetadata) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NetworkOverviewMetadata) SetType(v string) {
	o.Type = v
}

func (o NetworkOverviewMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkOverviewMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	toSerialize["country_code"] = o.CountryCode
	toSerialize["ASN"] = o.ASN
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *NetworkOverviewMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"country_code",
		"ASN",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkOverviewMetadata := _NetworkOverviewMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkOverviewMetadata)

	if err != nil {
		return err
	}

	*o = NetworkOverviewMetadata(varNetworkOverviewMetadata)

	return err
}

type NullableNetworkOverviewMetadata struct {
	value *NetworkOverviewMetadata
	isSet bool
}

func (v NullableNetworkOverviewMetadata) Get() *NetworkOverviewMetadata {
	return v.value
}

func (v *NullableNetworkOverviewMetadata) Set(val *NetworkOverviewMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkOverviewMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkOverviewMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkOverviewMetadata(val *NetworkOverviewMetadata) *NullableNetworkOverviewMetadata {
	return &NullableNetworkOverviewMetadata{value: val, isSet: true}
}

func (v NullableNetworkOverviewMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkOverviewMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


