/*
RevEng.AI API

RevEng.AI is Similarity Search Engine for executable binaries

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BaseResponseSecurityChecksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponseSecurityChecksResponse{}

// BaseResponseSecurityChecksResponse struct for BaseResponseSecurityChecksResponse
type BaseResponseSecurityChecksResponse struct {
	// Response status on whether the request succeeded
	Status *bool `json:"status,omitempty"`
	Data NullableSecurityChecksResponse `json:"data,omitempty"`
	Message NullableString `json:"message,omitempty"`
	Errors []ErrorModel `json:"errors,omitempty"`
	// Metadata
	Meta *MetaModel `json:"meta,omitempty"`
}

// NewBaseResponseSecurityChecksResponse instantiates a new BaseResponseSecurityChecksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponseSecurityChecksResponse() *BaseResponseSecurityChecksResponse {
	this := BaseResponseSecurityChecksResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// NewBaseResponseSecurityChecksResponseWithDefaults instantiates a new BaseResponseSecurityChecksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponseSecurityChecksResponseWithDefaults() *BaseResponseSecurityChecksResponse {
	this := BaseResponseSecurityChecksResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BaseResponseSecurityChecksResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseSecurityChecksResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BaseResponseSecurityChecksResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *BaseResponseSecurityChecksResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseSecurityChecksResponse) GetData() SecurityChecksResponse {
	if o == nil || IsNil(o.Data.Get()) {
		var ret SecurityChecksResponse
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseSecurityChecksResponse) GetDataOk() (*SecurityChecksResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *BaseResponseSecurityChecksResponse) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableSecurityChecksResponse and assigns it to the Data field.
func (o *BaseResponseSecurityChecksResponse) SetData(v SecurityChecksResponse) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *BaseResponseSecurityChecksResponse) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *BaseResponseSecurityChecksResponse) UnsetData() {
	o.Data.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseSecurityChecksResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseSecurityChecksResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *BaseResponseSecurityChecksResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *BaseResponseSecurityChecksResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *BaseResponseSecurityChecksResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *BaseResponseSecurityChecksResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetErrors returns the Errors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseResponseSecurityChecksResponse) GetErrors() []ErrorModel {
	if o == nil {
		var ret []ErrorModel
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseResponseSecurityChecksResponse) GetErrorsOk() ([]ErrorModel, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BaseResponseSecurityChecksResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorModel and assigns it to the Errors field.
func (o *BaseResponseSecurityChecksResponse) SetErrors(v []ErrorModel) {
	o.Errors = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BaseResponseSecurityChecksResponse) GetMeta() MetaModel {
	if o == nil || IsNil(o.Meta) {
		var ret MetaModel
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponseSecurityChecksResponse) GetMetaOk() (*MetaModel, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BaseResponseSecurityChecksResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given MetaModel and assigns it to the Meta field.
func (o *BaseResponseSecurityChecksResponse) SetMeta(v MetaModel) {
	o.Meta = &v
}

func (o BaseResponseSecurityChecksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponseSecurityChecksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBaseResponseSecurityChecksResponse struct {
	value *BaseResponseSecurityChecksResponse
	isSet bool
}

func (v NullableBaseResponseSecurityChecksResponse) Get() *BaseResponseSecurityChecksResponse {
	return v.value
}

func (v *NullableBaseResponseSecurityChecksResponse) Set(val *BaseResponseSecurityChecksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponseSecurityChecksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponseSecurityChecksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponseSecurityChecksResponse(val *BaseResponseSecurityChecksResponse) *NullableBaseResponseSecurityChecksResponse {
	return &NullableBaseResponseSecurityChecksResponse{value: val, isSet: true}
}

func (v NullableBaseResponseSecurityChecksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponseSecurityChecksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


